import re

DATA = {
    "阿姨": "Danh từ",
    "啊": "Trợ từ",
    "矮": "Tính từ",
    "爱好": "Danh từ",
    "安静": "Tính từ",
    "把": "Giới từ / Lượng từ",
    "班": "Danh từ",
    "搬": "Động từ",
    "半": "Số từ",
    "办法": "Danh từ",
    "办公室": "Danh từ",
    "帮忙": "Động từ",
    "包": "Danh từ",
    "饱": "Tính từ",
    "北方": "Danh từ",
    "被": "Giới từ",
    "鼻子": "Danh từ",
    "比较": "Phó từ / Động từ",
    "比赛": "Danh từ / Động từ",
    "笔记本": "Danh từ",
    "必须": "Phó từ",
    "变化": "Danh từ / Động từ",
    "表示": "Động từ",
    "表演": "Động từ / Danh từ",
    "别人": "Đại từ",
    "冰箱": "Danh từ",
    "不但…而且": "Liên từ",
    "才": "Phó từ",
    "菜单": "Danh từ",
    "参加": "Động từ",
    "草": "Danh từ",
    "层": "Lượng từ",
    "差": "Tính từ / Động từ",
    "超市": "Danh từ",
    "衬衫": "Danh từ",
    "成绩": "Danh từ",
    "城市": "Danh từ",
    "迟到": "Động từ",
    "除了": "Giới từ",
    "厨房": "Danh từ",
    "出现": "Động từ",
    "春": "Danh từ",
    "词典": "Danh từ",
    "聪明": "Tính từ",
    "打扫": "Động từ",
    "打算": "Động từ / Danh từ",
    "带": "Động từ",
    "担心": "Động từ",
    "蛋糕": "Danh từ",
    "当然": "Phó từ / Tính từ",
    "地": "Trợ từ",
    "灯": "Danh từ",
    "地方": "Danh từ",
    "地铁": "Danh từ",
    "地图": "Danh từ",
    "电梯": "Danh từ",
    "电子邮件": "Danh từ",
    "东": "Danh từ",
    "冬": "Danh từ",
    "动物": "Danh từ",
    "短": "Tính từ",
    "段": "Lượng từ",
    "锻炼": "Động từ",
    "多么": "Phó từ",
    "饿": "Tính từ",
    "耳朵": "Danh từ",
    "发": "Động từ",
    "发烧": "Động từ",
    "发现": "Động từ",
    "方便": "Tính từ",
    "放": "Động từ",
    "放心": "Động từ",
    "分": "Lượng từ / Động từ",
    "附近": "Danh từ",
    "复习": "Động từ",
    "干净": "Tính từ",
    "感冒": "Động từ / Danh từ",
    "刚才": "Danh từ chỉ thời gian",
    "跟": "Giới từ / Động từ",
    "根据": "Giới từ / Căn cứ",
    "更": "Phó từ",
    "公斤": "Lượng từ",
    "公园": "Danh từ",
    "故事": "Danh từ",
    "刮风": "Động từ",
    "关": "Động từ",
    "关系": "Danh từ",
    "关心": "Động từ",
    "关于": "Giới từ",
    "国家": "Danh từ",
    "果汁": "Danh từ",
    "过": "Trợ từ / Động từ",
    "过去": "Danh từ chỉ thời gian",
    "还是": "Liên từ / Phó từ",
    "害怕": "Động từ",
    "寒假": "Danh từ",
    "河": "Danh từ",
    "黑板": "Danh từ",
    "后来": "Danh từ chỉ thời gian",
    "护照": "Danh từ",
    "花": "Động từ / Danh từ",
    "花园": "Danh từ",
    "画": "Động từ / Danh từ",
    "坏": "Tính từ",
    "欢迎": "Động từ",
    "环境": "Danh từ",
    "换": "Động từ",
    "黄": "Tính từ",
    "回答": "Động từ",
    "回忆": "Danh từ / Động từ",
    "会议": "Danh từ",
    "或者": "Liên từ",
    "几乎": "Phó từ",
    "机会": "Danh từ",
    "极": "Phó từ",
    "季节": "Danh từ",
    "记得": "Động từ",
    "记住": "Động từ",
    "检查": "Động từ / Danh từ",
    "简单": "Tính từ",
    "健康": "Tính từ / Danh từ",
    "见面": "Động từ",
    "讲": "Động từ",
    "教": "Động từ",
    "脚": "Danh từ",
    "角": "Lượng từ",
    "接": "Động từ",
    "街道": "Danh từ",
    "节目": "Danh từ",
    "节日": "Danh từ",
    "结婚": "Động từ",
    "结束": "Động từ",
    "解决": "Động từ",
    "借": "Động từ",
    "经常": "Phó từ",
    "经过": "Giới từ / Động từ",
    "经理": "Danh từ",
    "久": "Tính từ",
    "旧": "Tính từ",
    "举行": "Động từ",
    "句子": "Danh từ",
    "决定": "Động từ / Danh từ",
    "可爱": "Tính từ",
    "渴": "Tính từ",
    "客人": "Danh từ",
    "空调": "Danh từ",
    "口": "Lượng từ / Danh từ",
    "哭": "Động từ",
    "裤子": "Danh từ",
    "筷子": "Danh từ",
    "蓝": "Tính từ",
    "老": "Tính từ",
    "离开": "Động từ",
    "礼物": "Danh từ",
    "历史": "Danh từ",
    "脸": "Danh từ",
    "练习": "Động từ / Danh từ",
    "辆": "Lượng từ",
    "了解": "Động từ",
    "邻居": "Danh từ",
    "留学": "Động từ",
    "楼": "Danh từ",
    "绿": "Tính từ",
    "马": "Danh từ",
    "马上": "Phó từ",
    "满意": "Tính từ / Động từ",
    "帽子": "Danh từ",
    "米": "Lượng từ / Danh từ",
    "面包": "Danh từ",
    "明白": "Tính từ / Động từ",
    "拿": "Động từ",
    "奶奶": "Danh từ",
    "南": "Danh từ",
    "南方": "Danh từ",
    "难": "Tính từ",
    "难过": "Tính từ",
    "年级": "Danh từ",
    "年轻": "Tính từ",
    "鸟": "Danh từ",
    "努力": "Tính từ / Động từ",
    "爬山": "Động từ",
    "盘子": "Danh từ",
    "胖": "Tính từ",
    "啤酒": "Danh từ",
    "皮鞋": "Danh từ",
    "瓶子": "Danh từ",
    "普通话": "Danh từ",
    "骑": "Động từ",
    "奇怪": "Tính từ",
    "其他": "Đại từ",
    "其实": "Phó từ",
    "起来": "Động từ",
    "清楚": "Tính từ",
    "请假": "Động từ",
    "秋": "Danh từ",
    "裙子": "Danh từ",
    "然后": "Liên từ / Phó từ",
    "热情": "Tính từ",
    "认为": "Động từ",
    "认真": "Tính từ",
    "容易": "Tính từ",
    "如果": "Liên từ",
    "伞": "Danh từ",
    "上网": "Động từ",
    "生气": "Tính từ / Động từ",
    "声音": "Danh từ",
    "世界": "Danh từ",
    "瘦": "Tính từ",
    "叔叔": "Danh từ",
    "舒服": "Tính từ",
    "树": "Danh từ",
    "数学": "Danh từ",
    "刷牙": "Động từ",
    "双": "Lượng từ",
    "水平": "Danh từ",
    "司机": "Danh từ",
    "太阳": "Danh từ",
    "特别": "Tính từ / Phó từ",
    "疼": "Tính từ / Động từ",
    "提高": "Động từ",
    "体育": "Danh từ",
    "甜": "Tính từ",
    "条": "Lượng từ",
    "同事": "Danh từ",
    "同意": "Động từ",
    "头发": "Danh từ",
    "突然": "Tính từ / Phó từ",
    "图书馆": "Danh từ",
    "腿": "Danh từ",
    "完成": "Động từ",
    "碗": "Danh từ / Lượng từ",
    "晚": "Tính từ",
    "忘记": "Động từ",
    "为": "Giới từ",
    "为了": "Giới từ",
    "位": "Lượng từ",
    "文化": "Danh từ",
    "西": "Danh từ",
    "习惯": "Danh từ / Động từ",
    "洗手间": "Danh từ",
    "洗澡": "Động từ",
    "夏": "Danh từ",
    "先": "Phó từ",
    "相信": "Động từ",
    "香蕉": "Danh từ",
    "向": "Giới từ",
    "像": "Động từ",
    "小心": "Tính từ / Động từ",
    "校长": "Danh từ",
    "新闻": "Danh từ",
    "新鲜": "Tính từ",
    "信": "Danh từ",
    "信用卡": "Danh từ",
    "行李箱": "Danh từ",
    "兴趣": "Danh từ",
    "熊猫": "Danh từ",
    "需要": "Động từ",
    "选择": "Động từ / Danh từ",
    "要求": "Động từ / Danh từ",
    "爷爷": "Danh từ",
    "一般": "Tính từ / Phó từ",
    "一边": "Phó từ",
    "一定": "Tính từ / Phó từ",
    "一共": "Phó từ",
    "一会儿": "Đại từ / Phó từ",
    "一样": "Tính từ",
    "一直": "Phó từ",
    "以后": "Danh từ chỉ thời gian",
    "以前": "Danh từ chỉ thời gian",
    "以为": "Động từ",
    "音乐": "Danh từ",
    "银行": "Danh từ",
    "应该": "Động từ năng nguyện",
    "影响": "Động từ / Danh từ",
    "用": "Động từ",
    "游戏": "Danh từ",
    "有名": "Tính từ",
    "又": "Phó từ",
    "遇到": "Động từ",
    "元": "Lượng từ",
    "愿意": "Động từ năng nguyện",
    "月亮": "Danh từ",
    "越": "Phó từ",
    "站": "Động từ / Danh từ",
    "张": "Lượng từ",
    "照顾": "Động từ",
    "照片": "Danh từ",
    "照相机": "Danh từ",
    "着急": "Tính từ",
    "只": "Phó từ / Lượng từ",
    "只有": "Liên từ / Phó từ",
    "中间": "Danh từ phương hướng",
    "终于": "Phó từ",
    "种": "Lượng từ",
    "重要": "Tính từ",
    "周末": "Danh từ",
    "主要": "Tính từ",
    "注意": "Động từ",
    "自己": "Đại từ",
    "总是": "Phó từ",
    "嘴": "Danh từ",
    "最近": "Danh từ chỉ thời gian",
    "作业": "Danh từ",
    "作用": "Danh từ"
}

def process_file(filename):
    with open(filename, "r", encoding="utf-8") as f:
        content = f.read()

    pattern = r'\[\s*"([^"]+)"\s*,\s*"([^"]+)"\s*,\s*"([^"]+)"\s*(,[^\]]*)?\]'
    matches = list(re.finditer(pattern, content))
    
    new_content = content
    for i in range(len(matches) - 1, -1, -1):
        m = matches[i]
        hz, py, vn, extras = m.group(1), m.group(2), m.group(3), m.group(4)
        full_match = m.group(0)
        m_start = m.start()
        
        # Use our precomputed pos
        pos = DATA.get(hz, "")
        
        if extras and extras.count(',') >= 1:
            # Maybe there are 4+ elements already. 
            parts = extras.strip(',').split(',')
            # We reconstruct 
            # w[3] was "" empty string from the last failed attempt
            rest = ",".join(parts[1:])
            if rest:
                new_str = f'["{hz}","{py}","{vn}","{pos}",{rest}]'
            else:
                new_str = f'["{hz}","{py}","{vn}","{pos}"]'
        else:
            new_str = f'["{hz}","{py}","{vn}","{pos}"]'

        # Safely overwrite
        new_content = new_content[:m_start] + new_content[m_start:].replace(full_match, new_str, 1)

    with open(filename, "w", encoding="utf-8") as f:
        f.write(new_content)

process_file("words_hsk3.js")
print("Done writing fallback for HSK 3")
