// HSK 5 Part 1 - 650 từ cao cấp (phần 1)
const HSK5_1 = [
 ["爱护","àihù","yêu quý, bảo vệ","Động từ"],
 ["爱惜","àixī","quý trọng","Động từ"],
 ["爱心","àixīn","lòng yêu thương","Danh từ"],
 ["安慰","ānwèi","an ủi","Động từ"],
 ["安装","ānzhuāng","lắp đặt","Động từ"],
 ["岸","àn","bờ","Danh từ"],
 ["暗","àn","tối, âm thầm","Phó từ"],
 ["熬夜","áo yè","thức khuya","Động từ"],
 ["把握","bǎwò","nắm bắt","Động từ"],
 ["摆","bǎi","bày, đặt","Động từ"],
 ["办理","bànlǐ","xử lý, làm thủ tục","Danh từ"],
 ["傍晚","bàngwǎn","chiều tối","Danh từ chỉ thời gian"],
 ["包裹","bāoguǒ","bưu kiện","Động từ"],
 ["包含","bāohán","bao hàm","Động từ"],
 ["薄","báo","mỏng","Tính từ"],
 ["宝贝","bǎobèi","bảo bối","Danh từ riêng"],
 ["宝贵","bǎoguì","quý giá","Danh từ riêng"],
 ["保持","bǎochí","duy trì","Động từ"],
 ["保存","bǎocún","bảo quản","Động từ"],
 ["保险","bǎoxiǎn","bảo hiểm","Danh từ"],
 ["报到","bào dào","trình diện","Động từ"],
 ["报道","bàodào","báo đạo, đưa tin","Động từ"],
 ["报告","bàogào","báo cáo","Danh từ"],
 ["报社","bàoshè","tòa soạn báo","Danh từ"],
 ["悲观","bēiguān","bi quan","Tính từ"],
 ["背","bèi","lưng, cõng","Động từ"],
 ["背景","bèijǐng","bối cảnh","Danh từ"],
 ["被子","bèizi","chăn","Danh từ"],
 ["本科","běnkē","đại học (cử nhân)","Đại từ"],
 ["本领","běnlǐng","khả năng","Danh từ"],
 ["本质","běnzhì","bản chất","Danh từ"],
 ["比例","bǐlì","tỷ lệ","Danh từ"],
 ["彼此","bǐcǐ","lẫn nhau","Đại từ"],
 ["必然","bìrán","tất nhiên","Phó từ"],
 ["必要","bìyào","cần thiết","Phó từ"],
 ["毕竟","bìjìng","cho dù sao","Phó từ"],
 ["避免","bìmiǎn","tránh","Động từ"],
 ["编辑","biānjí","biên tập","Danh từ"],
 ["鞭炮","biānpào","pháo","Danh từ"],
 ["辩论","biànlùn","tranh luận","Danh từ"],
 ["标点","biāodiǎn","dấu chấm câu","Danh từ"],
 ["标志","biāozhì","biểu tượng","Danh từ"],
 ["表达","biǎodá","biểu đạt","Động từ"],
 ["表面","biǎomiàn","bề mặt","Danh từ"],
 ["表明","biǎomíng","biểu minh","Động từ"],
 ["表情","biǎoqíng","biểu cảm","Danh từ"],
 ["表现","biǎoxiàn","thể hiện","Động từ"],
 ["冰激凌","bīngjīlíng","kem","Danh từ"],
 ["病毒","bìngdú","vi rút","Danh từ"],
 ["玻璃","bōli","kính, thủy tinh","Danh từ"],
 ["播放","bōfàng","phát (đoạn phim)","Động từ"],
 ["脖子","bózi","cổ","Danh từ"],
 ["不安","bù'ān","bất an","Tính từ"],
 ["不得了","bùdéliǎo","ghê gớm","Từ láy / Quán dụng ngữ"],
 ["不断","búduàn","không ngừng","Phó từ"],
 ["不耐烦","bú nàifán","mất kiên nhẫn","Tính từ"],
 ["不然","bùrán","nếu không","Liên từ"],
 ["不如","bùrú","không bằng","Liên từ"],
 ["不要紧","bú yàojǐn","không sao","Từ láy / Quán dụng ngữ"],
 ["不可思议","bùkěsīyì","không thể tin được","Thành ngữ"],
 ["补充","bǔchōng","bổ sung","Động từ"],
 ["不足","bùzú","thiếu hụt","Tính từ"],
 ["布","bù","vải","Danh từ riêng"],
 ["步骤","bùzhòu","bước, quy trình","Danh từ"],
 ["部门","bùmén","bộ phận","Danh từ"],
 ["财产","cáichǎn","tài sản","Danh từ"],
 ["采访","cǎifǎng","phỏng vấn","Động từ"],
 ["采取","cǎiqǔ","áp dụng","Động từ"],
 ["彩虹","cǎihóng","cầu vồng","Danh từ (Khác)"],
 ["踩","cǎi","giẫm, đạp",""],
 ["参考","cānkǎo","tham khảo","Động từ"],
 ["参与","cānyù","tham gia","Động từ"],
 ["餐巾纸","cānjīnzhǐ","giấy ăn","Danh từ"],
 ["惭愧","cánkuì","xấu hổ","Tính từ"],
 ["操场","cāochǎng","sân vận động","Danh từ"],
 ["操心","cāo xīn","lo lắng","Động từ"],
 ["册","cè","quyển, tập","Lượng từ"],
 ["测验","cèyàn","kiểm tra","Động từ / Danh từ"],
 ["曾经","céngjīng","đã từng","Phó từ"],
 ["叉子","chāzi","cái nĩa","Danh từ"],
 ["差别","chābié","sự khác biệt","Phó từ"],
 ["差距","chājù","khoảng cách","Danh từ"],
 ["插","chā","cắm, chèn","Động từ"],
 ["拆","chāi","tháo, phá","Động từ"],
 ["产品","chǎnpǐn","sản phẩm","Danh từ"],
 ["产生","chǎnshēng","sản sinh, tạo ra","Danh từ"],
 ["长途","chángtú","đường dài","Phó từ"],
 ["常识","chángshí","thường thức","Danh từ"],
 ["抄","chāo","chép","Động từ"],
 ["朝","cháo","về phía, triều đại","Danh từ (Địa danh)"],
 ["朝代","cháodài","triều đại","Danh từ"],
 ["潮湿","cháoshī","ẩm ướt","Tính từ"],
 ["吵架","chǎo jià","cãi nhau","Động từ"],
 ["炒","chǎo","xào","Động từ"],
 ["车库","chēkù","nhà xe","Danh từ"],
 ["车厢","chēxiāng","toa xe","Danh từ"],
 ["彻底","chèdǐ","triệt để","Tính từ / Phó từ"],
 ["沉默","chénmò","im lặng","Tính từ"],
 ["趁","chèn","nhân lúc","Động từ"],
 ["称赞","chēngzàn","khen ngợi","Động từ"],
 ["称","chēng","gọi là, cân","Động từ"],
 ["成分","chéngfèn","thành phần","Danh từ"],
 ["成果","chéngguǒ","thành quả","Danh từ"],
 ["成就","chéngjiù","thành tựu","Danh từ"],
 ["成立","chénglì","thành lập","Động từ"],
 ["成语","chéngyǔ","thành ngữ","Danh từ"],
 ["成长","chéngzhǎng","trưởng thành","Động từ"],
 ["承担","chéngdān","gánh chịu","Động từ"],
 ["承认","chéngrèn","thừa nhận","Động từ"],
 ["承受","chéngshòu","chịu đựng","Động từ"],
 ["程度","chéngdù","mức độ","Danh từ"],
 ["程序","chéngxù","chương trình, thủ tục","Danh từ"],
 ["诚恳","chéngkěn","chân thành","Tính từ"],
 ["吃亏","chī kuī","chịu thiệt","Động từ"],
 ["迟早","chízǎo","sớm muộn","Phó từ"],
 ["持续","chíxù","kéo dài","Động từ / Phó từ"],
 ["尺子","chǐzi","thước kẻ","Danh từ"],
 ["充分","chōngfèn","đầy đủ","Tính từ / Phó từ"],
 ["充满","chōngmǎn","tràn đầy","Tính từ"],
 ["冲","chōng","xông","Động từ"],
 ["重复","chóngfù","lập lại","Phó từ"],
 ["宠物","chǒngwù","thú cưng","Danh từ"],
 ["抽屉","chōuti","ngăn kéo","Danh từ"],
 ["抽象","chōuxiàng","trừu tượng","Động từ"],
 ["丑","chǒu","xấu xí","Tính từ"],
 ["臭","chòu","hôi, thối","Tính từ"],
 ["出版","chūbǎn","xuất bản","Động từ"],
 ["出口","chūkǒu","xuất khẩu, lối ra","Động từ / Danh từ"],
 ["出色","chūsè","xuất sắc","Động từ"],
 ["出席","chūxí","tham dự","Động từ"],
 ["初级","chūjí","sơ cấp","Tính từ"],
 ["除非","chúfēi","trừ phi","Liên từ"],
 ["处理","chǔlǐ","xử lý","Động từ"],
 ["传播","chuánbō","truyền bá","Động từ / Danh từ"],
 ["传递","chuándì","truyền đạt","Động từ"],
 ["传染","chuánrǎn","lây nhiễm","Động từ / Danh từ"],
 ["传说","chuánshuō","truyền thuyết","Danh từ"],
 ["传统","chuántǒng","truyền thống","Danh từ"],
 ["闯","chuǎng","xông vào","Động từ"],
 ["创造","chuàngzào","sáng tạo","Động từ"],
 ["吹","chuī","thổi","Động từ"],
 ["词汇","cíhuì","từ vựng","Danh từ"],
 ["辞职","cí zhí","từ chức","Động từ"],
 ["此外","cǐwài","ngoài ra","Liên từ"],
 ["次要","cìyào","thứ yếu","Tính từ"],
 ["刺激","cìjī","kích thích","Động từ"],
 ["匆忙","cōngmáng","vội vàng","Hình dung từ"],
 ["从此","cóngcǐ","từ đó","Liên từ"],
 ["从而","cóng'ér","từ đó mà","Liên từ"],
 ["从前","cóngqián","ngày xưa","Danh từ chỉ thời gian"],
 ["从事","cóngshì","làm (nghề)","Động từ"],
 ["粗糙","cūcāo","thô ráp","Tính từ"],
 ["促进","cùjìn","thúc đẩy","Động từ"],
 ["促使","cùshǐ","thúc đẩy, khiến","Động từ"],
 ["醋","cù","giấm","Danh từ"],
 ["催","cuī","giục",""],
 ["存在","cúnzài","tồn tại","Động từ"],
 ["措施","cuòshī","biện pháp","Danh từ"],
 ["达到","dádào","đạt tới","Động từ"],
 ["答应","dāying","đồng ý","Động từ"],
 ["打工","dǎ gōng","làm thêm","Động từ"],
 ["打交道","dǎ jiāodao","giao thiệp","Động từ"],
 ["打听","dǎting","dò hỏi","Động từ"],
 ["大方","dàfang","hào phóng","Danh từ"],
 ["大厦","dàshà","tòa nhà lớn","Danh từ"],
 ["大象","dàxiàng","con voi","Danh từ"],
 ["大型","dàxíng","quy mô lớn","Tính từ"],
 ["呆","dāi","ngờ, ở","Động từ"],
 ["代","dài","đời, thế hệ","Lượng từ"],
 ["贷款","dàikuǎn","cho vay","Danh từ"],
 ["待遇","dàiyù","đãi ngộ","Danh từ"],
 ["单调","dāndiào","đơn điệu","Danh từ"],
 ["单独","dāndú","đơn độc","Phó từ"],
 ["单位","dānwèi","đơn vị","Danh từ"],
 ["单元","dānyuán","đơn nguyên","Danh từ"],
 ["担任","dānrèn","đảm nhiệm","Động từ"],
 ["耽误","dānwu","trì hoãn","Động từ"],
 ["胆小鬼","dǎnxiǎoguǐ","người nhát gan","Thành ngữ"],
 ["淡","dàn","nhạt","Tính từ"],
 ["当地","dāngdì","địa phương","Danh từ nơi chốn"],
 ["当中","dāngzhōng","ở giữa","Danh từ nơi chốn"],
 ["导致","dǎozhì","dẫn đến","Động từ"],
 ["岛","dǎo","đảo","Danh từ"],
 ["倒","dào","đổ, ngược lại","Động từ"],
 ["倒霉","dǎoméi","xui xẻo","Tính từ"],
 ["道德","dàodé","đạo đức","Danh từ riêng"],
 ["道理","dàolǐ","đạo lý","Danh từ"],
 ["登记","dēngjì","đăng ký","Động từ"],
 ["登山","dēng shān","leo núi","Danh từ (Địa danh)"],
 ["等待","děngdài","chờ đợi","Động từ"],
 ["等于","děngyú","bằng","Động từ"],
 ["敌人","dírén","kẻ thù","Danh từ"],
 ["的确","díquè","quả thực","Phó từ"],
 ["地道","dìdao","chính gốc","Danh từ"],
 ["地理","dìlǐ","địa lý","Danh từ"],
 ["地区","dìqū","khu vực","Danh từ"],
 ["地毯","dìtǎn","thảm","Danh từ"],
 ["地位","dìwèi","địa vị","Danh từ"],
 ["地震","dìzhèn","động đất","Danh từ"],
 ["递","dì","chuyển, đưa","Động từ"],
 ["点心","diǎnxin","điểm tâm","Động từ"],
 ["电池","diànchí","pin","Danh từ"],
 ["电台","diàntái","đài phát thanh","Danh từ"],
 ["调查","diàochá","điều tra","Động từ / Danh từ"],
 ["顶","dǐng","đỉnh","Động từ"],
 ["动画片","dònghuàpiàn","phim hoạt hình","Danh từ"],
 ["冻","dòng","đóng băng","Động từ"],
 ["洞","dòng","cái lỗ, hang","Danh từ"],
 ["豆腐","dòufu","đậu phụ","Danh từ"],
 ["独立","dúlì","độc lập","Động từ"],
 ["独特","dútè","độc đáo","Tính từ"],
 ["度过","dùguò","trải qua","Động từ"],
 ["短暂","duǎnzàn","ngắn ngủi","Tính từ"],
 ["断","duàn","đứt, gãy","Động từ"],
 ["堆","duī","đống","Động từ"],
 ["对比","duìbǐ","so sánh","Động từ"],
 ["对待","duìdài","đối đãi","Động từ"],
 ["对方","duìfāng","đối phương","Danh từ"],
 ["对手","duìshǒu","đối thủ","Động từ"],
 ["对象","duìxiàng","đối tượng","Danh từ"],
 ["兑换","duìhuàn","đổi (tiền)","Động từ"],
 ["吨","dūn","tấn","Số từ"],
 ["蹲","dūn","ngồi xổm","Động từ"],
 ["多亏","duōkuī","nhờ","Phó từ"],
 ["多余","duōyú","thừa","Số từ"],
 ["朵","duǒ","(lượng từ) bông (hoa)","Số từ"],
 ["躲藏","duǒcáng","ẩn nấp","Động từ"],
 ["恶劣","èliè","ác liệt, tồi tệ","Tính từ"],
 ["耳环","ěrhuán","hoa tai","Danh từ"],
 ["发表","fābiǎo","phát biểu","Động từ"],
 ["发愁","fā chóu","lo lắng","Động từ"],
 ["发达","fādá","phát triển","Động từ"],
 ["发抖","fā dǒu","run rẩy","Động từ"],
 ["发挥","fāhuī","phát huy","Động từ"],
 ["发明","fāmíng","phát minh","Động từ"],
 ["发票","fāpiào","hóa đơn","Danh từ"],
 ["发言","fā yán","phát biểu","Động từ"],
 ["罚款","fá kuǎn","phạt tiền","Danh từ"],
 ["法院","fǎyuàn","tòa án","Danh từ"],
 ["繁荣","fánróng","phồn vinh","Tính từ"],
 ["反复","fǎnfù","lặp đi lặp lại","Động từ"],
 ["反而","fǎn'ér","ngược lại","Liên từ"],
 ["反应","fǎnyìng","phản ứng","Động từ / Danh từ"],
 ["反正","fǎnzhèng","dù sao","Phó từ"],
 ["范围","fànwéi","phạm vi","Danh từ"],
 ["方案","fāng'àn","phương án","Danh từ"],
 ["方式","fāngshì","phương thức","Danh từ"],
 ["妨碍","fáng'ài","cản trở","Động từ"],
 ["房屋","fángwū","nhà ở","Danh từ"],
 ["仿佛","fǎngfú","dường như","Phó từ"],
 ["纺织","fǎngzhī","dệt may","Danh từ"],
 ["非","fēi","phi, không",""],
 ["肥","féi","béo, mập","Danh từ"],
 ["废话","fèihuà","nói nhảm","Danh từ"],
 ["费用","fèiyòng","chi phí","Danh từ"],
 ["分别","fēnbié","chia tay, phân biệt","Phó từ"],
 ["分布","fēnbù","phân bố","Động từ"],
 ["分配","fēnpèi","phân phối","Động từ / Danh từ"],
 ["分手","fēn shǒu","chia tay","Động từ"],
 ["分析","fēnxī","phân tích","Động từ / Danh từ"],
 ["纷纷","fēnfēn","lần lượt","Phó từ"],
 ["奋斗","fèndòu","phấn đấu","Động từ"],
 ["风格","fēnggé","phong cách","Danh từ"],
 ["风景","fēngjǐng","phong cảnh","Danh từ"],
 ["风俗","fēngsú","phong tục","Danh từ"],
 ["风险","fēngxiǎn","rủi ro","Danh từ"],
 ["疯狂","fēngkuáng","điên cuồng","Tính từ"],
 ["讽刺","fěngcì","châm biếm","Động từ"],
 ["否定","fǒudìng","phủ định","Động từ"],
 ["扶","fú","đỡ, nâng","Động từ"],
 ["幅","fú","(lượng từ) bức (tranh)","Danh từ"],
 ["服装","fúzhuāng","trang phục","Động từ / Danh từ"],
 ["辅导","fǔdǎo","hướng dẫn","Động từ / Danh từ"],
 ["付出","fùchū","bỏ ra","Động từ"],
 ["妇女","fùnǚ","phụ nữ","Danh từ"],
 ["复制","fùzhì","sao chép","Động từ"],
 ["改革","gǎigé","cải cách","Động từ / Danh từ"],
 ["改进","gǎijìn","cải tiến","Động từ"],
 ["改善","gǎishàn","cải thiện","Động từ"],
 ["改正","gǎizhèng","sửa chữa","Động từ"],
 ["盖","gài","đậy, xây","Động từ"],
 ["概括","gàikuò","khái quát","Động từ"],
 ["概念","gàiniàn","khái niệm","Danh từ"],
 ["干活儿","gàn huór","làm việc","Danh từ"],
 ["干燥","gānzào","khô","Tính từ"],
 ["感激","gǎnjī","cảm kích","Động từ"],
 ["感受","gǎnshòu","cảm nhận","Động từ"],
 ["感想","gǎnxiǎng","cảm tưởng","Động từ"],
 ["赶紧","gǎnjǐn","nhanh lên","Phó từ"],
 ["赶快","gǎnkuài","nhanh lên","Phó từ"],
 ["干脆","gāncuì","dứt khoát","Phó từ"],
 ["钢铁","gāngtiě","thép","Danh từ"],
 ["高档","gāodàng","cao cấp","Tính từ"],
 ["高级","gāojí","cao cấp","Tính từ"],
 ["搞","gǎo","làm","Động từ"],
 ["告别","gàobié","chia tay","Động từ"],
 ["格外","géwài","đặc biệt","Phó từ"],
 ["隔壁","gébì","hàng xóm, bên cạnh","Danh từ nơi chốn"],
 ["个别","gèbié","cá biệt","Danh từ"],
 ["个人","gèrén","cá nhân","Danh từ"],
 ["个性","gèxìng","cá tính","Danh từ"],
 ["各自","gèzì","riêng mỗi người","Đại từ"],
 ["根","gēn","rễ, gốc","Giới từ"],
 ["根本","gēnběn","cơ bản, hoàn toàn","Tính từ"],
 ["工厂","gōngchǎng","nhà máy","Danh từ"],
 ["工程","gōngchéng","công trình","Danh từ"],
 ["工业","gōngyè","công nghiệp","Danh từ"],
 ["公布","gōngbù","công bố","Động từ"],
 ["公开","gōngkāi","công khai","Tính từ / Phó từ"],
 ["公民","gōngmín","công dân","Danh từ"],
 ["公平","gōngpíng","công bằng","Danh từ"],
 ["公寓","gōngyù","căn hộ","Danh từ"],
 ["公主","gōngzhǔ","công chúa","Danh từ"],
 ["功能","gōngnéng","chức năng","Danh từ"],
 ["贡献","gòngxiàn","cống hiến","Danh từ"],
 ["沟通","gōutōng","giao tiếp","Động từ"],
 ["构成","gòuchéng","cấu thành","Động từ"],
 ["姑姑","gūgu","cô (chị/em gái của bố)","Danh từ"],
 ["姑娘","gūniang","cô gái","Danh từ"],
 ["古代","gǔdài","thời cổ","Danh từ chỉ thời gian"],
 ["古典","gǔdiǎn","cổ điển","Danh từ (Địa danh)"],
 ["股票","gǔpiào","cổ phiếu","Danh từ"],
 ["骨头","gǔtou","xương","Danh từ"],
 ["鼓舞","gǔwǔ","khích lệ","Động từ"],
 ["固定","gùdìng","cố định","Tính từ"],
 ["挂号","guà hào","đăng ký (bệnh viện)","Danh từ"],
 ["乖","guāi","ngoan","Tính từ"],
 ["拐弯","guǎi wān","rẽ, quẹo","Danh từ"],
 ["怪不得","guàibude","thảo nào","Từ láy / Quán dụng ngữ"],
 ["官","guān","quan chức","Danh từ"],
 ["观察","guānchá","quan sát","Động từ"],
 ["观点","guāndiǎn","quan điểm","Danh từ"],
 ["观念","guānniàn","quan niệm","Danh từ"],
 ["观众","guānzhòng","khán giả","Danh từ"],
 ["管","guǎn","quản, ống","Động từ / Danh từ"],
 ["冠军","guànjūn","quán quân, vô địch","Danh từ"],
 ["光滑","guānghuá","trơn nhẵn","Tính từ"],
 ["光临","guānglín","quang lâm","Động từ"],
 ["光明","guāngmíng","sáng sủa","Danh từ"],
 ["光盘","guāngpán","đĩa CD","Danh từ"],
 ["广场","guǎngchǎng","quảng trường","Danh từ"],
 ["广大","guǎngdà","rộng lớn","Tính từ"],
 ["广泛","guǎngfàn","rộng rãi","Tính từ"],
 ["归纳","guīnà","quy nạp","Động từ"],
 ["规矩","guījǔ","quy tắc","Danh từ"],
 ["规模","guīmó","quy mô","Danh từ"],
 ["规律","guīlǜ","quy luật","Danh từ"],
 ["规则","guīzé","quy tắc","Danh từ"],
 ["柜台","guìtái","quầy","Danh từ"],
 ["国庆节","guóqìngjié","Quốc khánh","Danh từ chỉ thời gian"],
 ["果实","guǒshí","quả, thành tựu","Phó từ"],
 ["过分","guòfèn","quá đáng","Danh từ"],
 ["过敏","guòmǐn","dị ứng","Danh từ riêng"],
 ["过期","guòqī","hết hạn","Danh từ chỉ thời gian"],
 ["哈","hā","ha (cười)","Danh từ riêng"],
 ["海关","hǎiguān","hải quan","Danh từ (Địa danh)"],
 ["海鲜","hǎixiān","hải sản","Danh từ (Địa danh)"],
 ["喊","hǎn","la, hét","Động từ"],
 ["行业","hángyè","ngành nghề","Danh từ"],
 ["豪华","háohuá","hào hoa, sang trọng","Tính từ"],
 ["好客","hàokè","hiếu khách","Danh từ"],
 ["好奇","hàoqí","tò mò","Tính từ"],
 ["合法","héfǎ","hợp pháp","Danh từ"],
 ["合理","hélǐ","hợp lý","Động từ / Danh từ"],
 ["合同","hétong","hợp đồng","Tính từ"],
 ["合影","hé yǐng","chụp ảnh chung","Danh từ"],
 ["合作","hézuò","hợp tác","Động từ / Danh từ"],
 ["何必","hébì","cần gì phải","Phó từ"],
 ["何况","hékuàng","huống chi","Liên từ"],
 ["核心","héxīn","hạt nhân, cốt lõi","Danh từ"],
 ["恨","hèn","ghét, hận","Động từ"],
 ["猴子","hóuzi","con khỉ","Danh từ"],
 ["后背","hòubèi","lưng","Danh từ"],
 ["后果","hòuguǒ","hậu quả","Danh từ"],
 ["呼吸","hūxī","hô hấp","Động từ"],
 ["忽略","hūlüè","bỏ qua","Phó từ"],
 ["忽然","hūrán","bỗng nhiên","Phó từ"],
 ["胡说","hú shuō","nói bậy",""],
 ["胡同","hútòng","ngõ, hẻm","Danh từ riêng"],
 ["壶","hú","ấm, bình","Lượng từ"],
 ["蝴蝶","húdié","con bướm","Danh từ"],
 ["糊涂","hútu","hồ đồ","Tính từ"],
 ["华裔","huáyì","người gốc Hoa","Danh từ riêng"],
 ["划算","huásuàn","đáng, lời","Động từ"],
 ["化学","huàxué","hóa học","Danh từ"],
 ["话题","huàtí","chủ đề","Danh từ"],
 ["怀念","huáiniàn","nhớ nhung","Động từ"],
 ["怀孕","huái yùn","mang thai","Động từ"],
 ["缓解","huǎnjiě","hòa hoãn","Động từ"],
 ["幻想","huànxiǎng","ảo tưởng","Danh từ"],
 ["慌张","huāngzhāng","hoảng hốt","Tính từ"],
 ["黄金","huángjīn","vàng","Danh từ"],
 ["灰","huī","tro, xám","Danh từ"],
 ["灰尘","huīchén","bụi","Danh từ"],
 ["灰心","huī xīn","nản lòng","Danh từ"],
 ["挥","huī","vẫy","Động từ"],
 ["恢复","huīfù","hồi phục","Động từ"],
 ["汇率","huìlǜ","tỷ giá","Danh từ"],
 ["婚礼","hūnlǐ","lễ cưới","Danh từ"],
 ["婚姻","hūnyīn","hôn nhân","Danh từ"],
 ["活跃","huóyuè","hoạt bát","Động từ / Danh từ"],
 ["伙伴","huǒbàn","bạn đồng hành","Danh từ"],
 ["火柴","huǒchái","diêm","Danh từ"],
 ["或许","huòxǔ","có lẽ","Phó từ"]
];
