// HSK 6 Part 1 - 1250 từ thành thạo (phần 1)
const HSK6_1 = [
 ["哀悼","āidào","ai điệu, thương tiếc","Động từ"],
 ["爱不释手","àibùshìshǒu","yêu không rời tay","Thành ngữ"],
 ["暧昧","àimèi","mập mờ, lấp lửng","Tính từ"],
 ["安宁","ānníng","an ninh, yên ổn","Danh từ (Địa danh)"],
 ["安慰","ānwèi","an ủi","Động từ"],
 ["暗示","ànshì","ám chỉ","Động từ"],
 ["案件","ànjiàn","vụ án","Danh từ"],
 ["案例","ànlì","án lệ, ví dụ","Danh từ"],
 ["昂贵","ángguì","đắt đỏ","Tính từ"],
 ["凹凸","āotū","lồi lõm","Danh từ"],
 ["熬","áo","nấu (lâu), chịu đựng","Động từ"],
 ["奥秘","àomì","bí ẩn","Danh từ riêng"],
 ["巴不得","bābude","mong muốn","Từ láy / Quán dụng ngữ"],
 ["巴结","bājie","nịnh bợ","Danh từ riêng"],
 ["拔苗助长","bá miáo zhù zhǎng","nhổ mạ giúp lúa mọc","Thành ngữ"],
 ["霸道","bàdào","ngang ngược","Danh từ"],
 ["罢工","bà gōng","đình công","Động từ"],
 ["摆脱","bǎituō","thoát khỏi","Động từ"],
 ["拜访","bàifǎng","bái phỏng, thăm","Động từ"],
 ["拜托","bàituō","nhờ cậy",""],
 ["颁布","bānbù","ban bố","Động từ"],
 ["颁发","bānfā","ban phát","Động từ"],
 ["版本","bǎnběn","phiên bản","Danh từ"],
 ["半途而废","bàntú'érfèi","nửa đường bỏ dở","Thành ngữ"],
 ["扮演","bànyǎn","đóng vai","Động từ"],
 ["帮忙","bāng máng","giúp đỡ","Động từ"],
 ["绑架","bǎngjià","bắt cóc","Động từ"],
 ["榜样","bǎngyàng","tấm gương","Danh từ"],
 ["磅","bàng","pound","Số từ"],
 ["包庇","bāobì","bao che","Động từ"],
 ["包袱","bāofu","gánh nặng","Danh từ"],
 ["包围","bāowéi","bao vây","Động từ"],
 ["包装","bāozhuāng","bao bì, đóng gói","Động từ"],
 ["饱和","bǎohé","bão hòa","Tính từ"],
 ["保管","bǎoguǎn","bảo quản","Động từ"],
 ["保留","bǎoliú","giữ lại","Động từ"],
 ["保密","bǎo mì","giữ bí mật","Danh từ"],
 ["保姆","bǎomǔ","bảo mẫu",""],
 ["保守","bǎoshǒu","bảo thủ","Động từ"],
 ["保卫","bǎowèi","bảo vệ","Động từ"],
 ["保养","bǎoyǎng","bảo dưỡng","Động từ"],
 ["保障","bǎozhàng","bảo đảm","Động từ"],
 ["报仇","bào chóu","trả thù","Động từ"],
 ["报酬","bàochou","thù lao","Danh từ"],
 ["报复","bàofù","báo thù","Động từ"],
 ["报警","bào jǐng","báo cảnh sát","Danh từ"],
 ["报销","bàoxiāo","thanh toán (hóa đơn)","Động từ"],
 ["抱负","bàofù","hoài bão","Động từ"],
 ["抱怨","bàoyuàn","oán trách","Động từ"],
 ["暴力","bàolì","bạo lực","Danh từ"],
 ["暴露","bàolù","phơi bày","Động từ"],
 ["爆发","bàofā","bùng nổ","Động từ"],
 ["爆炸","bàozhà","nổ","Động từ"],
 ["卑鄙","bēibǐ","hèn hạ","Tính từ"],
 ["悲哀","bēi'āi","bi ai","Tính từ"],
 ["悲惨","bēicǎn","bi thảm","Tính từ"],
 ["北极","Běijí","Bắc Cực","Danh từ (Địa danh)"],
 ["背叛","bèipàn","phản bội","Động từ"],
 ["背诵","bèisòng","đọc thuộc lòng","Động từ"],
 ["备份","bèifèn","sao lưu","Danh từ"],
 ["备忘录","bèiwànglù","bản ghi nhớ","Danh từ"],
 ["奔波","bēnbō","bôn ba","Động từ"],
 ["奔驰","bēnchí","lao vút","Động từ"],
 ["本能","běnnéng","bản năng","Danh từ"],
 ["本人","běnrén","bản thân","Đại từ"],
 ["本事","běnshi","bản lĩnh","Đại từ"],
 ["本着","běnzhe","dựa trên","Giới từ"],
 ["笨拙","bènzhuō","vụng về","Tính từ"],
 ["蹦","bèng","nhảy, bật","Động từ"],
 ["逼迫","bīpò","bức ép","Động từ"],
 ["鼻涕","bítì","nước mũi","Danh từ"],
 ["比方","bǐfang","ví dụ","Danh từ"],
 ["比喻","bǐyù","ẩn dụ","Danh từ"],
 ["比重","bǐzhòng","tỷ trọng","Danh từ"],
 ["彼岸","bǐ'àn","bờ bên kia",""],
 ["鄙视","bǐshì","coi thường","Động từ"],
 ["必定","bìdìng","nhất định","Phó từ"],
 ["闭幕式","bìmùshì","lễ bế mạc","Danh từ"],
 ["弊病","bìbìng","tệ nạn","Danh từ"],
 ["碧绿","bìlǜ","xanh biếc","Hình dung từ"],
 ["边缘","biānyuán","rìa, biên giới","Danh từ"],
 ["编织","biānzhī","dệt","Danh từ"],
 ["鞭策","biāncè","thúc đẩy","Danh từ"],
 ["贬低","biǎndī","hạ thấp","Động từ"],
 ["贬义","biǎnyì","nghĩa xấu","Động từ"],
 ["变故","biàngù","biến cố","Danh từ"],
 ["变迁","biànqiān","biến đổi","Động từ / Danh từ"],
 ["变质","biànzhì","biến chất","Danh từ"],
 ["便利","biànlì","tiện lợi","Tính từ"],
 ["便条","biàntiáo","giấy nhắn","Số từ"],
 ["辨别","biànbié","phân biệt","Động từ"],
 ["辩护","biànhù","biện hộ","Động từ"],
 ["辩解","biànjiě","biện giải","Động từ"],
 ["辩证","biànzhèng","biện chứng","Động từ"],
 ["标本","biāoběn","mẫu vật","Danh từ"],
 ["标记","biāojì","đánh dấu","Danh từ"],
 ["标题","biāotí","tiêu đề","Danh từ"],
 ["憋","biē","nín nhịn",""],
 ["别墅","biéshù","biệt thự","Danh từ"],
 ["别致","biézhì","độc đáo","Động từ"],
 ["濒临","bīnlín","ở bên bờ","Động từ"],
 ["冰雹","bīngbáo","mưa đá","Danh từ"],
 ["兵","bīng","lính","Danh từ"],
 ["并非","bìngfēi","không phải","Liên từ"],
 ["并列","bìngliè","song song","Động từ"],
 ["拨","bō","bấm (số), gạt","Động từ"],
 ["波浪","bōlàng","sóng","Danh từ (Khác)"],
 ["剥削","bōxuē","bóc lột","Động từ"],
 ["驳斥","bóchì","bác bỏ","Động từ"],
 ["博览会","bólǎnhuì","hội chợ triển lãm","Danh từ"],
 ["博物馆","bówùguǎn","bảo tàng","Danh từ"],
 ["薄弱","bóruò","yếu kém","Tính từ"],
 ["补偿","bǔcháng","bù đắp","Động từ / Danh từ"],
 ["补救","bǔjiù","bù cứu","Động từ"],
 ["补贴","bǔtiē","trợ cấp","Danh từ"],
 ["不顾","bùgù","bất chấp","Động từ"],
 ["不堪","bùkān","không chịu nổi","Động từ"],
 ["不免","bùmiǎn","không tránh khỏi","Liên từ"],
 ["不禁","bùjīn","không kìm được","Phó từ"],
 ["不像话","bú xiànghuà","quá quắt","Từ láy / Quán dụng ngữ"],
 ["不由得","bùyóude","bất giác","Phó từ"],
 ["不择手段","bùzé shǒuduàn","bất chấp thủ đoạn","Thành ngữ"],
 ["不止","bùzhǐ","không chỉ","Động từ"],
 ["布告","bùgào","thông báo","Danh từ"],
 ["布局","bùjú","bố cục","Danh từ"],
 ["布置","bùzhì","bố trí","Danh từ"],
 ["步伐","bùfá","bước đi","Danh từ"],
 ["财富","cáifù","tài phú","Danh từ"],
 ["财务","cáiwù","tài vụ","Danh từ"],
 ["财政","cáizhèng","tài chính","Danh từ"],
 ["裁缝","cáiféng","thợ may","Danh từ"],
 ["裁判","cáipàn","trọng tài","Động từ / Danh từ"],
 ["裁员","cái yuán","sa thải","Danh từ"],
 ["采购","cǎigòu","mua sắm","Động từ"],
 ["采集","cǎijí","thu thập","Động từ"],
 ["采纳","cǎinà","chấp nhận","Động từ"],
 ["彩票","cǎipiào","vé số","Danh từ"],
 ["参谋","cānmóu","tham mưu","Động từ"],
 ["参照","cānzhào","tham chiếu","Động từ"],
 ["残疾","cánjí","tàn tật","Danh từ"],
 ["残酷","cánkù","tàn khốc","Tính từ"],
 ["残留","cánliú","tàn dư","Động từ"],
 ["残忍","cánrěn","tàn nhẫn","Tính từ"],
 ["灿烂","cànlàn","rực rỡ","Tính từ"],
 ["仓促","cāngcù","vội vàng","Tính từ / Phó từ"],
 ["仓库","cāngkù","nhà kho","Danh từ"],
 ["苍白","cāngbái","trắng bệch","Hình dung từ"],
 ["操纵","cāozòng","thao túng","Động từ"],
 ["操作","cāozuò","vận hành","Động từ"],
 ["草案","cǎo'àn","dự thảo","Danh từ"],
 ["草率","cǎoshuài","cẩu thả","Danh từ"],
 ["侧面","cèmiàn","bên cạnh","Danh từ phương hướng"],
 ["策划","cèhuà","hoạch định","Danh từ"],
 ["策略","cèlüè","chiến lược","Danh từ"],
 ["层次","céngcì","tầng lớp","Số từ"],
 ["叉","chā","nĩa","Danh từ"],
 ["差额","chā'é","chênh lệch","Danh từ"],
 ["差异","chāyì","sự khác biệt","Danh từ"],
 ["搀","chān","dìu",""],
 ["馋","chán","thèm ăn","Tính từ"],
 ["缠绕","chánrào","quấn quanh","Động từ"],
 ["产业","chǎnyè","ngành","Danh từ"],
 ["阐述","chǎnshù","trình bày","Động từ"],
 ["颤抖","chàndǒu","run rẩy","Động từ"],
 ["昌盛","chāngshèng","hưng thịnh","Danh từ (Khác)"],
 ["猖狂","chāngkuáng","điên cuồng","Tính từ"],
 ["常务","chángwù","thường vụ","Danh từ"],
 ["偿还","chánghuán","trả lại","Động từ"],
 ["敞开","chǎngkāi","mở rộng","Động từ"],
 ["畅销","chàngxiāo","bán chạy","Động từ"],
 ["倡导","chàngdǎo","chủ trương","Động từ"],
 ["倡议","chàngyì","đề xướng","Danh từ"],
 ["超级","chāojí","siêu cấp","Tính từ"],
 ["超越","chāoyuè","vượt qua","Động từ"],
 ["巢穴","cháoxué","ổ, hang","Danh từ"],
 ["嘲笑","cháoxiào","chế nhạo","Động từ"],
 ["潮流","cháoliú","xu hướng","Danh từ"],
 ["撤退","chètuì","rút lui","Động từ"],
 ["撤销","chèxiāo","thu hồi","Động từ"],
 ["沉淀","chéndiàn","lắng đọng","Động từ"],
 ["沉闷","chénmèn","ngột ngạt","Tính từ"],
 ["沉思","chénsī","suy tư","Tính từ"],
 ["沉重","chénzhòng","nặng nề","Tính từ"],
 ["沉着","chénzhuó","điềm tĩnh","Động từ"],
 ["陈旧","chénjiù","cũ kỹ","Danh từ riêng"],
 ["陈列","chénliè","trưng bày","Danh từ riêng"],
 ["陈述","chénshù","trình bày","Danh từ riêng"],
 ["称心如意","chènxīnrúyì","vừa ý","Thành ngữ"],
 ["成本","chéngběn","giá thành","Danh từ"],
 ["成交","chéngjiāo","giao dịch thành","Động từ"],
 ["成天","chéngtiān","cả ngày","Danh từ chỉ thời gian"],
 ["成效","chéngxiào","hiệu quả","Tính từ"],
 ["成员","chéngyuán","thành viên","Danh từ"],
 ["呈现","chéngxiàn","hiện ra","Động từ"],
 ["诚挚","chéngzhì","chân thành","Tính từ"],
 ["承办","chéngbàn","đảm trách","Động từ"],
 ["承包","chéngbāo","bao thầu","Động từ"],
 ["承诺","chéngnuò","cam kết","Động từ"],
 ["城堡","chéngbǎo","lâu đài","Danh từ (Địa danh)"],
 ["惩罚","chéngfá","trừng phạt","Động từ / Danh từ"],
 ["澄清","chéngqīng","làm rõ","Động từ"],
 ["橙","chéng","cam (màu/quả)","Danh từ"],
 ["吃力","chīlì","vất vả","Danh từ"],
 ["池塘","chítáng","ao","Danh từ (Địa danh)"],
 ["迟缓","chíhuǎn","chậm chạp","Phó từ"],
 ["迟疑","chíyí","do dự","Phó từ"],
 ["持久","chíjiǔ","lâu dài","Tính từ"],
 ["赤道","chìdào","xích đạo","Danh từ"],
 ["赤字","chìzì","thâm hụt","Danh từ"],
 ["冲刺","chōngcì","nước rút","Động từ / Danh từ"],
 ["冲动","chōngdòng","bốc đồng","Động từ / Danh từ"],
 ["冲击","chōngjī","xung kích","Động từ / Danh từ"],
 ["冲突","chōngtū","xung đột","Động từ / Danh từ"],
 ["充当","chōngdāng","đảm nhiệm","Tính từ"],
 ["充沛","chōngpèi","dồi dào","Tính từ"],
 ["充实","chōngshí","sung túc","Tính từ / Phó từ"],
 ["充足","chōngzú","dồi dào","Tính từ"],
 ["崇拜","chóngbài","sùng bái",""],
 ["崇高","chónggāo","cao cả",""],
 ["崇敬","chóngjìng","kính trọng","Động từ"],
 ["筹备","chóubèi","chuẩn bị","Động từ"],
 ["稠密","chóumì","dày đặc","Tính từ"],
 ["丑恶","chǒu'è","xấu xa","Tính từ"],
 ["丑闻","chǒuwén","vụ bê bối","Danh từ"],
 ["出路","chūlù","lối thoát","Động từ"],
 ["出卖","chūmài","bán đứng","Động từ"],
 ["出难题","chū nántí","gây khó","Danh từ"],
 ["出身","chūshēn","xuất thân","Động từ"],
 ["出息","chūxi","triển vọng","Động từ"],
 ["初步","chūbù","bước đầu","Phó từ"],
 ["处分","chǔfèn","kỷ luật","Danh từ"],
 ["处境","chǔjìng","hoàn cảnh","Danh từ"],
 ["处置","chǔzhì","xử trí","Động từ"],
 ["储存","chǔcún","tích trữ","Danh từ"],
 ["储备","chǔbèi","dự trữ","Động từ / Danh từ"],
 ["触犯","chùfàn","phạm vào","Động từ"],
 ["川流不息","chuānliúbùxī","dòng người không ngớt","Thành ngữ"],
 ["穿越","chuānyuè","xuyên qua","Động từ"],
 ["传达","chuándá","truyền đạt","Động từ"],
 ["传单","chuándān","tờ rơi","Danh từ"],
 ["船舶","chuánbó","tàu thuyền","Danh từ"],
 ["喘气","chuǎn qì","thở hổn hển","Động từ"],
 ["串","chuàn","chuỗi, xiên","Động từ"],
 ["创立","chuànglì","sáng lập","Động từ"],
 ["创新","chuàngxīn","đổi mới","Động từ"],
 ["创业","chuàng yè","khởi nghiệp","Danh từ"],
 ["创作","chuàngzuò","sáng tác","Động từ / Danh từ"],
 ["吹捧","chuīpěng","tâng bốc","Động từ"],
 ["吹嘘","chuīxū","khoác loác","Động từ"],
 ["垂直","chuízhí","thẳng đứng","Động từ"],
 ["锤","chuí","búa","Danh từ"],
 ["纯粹","chúncuì","thuần túy","Tính từ"],
 ["纯洁","chúnjié","trong sạch","Tính từ"],
 ["磁带","cídài","băng cassette","Danh từ"],
 ["雌雄","cíxióng","cái đực","Danh từ"],
 ["辞退","cítuì","sa thải","Động từ"],
 ["慈善","císhàn","từ thiện","Danh từ riêng"],
 ["慈祥","cíxiáng","hiền từ","Danh từ riêng"],
 ["此致","cǐzhì","kính thư","Liên từ"],
 ["刺","cì","gai, đâm","Động từ"],
 ["伺候","cìhou","phục vụ","Động từ"],
 ["聪颖","cōngyǐng","thông minh lanh lợi","Tính từ"],
 ["从容","cóngróng","thong thả","Động từ"],
 ["凑合","còuhe","tạm được","Động từ"],
 ["粗鲁","cūlǔ","thô lỗ","Tính từ"],
 ["窜","cuàn","trốn chạy",""],
 ["摧毁","cuīhuǐ","phá hủy","Động từ"],
 ["脆弱","cuìruò","mong manh","Tính từ"],
 ["搓","cuō","xoa, vò","Động từ"],
 ["挫折","cuòzhé","thất bại","Danh từ"],
 ["搭档","dādàng","bạn đồng hành","Động từ"],
 ["搭配","dāpèi","phối hợp","Động từ"],
 ["达成","dáchéng","đạt được","Động từ"],
 ["答辩","dábiàn","bảo vệ (luận văn)","Động từ"],
 ["答复","dáfù","đáp lại","Động từ"],
 ["打包","dǎ bāo","đóng gói","Động từ"],
 ["打官司","dǎ guānsi","kiện tụng","Từ láy / Quán dụng ngữ"],
 ["打击","dǎjī","đánh, đả kích","Động từ"],
 ["打架","dǎ jià","đánh nhau","Động từ"],
 ["打猎","dǎ liè","đi săn","Động từ"],
 ["打仗","dǎ zhàng","đánh trận","Động từ"],
 ["大不了","dàbuliǎo","cùng lắm","Từ láy / Quán dụng ngữ"],
 ["大臣","dàchén","đại thần","Danh từ"],
 ["大肆","dàsì","tung hoành","Phó từ"],
 ["大体","dàtǐ","đại thể","Danh từ"],
 ["大意","dàyì","đại ý, sơ suất","Phó từ"],
 ["代价","dàijià","cái giá","Danh từ"],
 ["代理","dàilǐ","đại diện","Danh từ"],
 ["带领","dàilǐng","dẫn dắt","Động từ"],
 ["怠慢","dàimàn","thờ ơ","Động từ"],
 ["逮捕","dàibǔ","bắt giữ","Động từ"],
 ["担保","dānbǎo","bảo đảm","Động từ"],
 ["耽搁","dānge","trì hoãn","Động từ"],
 ["胆怯","dǎnqiè","nhát gan","Tính từ"],
 ["诞辰","dànchén","kỷ niệm sinh nhật","Danh từ"],
 ["诞生","dànshēng","ra đời","Động từ"],
 ["弹性","tánxìng","đàn hồi","Danh từ"],
 ["淡季","dànjì","mùa thấp điểm","Danh từ"],
 ["淡水","dànshuǐ","nước ngọt","Danh từ"],
 ["蛋白质","dànbáizhì","protein","Danh từ"],
 ["当初","dāngchū","ban đầu","Danh từ chỉ thời gian"],
 ["当面","dāngmiàn","trước mặt","Danh từ phương hướng"],
 ["当前","dāngqián","hiện tại","Danh từ chỉ thời gian"],
 ["当事人","dāngshìrén","đương sự","Danh từ"],
 ["当务之急","dāngwùzhījí","việc cấp bách","Thành ngữ"],
 ["当选","dāngxuǎn","trúng cử","Động từ"],
 ["档案","dàng'àn","hồ sơ","Danh từ"],
 ["档次","dàngcì","cấp bậc","Danh từ"],
 ["导弹","dǎodàn","tên lửa","Danh từ"],
 ["导航","dǎoháng","dẫn đường","Động từ"],
 ["导向","dǎoxiàng","hướng dẫn","Danh từ"],
 ["导演","dǎoyǎn","đạo diễn","Động từ"],
 ["倒闭","dǎobì","phá sản","Động từ"],
 ["倒塌","dǎotā","sụp đổ","Động từ"],
 ["盗窃","dàoqiè","trộm cắp","Động từ"],
 ["得力","délì","đắc lực","Động từ"],
 ["得罪","dézuì","mắc tội","Động từ"],
 ["等级","děngjí","đẳng cấp","Tính từ"],
 ["登陆","dēnglù","đổ bộ, đăng nhập","Động từ"],
 ["登录","dēnglù","đăng nhập","Động từ"],
 ["提防","dīfáng","đề phòng","Động từ"],
 ["低估","dīgū","đánh giá thấp","Động từ"],
 ["堤坝","dībà","đê đập","Danh từ"],
 ["敌视","díshì","thù địch","Danh từ"],
 ["抵达","dǐdá","đến","Động từ"],
 ["抵抗","dǐkàng","chống cự","Động từ / Danh từ"],
 ["抵制","dǐzhì","tẩy chay","Động từ"],
 ["地步","dìbù","tình thế","Danh từ"],
 ["地道","dìdào","đường hầm","Danh từ"],
 ["地势","dìshì","địa thế","Danh từ"],
 ["地形","dìxíng","địa hình","Danh từ"],
 ["地质","dìzhì","địa chất","Danh từ"],
 ["递增","dìzēng","tăng dần","Động từ"],
 ["颠倒","diāndǎo","đảo lộn","Động từ"],
 ["典礼","diǎnlǐ","lễ điển","Danh từ"],
 ["典型","diǎnxíng","điển hình","Danh từ"],
 ["奠定","diàndìng","đặt nền móng","Động từ"],
 ["惦记","diànjì","nhớ nhung","Động từ"],
 ["电源","diànyuán","nguồn điện","Danh từ"],
 ["殿堂","diàntáng","điện đường","Danh từ"],
 ["雕刻","diāokè","điêu khắc","Danh từ"],
 ["雕塑","diāosù","điêu khắc (tượng)","Danh từ"],
 ["吊","diào","treo",""],
 ["调动","diàodòng","điều động","Động từ / Danh từ"],
 ["调解","tiáojiě","hòa giải","Động từ"],
 ["跌","diē","ngã, giảm","Động từ"],
 ["叮嘱","dīngzhǔ","dặn dò","Động từ"],
 ["顶端","dǐngduān","đỉnh","Danh từ phương hướng"],
 ["定期","dìngqī","định kỳ","Động từ / Danh từ"],
 ["定义","dìngyì","định nghĩa","Danh từ"],
 ["丢人","diū rén","mất mặt","Động từ"],
 ["丢三落四","diūsānlàsì","hay quên","Thành ngữ"],
 ["东道主","dōngdàozhǔ","chủ nhà","Danh từ riêng"],
 ["东张西望","dōngzhāngxīwàng","nhìn quanh","Danh từ riêng"],
 ["动荡","dòngdàng","biến động","Động từ"],
 ["动机","dòngjī","động cơ","Danh từ"],
 ["动力","dònglì","động lực","Danh từ"],
 ["动脉","dòngmài","động mạch","Danh từ"],
 ["动态","dòngtài","động thái","Danh từ"],
 ["动员","dòngyuán","động viên","Danh từ"],
 ["栋","dòng","(lượng từ) tòa nhà",""],
 ["洞穴","dòngxué","hang động","Danh từ"],
 ["督促","dūcù","đôn đốc","Động từ"],
 ["独裁","dúcái","độc tài","Động từ"],
 ["独到","dúdào","độc đáo","Động từ"],
 ["赌博","dǔbó","cờ bạc","Động từ"],
 ["堵塞","dǔsè","tắc nghẽn","Động từ"],
 ["杜绝","dùjué","triệt để ngăn chặn","Danh từ riêng"],
 ["端","duān","đầu, bưng","Động từ"],
 ["端午节","duānwǔjié","Tết Đoan Ngọ","Danh từ chỉ thời gian"],
 ["端正","duānzhèng","đoan chính","Danh từ (Khác)"],
 ["短促","duǎncù","ngắn ngủi","Tính từ"],
 ["断定","duàndìng","phán đoán","Động từ"],
 ["断绝","duànjué","cắt đứt","Động từ"],
 ["堆积","duījī","chất đống","Động từ"],
 ["对策","duìcè","đối sách","Danh từ"],
 ["对称","duìchèn","đối xứng","Động từ"],
 ["对付","duìfu","đối phó","Động từ / Danh từ"],
 ["对立","duìlì","đối lập","Động từ"],
 ["兑现","duìxiàn","thực hiện lời hứa","Động từ"],
 ["顿时","dùnshí","lập tức","Phó từ"],
 ["多元化","duōyuánhuà","đa nguyên hóa","Động từ / Danh từ"],
 ["夺","duó","giành, chiếm","Động từ"],
 ["堕落","duòluò","sa đọa","Động từ"],
 ["额外","éwài","ngoại lệ","Tính từ"],
 ["恶化","èhuà","xấu đi","Động từ"],
 ["恶心","ěxin","buồn nôn","Danh từ"],
 ["遏制","èzhì","kiềm chế","Động từ"],
 ["恩怨","ēnyuàn","ân oán","Danh từ"],
 ["而已","éryǐ","mà thôi","Trợ từ ngữ khí"],
 ["耳闻目睹","ěrwénmùdǔ","tai nghe mắt thấy","Thành ngữ"],
 ["发布","fābù","phát hành","Động từ"],
 ["发财","fā cái","phát tài","Động từ"],
 ["发呆","fā dāi","phát ngẩn","Động từ"],
 ["发动","fādòng","phát động","Động từ / Danh từ"],
 ["发觉","fājué","phát giác","Động từ"],
 ["发落","fāluò","xử lý","Động từ"],
 ["发射","fāshè","phóng","Động từ"],
 ["发誓","fā shì","thề","Động từ"],
 ["发行","fāxíng","phát hành","Động từ"],
 ["发炎","fā yán","viêm","Danh từ"],
 ["发育","fāyù","phát triển (cơ thể)","Động từ / Danh từ"],
 ["法规","fǎguī","pháp quy","Danh từ"],
 ["法人","fǎrén","pháp nhân","Danh từ"],
 ["帆","fān","cánh buồm","Danh từ"],
 ["番","fān","lần","Lượng từ"],
 ["繁殖","fánzhí","sinh sản","Động từ"],
 ["反驳","fǎnbó","bác bỏ","Động từ"],
 ["反常","fǎncháng","bất thường","Phó từ"],
 ["反倒","fǎndào","ngược lại","Động từ"],
 ["反感","fǎngǎn","phản cảm","Động từ"],
 ["反抗","fǎnkàng","kháng cự","Động từ"],
 ["反馈","fǎnkuì","phản hồi","Động từ"],
 ["反面","fǎnmiàn","mặt trái","Phó từ"],
 ["反射","fǎnshè","phản xạ","Động từ"],
 ["反思","fǎnsī","phản tỉnh","Động từ"],
 ["反问","fǎnwèn","phản vấn","Động từ"],
 ["反之","fǎnzhī","ngược lại","Liên từ"],
 ["泛滥","fànlàn","tràn lan","Động từ"],
 ["饭碗","fànwǎn","bát cơm, công việc","Danh từ"],
 ["范畴","fànchóu","phạm trù","Danh từ riêng"],
 ["贩卖","fànmài","buôn bán","Động từ"],
 ["方圆","fāngyuán","vùng","Danh từ"],
 ["方针","fāngzhēn","phương châm","Danh từ"],
 ["防守","fángshǒu","phòng thủ","Động từ"],
 ["防御","fángyù","phòng ngự","Động từ"],
 ["防止","fángzhǐ","phòng chống","Động từ"],
 ["防治","fángzhì","phòng trị","Động từ"],
 ["妨碍","fáng'ài","cản trở","Động từ"],
 ["房屋","fángwū","nhà ở","Danh từ"],
 ["仿造","fǎngzào","giả mạo","Động từ"],
 ["放大","fàngdà","phóng đại","Động từ"],
 ["放射","fàngshè","bức xạ","Động từ"],
 ["放手","fàng shǒu","bỏ tay, buông","Động từ"],
 ["放映","fàngyìng","chiếu (phim)","Động từ"],
 ["飞禽走兽","fēiqínzǒushòu","chim muông","Thành ngữ"],
 ["飞翔","fēixiáng","bay lượn","Danh từ (Khác)"],
 ["飞跃","fēiyuè","nhảy vọt","Động từ"],
 ["非法","fēifǎ","bất hợp pháp","Tính từ"],
 ["肥沃","féiwò","màu mỡ","Tính từ"],
 ["肺","fèi","phổi","Danh từ"],
 ["废除","fèichú","bãi bỏ","Động từ"],
 ["废墟","fèixū","đống đổ nát","Danh từ"],
 ["沸腾","fèiténg","sôi","Động từ"],
 ["分辨","fēnbiàn","phân biệt","Động từ"],
 ["分寸","fēncun","chừng mực","Danh từ"],
 ["分红","fēnhóng","chia lợi nhuận","Động từ"],
 ["分裂","fēnliè","chia rẽ","Động từ"],
 ["分泌","fēnmì","tiết ra","Động từ"],
 ["分明","fēnmíng","rõ ràng","Động từ"],
 ["分歧","fēnqí","bất đồng","Danh từ"],
 ["分散","fēnsàn","phân tán","Động từ"],
 ["吩咐","fēnfu","dặn dò","Động từ"],
 ["坟墓","fénmù","mộ","Danh từ"],
 ["粉笔","fěnbǐ","phấn","Danh từ"],
 ["粉末","fěnmò","bột","Danh từ"],
 ["粉色","fěnsè","hồng","Danh từ"],
 ["粉碎","fěnsuì","nghiền nát","Động từ"],
 ["丰满","fēngmǎn","đầy đặn","Tính từ"],
 ["丰盛","fēngshèng","phong phú (bữa ăn)","Tính từ"],
 ["丰收","fēngshōu","mùa bội thu","Động từ"],
 ["风范","fēngfàn","phong thái","Danh từ"],
 ["风气","fēngqì","nề nếp","Danh từ"],
 ["风趣","fēngqù","hài hước","Danh từ"],
 ["风土人情","fēngtǔrénqíng","phong tục tập quán","Thành ngữ"],
 ["风味","fēngwèi","hương vị","Danh từ"],
 ["封闭","fēngbì","phong tỏa","Động từ"],
 ["封建","fēngjiàn","phong kiến","Tính từ"],
 ["封锁","fēngsuǒ","phong tỏa","Danh từ riêng"],
 ["锋利","fēnglì","sắc bén","Tính từ"],
 ["逢","féng","gặp",""],
 ["讽刺","fěngcì","châm biếm","Động từ"],
 ["奉献","fèngxiàn","cống hiến","Động từ"],
 ["夫妇","fūfù","vợ chồng","Danh từ"],
 ["夫人","fūrén","phu nhân","Danh từ"],
 ["敷衍","fūyǎn","hời hợt, qua loa","Động từ"],
 ["服从","fúcóng","tuân theo","Động từ"],
 ["服气","fúqì","khâm phục","Danh từ"],
 ["俘虏","fúlǔ","tù binh","Danh từ"],
 ["符号","fúhào","ký hiệu","Danh từ"],
 ["幅度","fúdù","biên độ","Danh từ"],
 ["辅助","fǔzhù","hỗ trợ","Động từ / Danh từ"],
 ["腐败","fǔbài","tham nhũng","Tính từ / Danh từ"],
 ["腐烂","fǔlàn","thối rữa","Tính từ"],
 ["腐蚀","fǔshí","ăn mòn","Động từ"],
 ["附带","fùdài","đính kèm","Danh từ"],
 ["附和","fùhè","a dua","Động từ"],
 ["附件","fùjiàn","phụ kiện","Danh từ"],
 ["附属","fùshǔ","phụ thuộc","Tính từ"],
 ["复活","fùhuó","hồi sinh","Động từ / Danh từ"],
 ["赋予","fùyǔ","ban cho","Động từ"],
 ["覆盖","fùgài","phủ lên","Động từ"]
];
