// HSK 3 - 300 từ trung cấp cơ sở
const HSK3 = [
 ["阿姨","āyí","cô, dì","Danh từ"],
 ["啊","a","à (trợ từ)","Trợ từ"],
 ["矮","ǎi","thấp, lùn","Tính từ"],
 ["爱好","àihào","sở thích","Danh từ"],
 ["安静","ānjìng","yên tĩnh","Tính từ"],
 ["把","bǎ","(giới từ) đem, cầm","Giới từ / Lượng từ"],
 ["班","bān","lớp","Danh từ"],
 ["搬","bān","chuyển (nhà)","Động từ"],
 ["半","bàn","nửa","Số từ"],
 ["办法","bànfǎ","cách, biện pháp","Danh từ"],
 ["办公室","bàngōngshì","văn phòng","Danh từ"],
 ["帮忙","bāng máng","giúp đỡ","Động từ"],
 ["包","bāo","túi, bao","Danh từ"],
 ["饱","bǎo","no","Tính từ"],
 ["北方","běifāng","phía Bắc","Danh từ"],
 ["被","bèi","bị, được","Giới từ"],
 ["鼻子","bízi","mũi","Danh từ"],
 ["比较","bǐjiào","tương đối, so sánh","Phó từ / Động từ"],
 ["比赛","bǐsài","thi đấu","Danh từ / Động từ"],
 ["笔记本","bǐjìběn","vở, sổ tay","Danh từ"],
 ["必须","bìxū","phải, bắt buộc","Phó từ"],
 ["变化","biànhuà","thay đổi","Danh từ / Động từ"],
 ["表示","biǎoshì","biểu thị, thể hiện","Động từ"],
 ["表演","biǎoyǎn","biểu diễn","Động từ / Danh từ"],
 ["别人","biéren","người khác","Đại từ"],
 ["冰箱","bīngxiāng","tủ lạnh","Danh từ"],
 ["不但…而且","búdàn...érqiě","không những...mà còn","Liên từ"],
 ["才","cái","mới (vừa)","Phó từ"],
 ["菜单","càidān","thực đơn","Danh từ"],
 ["参加","cānjiā","tham gia","Động từ"],
 ["草","cǎo","cỏ","Danh từ"],
 ["层","céng","tầng, lớp","Lượng từ"],
 ["差","chà","kém, thiếu","Tính từ / Động từ"],
 ["超市","chāoshì","siêu thị","Danh từ"],
 ["衬衫","chènshān","áo sơ mi","Danh từ"],
 ["成绩","chéngjì","thành tích, kết quả","Danh từ"],
 ["城市","chéngshì","thành phố","Danh từ"],
 ["迟到","chídào","đến muộn","Động từ"],
 ["除了","chúle","ngoài ra","Giới từ"],
 ["厨房","chúfáng","nhà bếp","Danh từ"],
 ["出现","chūxiàn","xuất hiện","Động từ"],
 ["春","chūn","mùa xuân","Danh từ"],
 ["词典","cídiǎn","từ điển","Danh từ"],
 ["聪明","cōngming","thông minh","Tính từ"],
 ["打扫","dǎsǎo","dọn dẹp","Động từ"],
 ["打算","dǎsuàn","dự định","Động từ / Danh từ"],
 ["带","dài","mang, đeo","Động từ"],
 ["担心","dānxīn","lo lắng","Động từ"],
 ["蛋糕","dàngāo","bánh kem","Danh từ"],
 ["当然","dāngrán","tất nhiên","Phó từ / Tính từ"],
 ["地","de","(trợ từ trạng ngữ)","Trợ từ"],
 ["灯","dēng","đèn","Danh từ"],
 ["地方","dìfang","nơi, chỗ","Danh từ"],
 ["地铁","dìtiě","tàu điện ngầm","Danh từ"],
 ["地图","dìtú","bản đồ","Danh từ"],
 ["电梯","diàntī","thang máy","Danh từ"],
 ["电子邮件","diànzǐ yóujiàn","email","Danh từ"],
 ["东","dōng","đông","Danh từ"],
 ["冬","dōng","mùa đông","Danh từ"],
 ["动物","dòngwù","động vật","Danh từ"],
 ["短","duǎn","ngắn","Tính từ"],
 ["段","duàn","đoạn","Lượng từ"],
 ["锻炼","duànliàn","tập thể dục","Động từ"],
 ["多么","duōme","biết bao","Phó từ"],
 ["饿","è","đói","Tính từ"],
 ["耳朵","ěrduo","tai","Danh từ"],
 ["发","fā","gửi, phát","Động từ"],
 ["发烧","fā shāo","sốt","Động từ"],
 ["发现","fāxiàn","phát hiện","Động từ"],
 ["方便","fāngbiàn","thuận tiện","Tính từ"],
 ["放","fàng","đặt, thả","Động từ"],
 ["放心","fàng xīn","yên tâm","Động từ"],
 ["分","fēn","phút, phân","Lượng từ / Động từ"],
 ["附近","fùjìn","gần đây","Danh từ"],
 ["复习","fùxí","ôn tập","Động từ"],
 ["干净","gānjìng","sạch sẽ","Tính từ"],
 ["感冒","gǎnmào","cảm cúm","Động từ / Danh từ"],
 ["刚才","gāngcái","vừa nãy","Danh từ chỉ thời gian"],
 ["跟","gēn","theo, với","Giới từ / Động từ"],
 ["根据","gēnjù","căn cứ, dựa theo","Giới từ / Căn cứ"],
 ["更","gèng","càng, hơn","Phó từ"],
 ["公斤","gōngjīn","kg","Lượng từ"],
 ["公园","gōngyuán","công viên","Danh từ"],
 ["故事","gùshi","câu chuyện","Danh từ"],
 ["刮风","guā fēng","gió thổi","Động từ"],
 ["关","guān","đóng","Động từ"],
 ["关系","guānxi","quan hệ","Danh từ"],
 ["关心","guānxīn","quan tâm","Động từ"],
 ["关于","guānyú","về (chủ đề)","Giới từ"],
 ["国家","guójiā","quốc gia","Danh từ"],
 ["果汁","guǒzhī","nước ép trái cây","Danh từ"],
 ["过","guò","qua","Trợ từ / Động từ"],
 ["过去","guòqù","quá khứ","Danh từ chỉ thời gian"],
 ["还是","háishi","vẫn là, hay là","Liên từ / Phó từ"],
 ["害怕","hàipà","sợ hãi","Động từ"],
 ["寒假","hánjià","nghỉ đông","Danh từ"],
 ["河","hé","sông","Danh từ"],
 ["黑板","hēibǎn","bảng đen","Danh từ"],
 ["后来","hòulái","sau đó","Danh từ chỉ thời gian"],
 ["护照","hùzhào","hộ chiếu","Danh từ"],
 ["花","huā","tiêu (tiền), hoa","Động từ / Danh từ"],
 ["花园","huāyuán","vườn hoa","Danh từ"],
 ["画","huà","bức tranh, vẽ","Động từ / Danh từ"],
 ["坏","huài","hỏng, xấu","Tính từ"],
 ["欢迎","huānyíng","chào mừng","Động từ"],
 ["环境","huánjìng","môi trường","Danh từ"],
 ["换","huàn","đổi","Động từ"],
 ["黄","huáng","vàng","Tính từ"],
 ["回答","huídá","trả lời","Động từ"],
 ["回忆","huíyì","hồi ức","Danh từ / Động từ"],
 ["会议","huìyì","hội nghị","Danh từ"],
 ["或者","huòzhě","hoặc","Liên từ"],
 ["几乎","jīhū","hầu như","Phó từ"],
 ["机会","jīhuì","cơ hội","Danh từ"],
 ["极","jí","cực kỳ","Phó từ"],
 ["季节","jìjié","mùa","Danh từ"],
 ["记得","jìde","nhớ","Động từ"],
 ["记住","jìzhù","ghi nhớ","Động từ"],
 ["检查","jiǎnchá","kiểm tra","Động từ / Danh từ"],
 ["简单","jiǎndān","đơn giản","Tính từ"],
 ["健康","jiànkāng","khỏe mạnh","Tính từ / Danh từ"],
 ["见面","jiàn miàn","gặp mặt","Động từ"],
 ["讲","jiǎng","giảng, nói","Động từ"],
 ["教","jiāo","dạy","Động từ"],
 ["脚","jiǎo","chân","Danh từ"],
 ["角","jiǎo","góc, hào (tiền)","Lượng từ"],
 ["接","jiē","đón, nhận","Động từ"],
 ["街道","jiēdào","đường phố","Danh từ"],
 ["节目","jiémù","chương trình","Danh từ"],
 ["节日","jiérì","ngày lễ","Danh từ"],
 ["结婚","jié hūn","kết hôn","Động từ"],
 ["结束","jiéshù","kết thúc","Động từ"],
 ["解决","jiějué","giải quyết","Động từ"],
 ["借","jiè","mượn","Động từ"],
 ["经常","jīngcháng","thường xuyên","Phó từ"],
 ["经过","jīngguò","đi qua, trải qua","Giới từ / Động từ"],
 ["经理","jīnglǐ","giám đốc","Danh từ"],
 ["久","jiǔ","lâu","Tính từ"],
 ["旧","jiù","cũ","Tính từ"],
 ["举行","jǔxíng","tổ chức","Động từ"],
 ["句子","jùzi","câu","Danh từ"],
 ["决定","juédìng","quyết định","Động từ / Danh từ"],
 ["可爱","kě'ài","đáng yêu","Tính từ"],
 ["渴","kě","khát","Tính từ"],
 ["客人","kèrén","khách","Danh từ"],
 ["空调","kōngtiáo","điều hòa","Danh từ"],
 ["口","kǒu","miệng","Lượng từ / Danh từ"],
 ["哭","kū","khóc","Động từ"],
 ["裤子","kùzi","quần","Danh từ"],
 ["筷子","kuàizi","đũa","Danh từ"],
 ["蓝","lán","xanh dương","Tính từ"],
 ["老","lǎo","già","Tính từ"],
 ["离开","líkāi","rời khỏi","Động từ"],
 ["礼物","lǐwù","quà tặng","Danh từ"],
 ["历史","lìshǐ","lịch sử","Danh từ"],
 ["脸","liǎn","mặt","Danh từ"],
 ["练习","liànxí","luyện tập","Động từ / Danh từ"],
 ["辆","liàng","(lượng từ) chiếc (xe)","Lượng từ"],
 ["了解","liǎojiě","hiểu biết","Động từ"],
 ["邻居","línjū","hàng xóm","Danh từ"],
 ["留学","liúxué","du học","Động từ"],
 ["楼","lóu","tòa nhà, tầng","Danh từ"],
 ["绿","lǜ","xanh lá","Tính từ"],
 ["马","mǎ","ngựa","Danh từ"],
 ["马上","mǎshàng","ngay lập tức","Phó từ"],
 ["满意","mǎnyì","hài lòng","Tính từ / Động từ"],
 ["帽子","màozi","mũ","Danh từ"],
 ["米","mǐ","mét, gạo","Lượng từ / Danh từ"],
 ["面包","miànbāo","bánh mì","Danh từ"],
 ["明白","míngbai","hiểu rõ","Tính từ / Động từ"],
 ["拿","ná","cầm, lấy","Động từ"],
 ["奶奶","nǎinai","bà nội","Danh từ"],
 ["南","nán","nam","Danh từ"],
 ["南方","nánfāng","phía nam","Danh từ"],
 ["难","nán","khó","Tính từ"],
 ["难过","nánguò","buồn, khó chịu","Tính từ"],
 ["年级","niánjí","khối lớp","Danh từ"],
 ["年轻","niánqīng","trẻ","Tính từ"],
 ["鸟","niǎo","chim","Danh từ"],
 ["努力","nǔlì","cố gắng","Tính từ / Động từ"],
 ["爬山","pá shān","leo núi","Động từ"],
 ["盘子","pánzi","cái đĩa","Danh từ"],
 ["胖","pàng","béo, mập","Tính từ"],
 ["啤酒","píjiǔ","bia","Danh từ"],
 ["皮鞋","píxié","giày da","Danh từ"],
 ["瓶子","píngzi","chai, bình","Danh từ"],
 ["普通话","pǔtōnghuà","tiếng phổ thông","Danh từ"],
 ["骑","qí","cưỡi, đi (xe)","Động từ"],
 ["奇怪","qíguài","kỳ lạ","Tính từ"],
 ["其他","qítā","khác","Đại từ"],
 ["其实","qíshí","thực ra","Phó từ"],
 ["起来","qǐlai","lên, dậy","Động từ"],
 ["清楚","qīngchu","rõ ràng","Tính từ"],
 ["请假","qǐng jià","xin nghỉ phép","Động từ"],
 ["秋","qiū","mùa thu","Danh từ"],
 ["裙子","qúnzi","váy","Danh từ"],
 ["然后","ránhòu","sau đó","Liên từ / Phó từ"],
 ["热情","rèqíng","nhiệt tình","Tính từ"],
 ["认为","rènwéi","cho rằng","Động từ"],
 ["认真","rènzhēn","nghiêm túc","Tính từ"],
 ["容易","róngyì","dễ dàng","Tính từ"],
 ["如果","rúguǒ","nếu","Liên từ"],
 ["伞","sǎn","ô, dù","Danh từ"],
 ["上网","shàng wǎng","lên mạng","Động từ"],
 ["生气","shēng qì","tức giận","Tính từ / Động từ"],
 ["声音","shēngyīn","âm thanh, giọng","Danh từ"],
 ["世界","shìjiè","thế giới","Danh từ"],
 ["瘦","shòu","gầy, ốm","Tính từ"],
 ["叔叔","shūshu","chú","Danh từ"],
 ["舒服","shūfu","thoải mái","Tính từ"],
 ["树","shù","cây","Danh từ"],
 ["数学","shùxué","toán học","Danh từ"],
 ["刷牙","shuā yá","đánh răng","Động từ"],
 ["双","shuāng","đôi","Lượng từ"],
 ["水平","shuǐpíng","trình độ","Danh từ"],
 ["司机","sījī","tài xế","Danh từ"],
 ["太阳","tàiyáng","mặt trời","Danh từ"],
 ["特别","tèbié","đặc biệt","Tính từ / Phó từ"],
 ["疼","téng","đau","Tính từ / Động từ"],
 ["提高","tígāo","nâng cao","Động từ"],
 ["体育","tǐyù","thể dục","Danh từ"],
 ["甜","tián","ngọt","Tính từ"],
 ["条","tiáo","(lượng từ) sợi, con","Lượng từ"],
 ["同事","tóngshì","đồng nghiệp","Danh từ"],
 ["同意","tóngyì","đồng ý","Động từ"],
 ["头发","tóufa","tóc","Danh từ"],
 ["突然","tūrán","đột nhiên","Tính từ / Phó từ"],
 ["图书馆","túshūguǎn","thư viện","Danh từ"],
 ["腿","tuǐ","chân (từ đầu gối)","Danh từ"],
 ["完成","wánchéng","hoàn thành","Động từ"],
 ["碗","wǎn","bát, chén","Danh từ / Lượng từ"],
 ["晚","wǎn","muộn, tối","Tính từ"],
 ["忘记","wàngjì","quên","Động từ"],
 ["为","wèi","vì","Giới từ"],
 ["为了","wèile","vì, để","Giới từ"],
 ["位","wèi","(lượng từ) vị","Lượng từ"],
 ["文化","wénhuà","văn hóa","Danh từ"],
 ["西","xī","tây","Danh từ"],
 ["习惯","xíguàn","thói quen","Danh từ / Động từ"],
 ["洗手间","xǐshǒujiān","nhà vệ sinh","Danh từ"],
 ["洗澡","xǐ zǎo","tắm","Động từ"],
 ["夏","xià","mùa hè","Danh từ"],
 ["先","xiān","trước","Phó từ"],
 ["相信","xiāngxìn","tin tưởng","Động từ"],
 ["香蕉","xiāngjiāo","chuối","Danh từ"],
 ["向","xiàng","về phía, hướng","Giới từ"],
 ["像","xiàng","giống","Động từ"],
 ["小心","xiǎoxīn","cẩn thận","Tính từ / Động từ"],
 ["校长","xiàozhǎng","hiệu trưởng","Danh từ"],
 ["新闻","xīnwén","tin tức","Danh từ"],
 ["新鲜","xīnxiān","tươi","Tính từ"],
 ["信","xìn","thư","Danh từ"],
 ["信用卡","xìnyòngkǎ","thẻ tín dụng","Danh từ"],
 ["行李箱","xínglixiāng","vali","Danh từ"],
 ["兴趣","xìngqù","hứng thú","Danh từ"],
 ["熊猫","xióngmāo","gấu trúc","Danh từ"],
 ["需要","xūyào","cần","Động từ"],
 ["选择","xuǎnzé","lựa chọn","Động từ / Danh từ"],
 ["要求","yāoqiú","yêu cầu","Động từ / Danh từ"],
 ["爷爷","yéye","ông nội","Danh từ"],
 ["一般","yìbān","bình thường","Tính từ / Phó từ"],
 ["一边","yìbiān","vừa... vừa","Phó từ"],
 ["一定","yídìng","nhất định","Tính từ / Phó từ"],
 ["一共","yígòng","tổng cộng","Phó từ"],
 ["一会儿","yíhuìr","một lát","Đại từ / Phó từ"],
 ["一样","yíyàng","giống nhau","Tính từ"],
 ["一直","yìzhí","luôn, thẳng","Phó từ"],
 ["以后","yǐhòu","sau này","Danh từ chỉ thời gian"],
 ["以前","yǐqián","trước đây","Danh từ chỉ thời gian"],
 ["以为","yǐwéi","tưởng rằng","Động từ"],
 ["音乐","yīnyuè","âm nhạc","Danh từ"],
 ["银行","yínháng","ngân hàng","Danh từ"],
 ["应该","yīnggāi","nên","Động từ năng nguyện"],
 ["影响","yǐngxiǎng","ảnh hưởng","Động từ / Danh từ"],
 ["用","yòng","dùng","Động từ"],
 ["游戏","yóuxì","trò chơi","Danh từ"],
 ["有名","yǒumíng","nổi tiếng","Tính từ"],
 ["又","yòu","lại","Phó từ"],
 ["遇到","yùdào","gặp","Động từ"],
 ["元","yuán","đồng (tiền)","Lượng từ"],
 ["愿意","yuànyì","sẵn lòng","Động từ năng nguyện"],
 ["月亮","yuèliang","mặt trăng","Danh từ"],
 ["越","yuè","càng","Phó từ"],
 ["站","zhàn","trạm, đứng","Động từ / Danh từ"],
 ["张","zhāng","(lượng từ) tờ","Lượng từ"],
 ["照顾","zhàogù","chăm sóc","Động từ"],
 ["照片","zhàopiàn","ảnh","Danh từ"],
 ["照相机","zhàoxiàngjī","máy ảnh","Danh từ"],
 ["着急","zháojí","sốt ruột","Tính từ"],
 ["只","zhǐ","chỉ","Phó từ / Lượng từ"],
 ["只有","zhǐyǒu","chỉ có","Liên từ / Phó từ"],
 ["中间","zhōngjiān","ở giữa","Danh từ phương hướng"],
 ["终于","zhōngyú","cuối cùng","Phó từ"],
 ["种","zhǒng","loại","Lượng từ"],
 ["重要","zhòngyào","quan trọng","Tính từ"],
 ["周末","zhōumò","cuối tuần","Danh từ"],
 ["主要","zhǔyào","chủ yếu","Tính từ"],
 ["注意","zhùyì","chú ý","Động từ"],
 ["自己","zìjǐ","tự mình","Đại từ"],
 ["总是","zǒngshì","luôn luôn","Phó từ"],
 ["嘴","zuǐ","miệng","Danh từ"],
 ["最近","zuìjìn","gần đây","Danh từ chỉ thời gian"],
 ["作业","zuòyè","bài tập","Danh từ"],
 ["作用","zuòyòng","tác dụng","Danh từ"]
];
