// HSK 5 Part 2 - 650 từ cao cấp (phần 2)
const HSK5_2 = [
 ["机器","jīqì","máy móc","Danh từ"],
 ["基本","jīběn","cơ bản","Danh từ"],
 ["激烈","jīliè","kịch liệt","Tính từ"],
 ["及格","jí gé","đạt điểm","Tính từ / Phó từ"],
 ["极其","jíqí","cực kỳ","Phó từ"],
 ["急忙","jímáng","vội vàng","Phó từ"],
 ["集合","jíhé","tập hợp","Động từ"],
 ["集体","jítǐ","tập thể","Danh từ"],
 ["集中","jízhōng","tập trung","Động từ"],
 ["纪录","jìlù","kỷ lục","Danh từ"],
 ["纪律","jìlǜ","kỷ luật","Danh từ"],
 ["纪念","jìniàn","kỷ niệm","Danh từ"],
 ["寂寞","jìmò","cô đơn","Tính từ"],
 ["系领带","jì lǐngdài","thắt cà vạt","Danh từ"],
 ["夹子","jiāzi","kẹp","Danh từ"],
 ["嘉宾","jiābīn","khách quý","Danh từ (Địa danh)"],
 ["家庭","jiātíng","gia đình","Danh từ"],
 ["家务","jiāwù","việc nhà","Danh từ"],
 ["家乡","jiāxiāng","quê hương","Danh từ"],
 ["假如","jiǎrú","giả sử","Liên từ"],
 ["假设","jiǎshè","giả thiết","Động từ / Danh từ"],
 ["假装","jiǎzhuāng","giả vờ","Danh từ"],
 ["价值","jiàzhí","giá trị","Danh từ"],
 ["驾驶","jiàshǐ","lái xe","Động từ"],
 ["嫁","jià","lấy chồng","Động từ"],
 ["坚决","jiānjué","kiên quyết","Tính từ / Phó từ"],
 ["坚强","jiānqiáng","kiên cường","Động từ"],
 ["肩膀","jiānbǎng","vai","Danh từ"],
 ["艰巨","jiānjù","gian khổ","Tính từ"],
 ["艰苦","jiānkǔ","gian khổ","Tính từ"],
 ["剪刀","jiǎndāo","kéo","Danh từ"],
 ["拣","jiǎn","nhặt","Động từ"],
 ["建立","jiànlì","thành lập","Động từ"],
 ["建设","jiànshè","xây dựng","Động từ / Danh từ"],
 ["建筑","jiànzhù","kiến trúc","Danh từ"],
 ["健身房","jiànshēnfáng","phòng gym","Danh từ"],
 ["键盘","jiànpán","bàn phím","Danh từ"],
 ["讲究","jiǎngjiu","cầu kỳ","Động từ / Danh từ"],
 ["讲座","jiǎngzuò","bài giảng","Danh từ"],
 ["降落","jiàngluò","hạ cánh","Động từ"],
 ["酱油","jiàngyóu","nước tương","Danh từ"],
 ["交换","jiāohuàn","trao đổi","Động từ"],
 ["交际","jiāojì","giao tế","Danh từ"],
 ["郊区","jiāoqū","ngoại ô","Danh từ nơi chốn"],
 ["胶水","jiāoshuǐ","keo dán","Danh từ"],
 ["角度","jiǎodù","góc độ","Danh từ"],
 ["狡猾","jiǎohuá","xảo quyệt","Tính từ"],
 ["教材","jiàocái","giáo trình","Danh từ"],
 ["教练","jiàoliàn","huấn luyện viên","Động từ / Danh từ"],
 ["教训","jiàoxun","bài học (kinh nghiệm)","Động từ / Danh từ"],
 ["阶段","jiēduàn","giai đoạn","Danh từ"],
 ["接触","jiēchù","tiếp xúc","Động từ"],
 ["接待","jiēdài","tiếp đãi","Động từ"],
 ["接近","jiējìn","tiếp cận","Động từ"],
 ["节省","jiéshěng","tiết kiệm","Danh từ"],
 ["节约","jiéyuē","tiết kiệm","Danh từ"],
 ["结构","jiégòu","cấu trúc","Danh từ"],
 ["结合","jiéhé","kết hợp","Động từ"],
 ["结论","jiélùn","kết luận","Danh từ"],
 ["结账","jié zhàng","thanh toán","Danh từ"],
 ["解放","jiěfàng","giải phóng","Động từ"],
 ["届","jiè","khóa, kỳ","Phó từ"],
 ["借口","jièkǒu","lý do, cớ","Danh từ"],
 ["金属","jīnshǔ","kim loại","Danh từ"],
 ["紧急","jǐnjí","khẩn cấp","Tính từ"],
 ["尽力","jìn lì","cố hết sức","Phó từ"],
 ["尽量","jǐnliàng","cố gắng","Phó từ"],
 ["进步","jìnbù","tiến bộ","Phó từ"],
 ["进口","jìnkǒu","nhập khẩu","Động từ / Danh từ"],
 ["近代","jìndài","cận đại","Danh từ chỉ thời gian"],
 ["精力","jīnglì","năng lượng","Danh từ"],
 ["精神","jīngshén","tinh thần","Danh từ"],
 ["酒吧","jiǔbā","quán bar","Danh từ"],
 ["救","jiù","cứu","Động từ"],
 ["救护车","jiùhùchē","xe cứu thương","Danh từ"],
 ["舅舅","jiùjiu","cậu (anh/em trai mẹ)","Danh từ"],
 ["居然","jūrán","thậm chí, bỗng","Phó từ"],
 ["桔子","júzi","quả quýt","Danh từ"],
 ["巨大","jùdà","to lớn","Tính từ"],
 ["具备","jùbèi","có đủ","Động từ"],
 ["具体","jùtǐ","cụ thể","Tính từ"],
 ["俱乐部","jùlèbù","câu lạc bộ","Danh từ"],
 ["据说","jùshuō","nghe nói","Động từ"],
 ["卷","juǎn","cuộn","Số từ"],
 ["决赛","juésài","chung kết","Danh từ"],
 ["决心","juéxīn","quyết tâm","Động từ"],
 ["角色","juésè","vai trò","Danh từ"],
 ["绝对","juéduì","tuyệt đối","Phó từ"],
 ["军事","jūnshì","quân sự","Danh từ"],
 ["均匀","jūnyún","đều","Tính từ"],
 ["卡车","kǎchē","xe tải","Danh từ"],
 ["开发","kāifā","khai phá","Động từ"],
 ["开放","kāifàng","mở cửa","Động từ"],
 ["开幕式","kāimùshì","lễ khai mạc","Danh từ"],
 ["开水","kāishuǐ","nước sôi","Động từ"],
 ["砍","kǎn","chặt","Động từ"],
 ["看不起","kànbuqǐ","khinh thường","Động từ"],
 ["看来","kànlái","xem ra","Động từ"],
 ["抗议","kàngyì","phản đối","Danh từ (Khác)"],
 ["烤鸭","kǎoyā","vịt quay","Danh từ"],
 ["颗","kē","(lượng từ) hạt","Số từ"],
 ["可靠","kěkào","đáng tin cậy","Động từ"],
 ["可怕","kěpà","đáng sợ","Liên từ"],
 ["克","kè","gam","Số từ"],
 ["克服","kèfú","khắc phục","Động từ"],
 ["刻苦","kèkǔ","chăm chỉ","Động từ"],
 ["客观","kèguān","khách quan","Danh từ"],
 ["课程","kèchéng","khóa học","Danh từ"],
 ["空间","kōngjiān","không gian","Danh từ"],
 ["空闲","kòngxián","rảnh rỗi","Danh từ"],
 ["控制","kòngzhì","kiểm soát","Động từ"],
 ["口味","kǒuwèi","khẩu vị","Danh từ"],
 ["夸","kuā","khen","Động từ"],
 ["夸张","kuāzhāng","phóng đại","Động từ"],
 ["会计","kuàijì","kế toán","Động từ"],
 ["宽","kuān","rộng","Tính từ"],
 ["矿","kuàng","mỏ (khoáng sản)","Danh từ"],
 ["困","kùn","khó khăn","Động từ"],
 ["扩大","kuòdà","mở rộng","Động từ"],
 ["辣椒","làjiāo","ớt","Danh từ"],
 ["啦","la","(trợ từ)","Trợ từ ngữ khí"],
 ["拦","lán","cản, chặn","Động từ"],
 ["蜡烛","làzhú","nến","Danh từ"],
 ["懒","lǎn","lười","Tính từ"],
 ["烂","làn","nát, thối","Động từ"],
 ["朗读","lǎngdú","đọc to","Động từ"],
 ["劳动","láodòng","lao động","Động từ / Danh từ"],
 ["劳驾","láojià","xin phiền","Danh từ riêng"],
 ["老百姓","lǎobǎixìng","dân thường","Danh từ"],
 ["老板","lǎobǎn","ông chủ","Danh từ"],
 ["老婆","lǎopo","vợ","Danh từ"],
 ["老实","lǎoshi","thật thà","Danh từ"],
 ["老鼠","lǎoshǔ","con chuột","Danh từ"],
 ["姥姥","lǎolao","bà ngoại","Danh từ"],
 ["乐观","lèguān","lạc quan","Tính từ"],
 ["雷","léi","sấm sét","Danh từ"],
 ["类","lèi","loại","Lượng từ"],
 ["冷淡","lěngdàn","lạnh nhạt","Tính từ"],
 ["厘米","límǐ","cm","Lượng từ"],
 ["梨","lí","quả lê","Danh từ"],
 ["立场","lìchǎng","lập trường","Danh từ"],
 ["立即","lìjí","ngay lập tức","Phó từ"],
 ["立刻","lìkè","ngay tức khắc","Phó từ"],
 ["利润","lìrùn","lợi nhuận","Danh từ"],
 ["利息","lìxī","lãi suất","Danh từ"],
 ["利益","lìyì","lợi ích","Danh từ"],
 ["利用","lìyòng","sử dụng, lợi dụng","Danh từ"],
 ["连忙","liánmáng","vội vàng","Phó từ"],
 ["连续","liánxù","liên tục","Tính từ"],
 ["联合","liánhé","liên hợp","Động từ"],
 ["恋爱","liàn'ài","yêu đương","Động từ"],
 ["良好","liánghǎo","tốt đẹp","Tính từ"],
 ["粮食","liángshi","lương thực","Danh từ"],
 ["灵活","línghuó","linh hoạt","Tính từ"],
 ["铃","líng","chuông","Danh từ riêng"],
 ["零件","língjiàn","linh kiện","Số - Lượng từ"],
 ["零食","língshí","đồ ăn vặt","Danh từ"],
 ["领域","lǐngyù","lĩnh vực","Danh từ"],
 ["浏览","liúlǎn","lướt xem","Động từ"],
 ["龙","lóng","rồng","Danh từ"],
 ["漏","lòu","rò rỉ","Động từ"],
 ["陆地","lùdì","lục địa","Danh từ"],
 ["陆续","lùxù","lần lượt","Phó từ"],
 ["录取","lùqǔ","tuyển chọn","Động từ"],
 ["录音","lùyīn","ghi âm","Danh từ"],
 ["轮流","lúnliú","luân phiên","Danh từ"],
 ["论文","lùnwén","luận văn","Danh từ (Khác)"],
 ["落后","luòhòu","tụt hậu","Tính từ"],
 ["骂","mà","mắng","Động từ"],
 ["埋","mái","chôn","Động từ"],
 ["馒头","mántou","bánh bao","Danh từ"],
 ["满足","mǎnzú","thỏa mãn","Động từ"],
 ["毛病","máobìng","lỗi, bệnh","Danh từ"],
 ["矛盾","máodùn","mâu thuẫn","Tính từ / Danh từ"],
 ["冒险","mào xiǎn","mạo hiểm","Danh từ"],
 ["贸易","màoyì","thương mại","Động từ / Danh từ"],
 ["魅力","mèilì","sức hấp dẫn","Danh từ"],
 ["眯","mī","nheo (mắt)","Động từ"],
 ["迷","mí","mê","Động từ"],
 ["谜语","míyǔ","câu đố","Danh từ"],
 ["秘密","mìmì","bí mật","Danh từ"],
 ["秘书","mìshū","thư ký","Danh từ"],
 ["密切","mìqiè","mật thiết","Tính từ / Phó từ"],
 ["蜜蜂","mìfēng","con ong","Danh từ"],
 ["免得","miǎnde","tránh","Động từ"],
 ["面对","miànduì","đối mặt","Động từ"],
 ["面积","miànjī","diện tích","Danh từ"],
 ["面临","miànlín","đối mặt","Động từ"],
 ["苗条","miáotiao","mảnh mai","Danh từ"],
 ["描写","miáoxiě","miêu tả","Động từ"],
 ["民主","mínzhǔ","dân chủ","Danh từ"],
 ["名牌","míngpái","thương hiệu","Danh từ"],
 ["名胜古迹","míngshèng gǔjì","danh lam thắng cảnh","Danh từ"],
 ["名片","míngpiàn","danh thiếp","Danh từ"],
 ["明确","míngquè","rõ ràng","Tính từ / Phó từ"],
 ["明显","míngxiǎn","rõ rệt","Tính từ"],
 ["命令","mìnglìng","mệnh lệnh","Danh từ"],
 ["命运","mìngyùn","vận mệnh","Danh từ"],
 ["摸","mō","sờ, mó","Động từ"],
 ["模仿","mófǎng","bắt chước","Động từ"],
 ["模糊","móhu","mơ hồ","Tính từ"],
 ["模特","mótè","người mẫu","Tính từ"],
 ["摩托车","mótuōchē","xe máy","Danh từ (Khác)"],
 ["陌生","mòshēng","xa lạ","Danh từ"],
 ["某","mǒu","nào đó","Đại từ"],
 ["木头","mùtou","gỗ","Danh từ"],
 ["目标","mùbiāo","mục tiêu","Danh từ"],
 ["目录","mùlù","mục lục","Danh từ"],
 ["目前","mùqián","hiện tại","Danh từ chỉ thời gian"],
 ["内部","nèibù","nội bộ","Danh từ phương hướng"],
 ["嫩","nèn","non, mềm","Tính từ"],
 ["能干","nénggàn","giỏi giang","Danh từ"],
 ["能源","néngyuán","năng lượng","Danh từ"],
 ["泥","ní","bùn","Danh từ"],
 ["年代","niándài","niên đại","Danh từ chỉ thời gian"],
 ["年纪","niánjì","tuổi tác","Danh từ chỉ thời gian"],
 ["念","niàn","nhớ, đọc","Động từ"],
 ["宁可","nìngkě","thà","Danh từ riêng"],
 ["牛仔裤","niúzǎikù","quần bò","Danh từ"],
 ["农村","nóngcūn","nông thôn","Danh từ"],
 ["农民","nóngmín","nông dân","Danh từ"],
 ["农业","nóngyè","nông nghiệp","Danh từ"],
 ["浓","nóng","đặc, đậm","Tính từ"],
 ["女士","nǚshì","nữ sĩ, quý bà","Danh từ"],
 ["暖","nuǎn","ấm","Tính từ"],
 ["偶然","ǒurán","ngẫu nhiên","Phó từ"],
 ["拍","pāi","vỗ, chụp ảnh","Động từ"],
 ["派","pài","phái, cử","Động từ"],
 ["盼望","pànwàng","mong đợi","Động từ"],
 ["培养","péiyǎng","bồi dưỡng","Động từ"],
 ["赔偿","péicháng","bồi thường","Động từ"],
 ["配合","pèihé","phối hợp","Động từ"],
 ["盆","pén","chậu","Danh từ"],
 ["碰","pèng","va chạm","Động từ"],
 ["碰见","pèngjiàn","gặp (tình cờ)","Động từ"],
 ["批","pī","(lượng từ) lô, mẻ","Lượng từ"],
 ["批准","pīzhǔn","phê chuẩn","Động từ"],
 ["疲劳","píláo","mệt mỏi","Tính từ"],
 ["皮带","pídài","thắt lưng","Danh từ"],
 ["匹","pǐ","(lượng từ) con (ngựa)","Lượng từ"],
 ["片","piàn","(lượng từ) mảnh","Lượng từ"],
 ["片面","piànmiàn","phiến diện","Danh từ"],
 ["飘","piāo","bay","Động từ"],
 ["频道","píndào","kênh (TV)","Danh từ"],
 ["品种","pǐnzhǒng","giống, loại","Danh từ"],
 ["平安","píng'ān","bình an","Tính từ"],
 ["平常","píngcháng","bình thường","Tính từ"],
 ["平等","píngděng","bình đẳng","Tính từ"],
 ["平方","píngfāng","mét vuông","Lượng từ"],
 ["平衡","pínghéng","cân bằng","Tính từ"],
 ["平静","píngjìng","bình tĩnh","Tính từ"],
 ["评价","píngjià","đánh giá","Danh từ"],
 ["屏幕","píngmù","màn hình","Danh từ"],
 ["迫切","pòqiè","cấp bách","Tính từ"],
 ["破产","pò chǎn","phá sản","Động từ"],
 ["破坏","pòhuài","phá hoại","Động từ"],
 ["朴素","pǔsù","giản dị","Danh từ riêng"],
 ["期待","qīdài","mong đợi","Động từ"],
 ["期间","qījiān","giai đoạn","Danh từ phương hướng"],
 ["旗袍","qípáo","sườn xám","Danh từ"],
 ["棋","qí","cờ (trò chơi)","Danh từ"],
 ["奇迹","qíjì","kỳ tích","Danh từ"],
 ["企业","qǐyè","doanh nghiệp","Danh từ"],
 ["启发","qǐfā","gợi mở","Động từ"],
 ["气氛","qìfēn","bầu không khí","Danh từ"],
 ["汽油","qìyóu","xăng","Danh từ"],
 ["谦虚","qiānxū","khiêm tốn","Tính từ"],
 ["签","qiān","ký","Động từ"],
 ["前途","qiántú","tương lai","Danh từ"],
 ["浅","qiǎn","nông, nhạt","Tính từ"],
 ["欠","qiàn","nợ, thiếu","Động từ"],
 ["枪","qiāng","súng","Danh từ"],
 ["强调","qiángdiào","nhấn mạnh","Động từ"],
 ["强烈","qiángliè","mãnh liệt","Tính từ"],
 ["抢","qiǎng","cướp, giành","Động từ"],
 ["悄悄","qiāoqiāo","lẳng lặng","Hình dung từ"],
 ["瞧","qiáo","nhìn","Động từ"],
 ["切","qiē","cắt","Động từ"],
 ["亲爱","qīn'ài","thân yêu","Tính từ"],
 ["亲切","qīnqiè","thân thiết","Tính từ"],
 ["亲自","qīnzì","đích thân","Phó từ"],
 ["青","qīng","xanh","Danh từ (Địa danh)"],
 ["青春","qīngchūn","thanh xuân","Danh từ (Địa danh)"],
 ["青少年","qīngshàonián","thanh thiếu niên","Danh từ riêng"],
 ["轻视","qīngshì","coi thường","Tính từ"],
 ["清淡","qīngdàn","thanh đạm","Tính từ"],
 ["情景","qíngjǐng","cảnh tượng","Danh từ"],
 ["情绪","qíngxù","cảm xúc","Danh từ"],
 ["请求","qǐngqiú","yêu cầu","Động từ"],
 ["庆祝","qìngzhù","kỷ niệm, ăn mừng","Động từ"],
 ["球迷","qiúmí","fan bóng đá","Danh từ"],
 ["趋势","qūshì","xu hướng","Danh từ"],
 ["取消","qǔxiāo","hủy bỏ","Động từ"],
 ["去世","qùshì","qua đời","Danh từ chỉ thời gian"],
 ["圈","quān","vòng","Lượng từ"],
 ["权力","quánlì","quyền lực","Danh từ"],
 ["权利","quánlì","quyền lợi","Danh từ"],
 ["劝","quàn","khuyên","Động từ"],
 ["缺乏","quēfá","thiếu hụt","Động từ"],
 ["确定","quèdìng","xác định","Động từ"],
 ["确认","quèrèn","xác nhận","Động từ"],
 ["群","qún","nhóm, đàn","Danh từ"],
 ["燃烧","ránshāo","đốt cháy","Động từ"],
 ["嚷","rǎng","la hét","Động từ"],
 ["绕","rào","vòng quanh","Động từ"],
 ["热爱","rèài","yêu mến","Tính từ"],
 ["热烈","rèliè","nhiệt liệt","Tính từ"],
 ["热心","rèxīn","nhiệt tình","Danh từ"],
 ["人才","réncái","nhân tài","Danh từ"],
 ["人口","rénkǒu","dân số","Danh từ"],
 ["人类","rénlèi","nhân loại","Danh từ"],
 ["人民币","rénmínbì","RMB, nhân dân tệ","Danh từ"],
 ["人生","rénshēng","cuộc đời","Danh từ"],
 ["人事","rénshì","nhân sự","Danh từ"],
 ["人物","rénwù","nhân vật","Danh từ"],
 ["人员","rényuán","nhân viên","Danh từ"],
 ["忍不住","rěnbuzhù","không nhịn được","Động từ"],
 ["日常","rìcháng","hàng ngày","Phó từ"],
 ["日程","rìchéng","lịch trình","Danh từ"],
 ["日历","rìlì","lịch","Danh từ chỉ thời gian"],
 ["日期","rìqī","ngày tháng","Danh từ chỉ thời gian"],
 ["日用品","rìyòngpǐn","đồ dùng hàng ngày","Danh từ"],
 ["融化","rónghuà","tan chảy","Động từ / Danh từ"],
 ["柔和","róuhé","dịu dàng","Tính từ"],
 ["如何","rúhé","như thế nào","Đại từ"],
 ["如今","rújīn","hiện nay","Danh từ chỉ thời gian"],
 ["软","ruǎn","mềm","Tính từ"],
 ["软件","ruǎnjiàn","phần mềm","Danh từ"],
 ["弱","ruò","yếu","Tính từ"],
 ["洒","sǎ","rải, rắc","Động từ"],
 ["嗓子","sǎngzi","cổ họng","Danh từ"],
 ["色彩","sècǎi","màu sắc","Danh từ"],
 ["杀","shā","giết","Động từ"],
 ["沙漠","shāmò","sa mạc","Danh từ"],
 ["沙滩","shātān","bãi biển","Danh từ riêng"],
 ["傻","shǎ","ngốc","Tính từ"],
 ["晒","shài","phơi","Động từ"],
 ["删除","shānchú","xóa bỏ","Động từ"],
 ["闪电","shǎndiàn","tia chớp","Động từ"],
 ["善良","shànliáng","lương thiện","Tính từ"],
 ["善于","shànyú","giỏi về","Động từ"],
 ["商品","shāngpǐn","hàng hóa","Danh từ"],
 ["商业","shāngyè","thương mại","Danh từ"],
 ["上当","shàng dàng","bị lừa","Động từ"],
 ["勺子","sháozi","cái muỗng","Danh từ"],
 ["蛇","shé","con rắn","Danh từ"],
 ["舍不得","shěbude","không nỡ","Động từ"],
 ["设备","shèbèi","thiết bị","Động từ / Danh từ"],
 ["设计","shèjì","thiết kế","Động từ / Danh từ"],
 ["设施","shèshī","cơ sở vật chất","Danh từ"],
 ["射","shè","bắn","Động từ"],
 ["摄影","shèyǐng","nhiếp ảnh","Danh từ"],
 ["伸","shēn","giơ, duỗi","Động từ"],
 ["身材","shēncái","dáng người","Danh từ"],
 ["身份","shēnfèn","thân phận","Danh từ"],
 ["神话","shénhuà","thần thoại","Danh từ"],
 ["神秘","shénmì","bí ẩn","Tính từ"],
 ["升","shēng","lên, thăng",""],
 ["生长","shēngzhǎng","sinh trưởng","Danh từ"],
 ["声明","shēngmíng","tuyên bố","Danh từ"],
 ["绳子","shéngzi","dây","Danh từ"],
 ["胜利","shènglì","thắng lợi","Động từ / Danh từ"],
 ["失去","shīqù","mất","Động từ"],
 ["失业","shī yè","thất nghiệp","Danh từ"],
 ["诗","shī","thơ","Danh từ"],
 ["时差","shíchā","chênh múi giờ","Danh từ"],
 ["时代","shídài","thời đại","Danh từ"],
 ["时髦","shímáo","thời trang","Danh từ riêng"],
 ["时刻","shíkè","thời khắc","Danh từ"],
 ["时期","shíqī","thời kỳ","Danh từ"],
 ["时尚","shíshàng","thời thượng","Danh từ"],
 ["实话","shíhuà","lời thật","Động từ"],
 ["实践","shíjiàn","thực tiễn","Động từ"],
 ["实习","shíxí","thực tập","Động từ"],
 ["实现","shíxiàn","thực hiện","Động từ"],
 ["实行","shíxíng","thi hành","Động từ"],
 ["实验","shíyàn","thí nghiệm","Động từ / Danh từ"],
 ["石头","shítou","đá","Danh từ"],
 ["食物","shíwù","thức ăn","Danh từ"],
 ["始终","shǐzhōng","từ đầu đến cuối","Phó từ"],
 ["士兵","shìbīng","binh lính","Danh từ"],
 ["市场","shìchǎng","thị trường","Danh từ"],
 ["试卷","shìjuàn","bài thi","Danh từ"],
 ["事实","shìshí","sự thực","Danh từ"],
 ["事物","shìwù","sự vật","Danh từ"],
 ["事先","shìxiān","trước đó","Phó từ"],
 ["收获","shōuhuò","thu hoạch","Động từ"],
 ["手工","shǒugōng","thủ công","Danh từ"],
 ["手术","shǒushù","phẫu thuật","Danh từ"],
 ["手套","shǒutào","găng tay","Danh từ"],
 ["手续","shǒuxù","thủ tục","Động từ"],
 ["手指","shǒuzhǐ","ngón tay","Danh từ"],
 ["寿命","shòumìng","tuổi thọ","Danh từ"]
];
