// HSK 6 Part 2 - 1250 từ thành thạo (phần 2)
const HSK6_2 = [
 ["改良","gǎiliáng","cải lương","Động từ"],
 ["盖章","gài zhāng","đóng dấu","Danh từ riêng"],
 ["概论","gàilùn","khái luận","Danh từ"],
 ["干旱","gānhàn","hạn hán","Tính từ"],
 ["干劲","gànjìn","hăng hái","Tính từ"],
 ["干涉","gānshè","can thiệp","Động từ"],
 ["干预","gānyù","can dự","Động từ"],
 ["感慨","gǎnkǎi","cảm khái","Động từ"],
 ["感染","gǎnrǎn","nhiễm","Động từ"],
 ["岗位","gǎngwèi","vị trí công tác","Danh từ"],
 ["港口","gǎngkǒu","cảng","Danh từ"],
 ["港湾","gǎngwān","vịnh","Danh từ (Địa danh)"],
 ["高超","gāochāo","cao siêu","Danh từ riêng"],
 ["高潮","gāocháo","cao trào","Danh từ riêng"],
 ["高峰","gāofēng","đỉnh cao","Danh từ riêng"],
 ["高尚","gāoshàng","cao thượng","Danh từ"],
 ["高涨","gāozhǎng","tăng cao","Động từ"],
 ["稿件","gǎojiàn","bản thảo","Danh từ"],
 ["告辞","gàocí","cáo từ","Động từ"],
 ["告诫","gàojiè","cảnh cáo","Động từ"],
 ["割","gē","cắt","Động từ"],
 ["搁置","gēzhì","gác lại","Động từ"],
 ["歌颂","gēsòng","ca ngợi","Động từ"],
 ["格局","géjú","cách cục","Danh từ"],
 ["格式","géshì","định dạng","Danh từ"],
 ["隔阂","géhé","cách trở","Danh từ"],
 ["隔离","gélí","cách ly","Động từ"],
 ["个体","gètǐ","cá thể","Danh từ"],
 ["根深蒂固","gēnshēndìgù","ăn sâu bén rễ","Thành ngữ"],
 ["根源","gēnyuán","nguồn gốc","Danh từ"],
 ["耕地","gēngdì","đất canh tác","Danh từ"],
 ["更新","gēngxīn","cập nhật","Phó từ"],
 ["更正","gēngzhèng","đính chính","Phó từ"],
 ["工艺品","gōngyìpǐn","đồ thủ công mỹ nghệ","Danh từ"],
 ["公安","gōng'ān","công an","Danh từ"],
 ["公道","gōngdào","công bằng","Danh từ"],
 ["公费","gōngfèi","công phí","Danh từ"],
 ["公告","gōnggào","thông cáo","Danh từ"],
 ["公关","gōngguān","quan hệ công chúng","Danh từ"],
 ["公民","gōngmín","công dân","Danh từ"],
 ["公然","gōngrán","công khai","Tính từ / Phó từ"],
 ["公认","gōngrèn","được công nhận","Động từ"],
 ["公式","gōngshì","công thức","Danh từ"],
 ["公务","gōngwù","công vụ","Danh từ"],
 ["公正","gōngzhèng","công chính","Danh từ riêng"],
 ["功劳","gōngláo","công lao","Danh từ"],
 ["攻击","gōngjī","tấn công","Động từ"],
 ["攻克","gōngkè","chinh phục","Động từ"],
 ["供不应求","gōngbùyìngqiú","cung không đủ cầu","Từ láy / Quán dụng ngữ"],
 ["供给","gōngjǐ","cung cấp","Động từ / Danh từ"],
 ["宫殿","gōngdiàn","cung điện","Danh từ riêng"],
 ["恭维","gōngwéi","xu nịnh","Danh từ"],
 ["巩固","gǒnggù","củng cố","Động từ"],
 ["共鸣","gòngmíng","cộng hưởng","Động từ"],
 ["共享","gòngxiǎng","chia sẻ","Động từ"],
 ["勾结","gōujié","câu kết","Động từ"],
 ["沟渠","gōuqú","kênh rãnh","Danh từ"],
 ["构思","gòusī","ý tưởng","Động từ"],
 ["构造","gòuzào","cấu tạo","Động từ"],
 ["估量","gūliang","đánh giá","Danh từ"],
 ["辜负","gūfù","phụ lòng","Động từ"],
 ["孤独","gūdú","cô đơn","Tính từ"],
 ["孤立","gūlì","cô lập","Động từ"],
 ["姑且","gūqiě","tạm thời","Phó từ"],
 ["古董","gǔdǒng","đồ cổ","Danh từ riêng"],
 ["古怪","gǔguài","kỳ quặc","Tính từ"],
 ["谷","gǔ","thung lũng, lúa","Danh từ riêng"],
 ["故障","gùzhàng","hỏng hóc","Danh từ"],
 ["固然","gùrán","tất nhiên","Liên từ"],
 ["固有","gùyǒu","cố hữu","Tính từ"],
 ["固执","gùzhí","cố chấp","Tính từ"],
 ["顾虑","gùlǜ","lo ngại","Động từ"],
 ["顾问","gùwèn","cố vấn","Danh từ riêng"],
 ["乖巧","guāiqiǎo","ngoan","Tính từ"],
 ["官方","guānfāng","chính phủ","Danh từ"],
 ["关怀","guānhuái","quan hoài","Danh từ riêng"],
 ["关照","guānzhào","chiếu cố","Giới từ"],
 ["观光","guānguāng","tham quan","Danh từ"],
 ["管辖","guǎnxiá","quản lý (khu vực)","Động từ"],
 ["灌溉","guàngài","tưới tiêu","Động từ / Danh từ"],
 ["光彩","guāngcǎi","quang thái","Danh từ"],
 ["光辉","guānghuī","huy hoàng","Danh từ riêng"],
 ["光芒","guāngmáng","ánh sáng","Danh từ"],
 ["归还","guīhuán","trả lại","Động từ"],
 ["归结","guījié","quy kết","Động từ"],
 ["规范","guīfàn","quy phạm","Danh từ"],
 ["规格","guīgé","quy cách","Danh từ"],
 ["规划","guīhuà","quy hoạch","Danh từ"],
 ["规章","guīzhāng","quy chương","Danh từ"],
 ["轨道","guǐdào","quỹ đạo","Danh từ"],
 ["跪","guì","quỳ","Động từ"],
 ["滚","gǔn","lăn","Động từ"],
 ["棍","gùn","gậy",""],
 ["锅","guō","nồi","Danh từ"],
 ["国防","guófáng","quốc phòng","Danh từ"],
 ["国务院","guówùyuàn","quốc vụ viện","Danh từ (Tổ chức)"],
 ["果断","guǒduàn","quả đoán","Phó từ"],
 ["过渡","guòdù","quá độ","Động từ"],
 ["过奖","guòjiǎng","quá khen","Danh từ (Khác)"],
 ["过失","guòshī","lỗi lầm","Động từ"],
 ["过问","guòwèn","can thiệp","Động từ"],
 ["过瘾","guòyǐn","đã, thích thú","Danh từ"],
 ["过于","guòyú","quá","Động từ"],
 ["骇人听闻","hàiréntīngwén","rùng rợn","Thành ngữ"],
 ["含糊","hánhu","mơ hồ","Tính từ"],
 ["含义","hányì","ý nghĩa","Danh từ"],
 ["寒暄","hánxuān","chào hỏi xã giao","Danh từ riêng"],
 ["罕见","hǎnjiàn","hiếm thấy","Tính từ"],
 ["捍卫","hànwèi","bảo vệ","Động từ"],
 ["航空","hángkōng","hàng không","Danh từ"],
 ["航天","hángtiān","hàng không vũ trụ","Danh từ"],
 ["航行","hángxíng","đi biển","Danh từ"],
 ["毫不犹豫","háobùyóuyù","không chần chừ","Từ láy / Quán dụng ngữ"],
 ["毫无","háowú","hoàn toàn không","Động từ"],
 ["耗费","hàofèi","tiêu tốn","Động từ"],
 ["号召","hàozhào","kêu gọi","Động từ"],
 ["和蔼","hé'ǎi","hòa ái","Danh từ riêng"],
 ["和解","héjiě","hòa giải","Động từ"],
 ["和睦","hémù","hòa thuận","Danh từ riêng"],
 ["和气","héqi","hòa khí","Danh từ"],
 ["和谐","héxié","hòa hợp","Tính từ"],
 ["核实","héshí","xác minh","Danh từ"],
 ["核算","hésuàn","hạch toán","Danh từ"],
 ["核心","héxīn","hạt nhân","Danh từ"],
 ["黑暗","hēi'àn","tối tăm","Hình dung từ"],
 ["痕迹","hénjì","dấu vết","Danh từ"],
 ["恒心","héngxīn","lòng kiên trì","Danh từ"],
 ["横","héng","ngang","Động từ"],
 ["哄","hǒng","dỗ","Động từ"],
 ["宏观","hóngguān","vĩ mô","Danh từ"],
 ["宏伟","hóngwěi","hùng vĩ","Tính từ"],
 ["洪水","hóngshuǐ","lũ lụt","Danh từ riêng"],
 ["吼","hǒu","gầm","Động từ"],
 ["后代","hòudài","hậu thế","Danh từ chỉ thời gian"],
 ["后顾之忧","hòugùzhīyōu","mối lo hậu phương","Thành ngữ"],
 ["后勤","hòuqín","hậu cần","Danh từ"],
 ["候选","hòuxuǎn","ứng cử","Động từ"],
 ["呼唤","hūhuàn","gọi","Danh từ riêng"],
 ["呼吁","hūyù","kêu gọi","Động từ"],
 ["胡乱","húluàn","bừa bãi","Danh từ"],
 ["胡子","húzi","râu","Danh từ riêng"],
 ["湖泊","húpō","hồ","Danh từ (Địa danh)"],
 ["互联网","hùliánwǎng","internet","Danh từ"],
 ["花瓣","huābàn","cánh hoa","Danh từ"],
 ["花蕾","huālěi","nụ hoa","Danh từ riêng"],
 ["滑坡","huápō","sụt giảm, sạt lở","Danh từ (Địa danh)"],
 ["华丽","huálì","hoa lệ","Danh từ riêng"],
 ["化肥","huàféi","phân bón","Danh từ"],
 ["化石","huàshí","hóa thạch","Danh từ"],
 ["化验","huàyàn","xét nghiệm","Danh từ"],
 ["化妆","huàzhuāng","trang điểm","Danh từ"],
 ["划分","huàfēn","phân chia","Động từ"],
 ["画蛇添足","huàshétiānzú","vẽ rắn thêm chân","Thành ngữ"],
 ["话筒","huàtǒng","micro","Danh từ"],
 ["怀抱","huáibào","ôm","Động từ"],
 ["欢乐","huānlè","vui mừng","Tính từ"],
 ["环节","huánjié","khâu, mắt xích","Danh từ"],
 ["还原","huányuán","hoàn nguyên","Động từ"],
 ["缓和","huǎnhé","hòa hoãn","Tính từ"],
 ["缓冲","huǎnchōng","đệm","Động từ"],
 ["患者","huànzhě","bệnh nhân","Danh từ"],
 ["荒凉","huāngliáng","hoang vắng","Tính từ"],
 ["荒谬","huāngmiù","hoang đường","Tính từ"],
 ["荒唐","huāngtáng","hoang đường","Tính từ"],
 ["皇帝","huángdì","hoàng đế","Danh từ"],
 ["皇后","huánghòu","hoàng hậu","Danh từ"],
 ["黄昏","huánghūn","hoàng hôn","Danh từ chỉ thời gian"],
 ["恍然大悟","huǎngrándàwù","chợt ngộ ra","Thành ngữ"],
 ["晃","huǎng","lắc, lóa","Động từ"],
 ["挥霍","huīhuò","hoang phí","Động từ"],
 ["辉煌","huīhuáng","huy hoàng","Tính từ"],
 ["回报","huíbào","đền đáp","Động từ"],
 ["回避","huíbì","tránh né","Động từ"],
 ["回顾","huígù","nhìn lại","Động từ"],
 ["回收","huíshōu","thu hồi","Động từ"],
 ["悔恨","huǐhèn","ân hận","Động từ"],
 ["毁灭","huǐmiè","hủy diệt","Động từ"],
 ["汇报","huìbào","báo cáo","Danh từ (Khác)"],
 ["会晤","huìwù","hội đàm","Động từ"],
 ["贿赂","huìlù","hối lộ","Động từ"],
 ["昏迷","hūnmí","hôn mê","Động từ"],
 ["混合","hùnhé","hỗn hợp","Động từ / Danh từ"],
 ["混乱","hùnluàn","hỗn loạn","Tính từ"],
 ["混淆","hùnxiáo","lẫn lộn","Động từ"],
 ["活该","huógāi","đáng đời","Động từ"],
 ["活力","huólì","sức sống","Danh từ"],
 ["火箭","huǒjiàn","tên lửa","Danh từ"],
 ["火焰","huǒyàn","ngọn lửa","Danh từ"],
 ["火药","huǒyào","thuốc súng","Danh từ"],
 ["货币","huòbì","tiền tệ","Danh từ"],
 ["货物","huòwù","hàng hóa","Danh từ"],
 ["祸害","huòhai","tai họa","Danh từ"],
 ["饥饿","jī'è","đói","Danh từ"],
 ["饥荒","jīhuāng","nạn đói","Danh từ"],
 ["机动","jīdòng","cơ động","Danh từ"],
 ["机构","jīgòu","cơ quan","Danh từ"],
 ["机灵","jīling","nhanh trí","Danh từ"],
 ["机密","jīmì","cơ mật","Danh từ"],
 ["机械","jīxiè","cơ khí","Danh từ"],
 ["机遇","jīyù","cơ duyên","Danh từ"],
 ["机智","jīzhì","cơ trí","Danh từ"],
 ["激发","jīfā","kích thích","Động từ"],
 ["激光","jīguāng","laser","Danh từ"],
 ["积蓄","jīxù","tích lũy","Danh từ"],
 ["基金","jījīn","quỹ","Danh từ"],
 ["基因","jīyīn","gen","Danh từ"],
 ["嫉妒","jídù","ghen tỵ","Động từ"],
 ["即便","jíbiàn","cho dù","Liên từ"],
 ["急功近利","jígōngjìnlì","nóng vội","Thành ngữ"],
 ["急切","jíqiè","cấp bách","Tính từ"],
 ["急于求成","jíyúqiúchéng","nôn nóng","Thành ngữ"],
 ["急躁","jízào","nóng nảy","Tính từ"],
 ["籍贯","jíguàn","quê quán","Danh từ riêng"],
 ["计较","jìjiào","tính toán, so đo","Động từ"],
 ["记载","jìzǎi","ghi chép","Động từ"],
 ["纪要","jìyào","biên bản","Động từ"],
 ["忌讳","jìhuì","kiêng kỵ","Động từ"],
 ["寄托","jìtuō","gửi gắm","Động từ"],
 ["济","jì","giúp đỡ","Tên gọi tắt"],
 ["加工","jiā gōng","gia công","Động từ / Danh từ"],
 ["加剧","jiājù","gia tăng","Động từ"],
 ["佳","jiā","tốt đẹp","Tính từ"],
 ["夹缝","jiāfèng","khe hẹp","Danh từ"],
 ["嘉奖","jiājiǎng","khen thưởng","Danh từ (Khác)"],
 ["假定","jiǎdìng","giả định","Động từ"],
 ["假说","jiǎshuō","giả thuyết","Liên từ"],
 ["嫁接","jiàjiē","ghép","Động từ"],
 ["价格","jiàgé","giá cả","Danh từ"],
 ["驾驭","jiàyù","điều khiển","Động từ"],
 ["架子","jiàzi","giá, bệ","Danh từ"],
 ["尖锐","jiānruì","sắc bén","Tính từ"],
 ["尖端","jiānduān","tiên tiến","Danh từ"],
 ["坚定","jiāndìng","kiên định","Tính từ"],
 ["坚固","jiāngù","kiên cố","Tính từ"],
 ["坚韧","jiānrèn","kiên nhẫn","Tính từ"],
 ["坚实","jiānshí","vững chắc","Tính từ / Phó từ"],
 ["坚硬","jiānyìng","cứng","Tính từ"],
 ["艰难","jiānnán","gian nan","Tính từ"],
 ["兼职","jiān zhí","kiêm nhiệm","Động từ"],
 ["监督","jiāndū","giám sát","Động từ / Danh từ"],
 ["监视","jiānshì","giám sát","Động từ"],
 ["监狱","jiānyù","nhà tù","Danh từ"],
 ["简化","jiǎnhuà","đơn giản hóa","Động từ"],
 ["简陋","jiǎnlòu","đơn sơ","Tính từ"],
 ["简要","jiǎnyào","tóm tắt","Tính từ"],
 ["见解","jiànjiě","kiến giải","Động từ"],
 ["见闻","jiànwén","kiến văn","Danh từ"],
 ["见效","jiànxiào","có hiệu quả","Động từ"],
 ["见义勇为","jiànyìyǒngwéi","thấy nghĩa dũng làm","Thành ngữ"],
 ["间谍","jiàndié","gián điệp","Danh từ"],
 ["间隔","jiàngé","khoảng cách","Danh từ"],
 ["间接","jiànjiē","gián tiếp","Tính từ"],
 ["间断","jiànduàn","gián đoạn","Phó từ"],
 ["荐","jiàn","tiến cử","Động từ"],
 ["鉴定","jiàndìng","thẩm định","Động từ"],
 ["鉴于","jiànyú","xét vì","Giới từ"],
 ["键","jiàn","phím","Danh từ"],
 ["箭","jiàn","mũi tên","Danh từ"],
 ["江","jiāng","sông","Danh từ riêng"],
 ["姜","jiāng","gừng","Danh từ riêng"],
 ["僵硬","jiāngyìng","cứng đờ","Tính từ"],
 ["讲话","jiǎnghuà","phát biểu","Danh từ"],
 ["讲解","jiǎngjiě","giải thích","Động từ"],
 ["奖励","jiǎnglì","thưởng","Động từ / Danh từ"],
 ["奖赏","jiǎngshǎng","ban thưởng","Động từ"],
 ["降临","jiànglín","giáng lâm","Động từ"],
 ["浇","jiāo","tưới","Động từ"],
 ["焦点","jiāodiǎn","tiêu điểm","Danh từ"],
 ["焦急","jiāojí","lo lắng","Tính từ"],
 ["角落","jiǎoluò","góc","Danh từ"],
 ["绞尽脑汁","jiǎojìnnǎozhī","vắt óc suy nghĩ","Thành ngữ"],
 ["搅拌","jiǎobàn","khuấy trộn","Động từ"],
 ["缴纳","jiǎonà","nộp","Động từ"],
 ["轿车","jiàochē","ô tô con","Danh từ"],
 ["教养","jiàoyǎng","giáo dưỡng","Danh từ"],
 ["接连","jiēlián","liên tiếp","Động từ"],
 ["揭露","jiēlù","vạch trần","Động từ"],
 ["揭开","jiēkāi","mở ra","Động từ"],
 ["阶层","jiēcéng","giai tầng","Danh từ"],
 ["截止","jiézhǐ","hạn chót","Động từ"],
 ["截至","jiézhì","tính đến","Động từ"],
 ["竭力","jiélì","hết sức","Phó từ"],
 ["竭尽全力","jiéjìnquánlì","dốc sức","Thành ngữ"],
 ["结局","jiéjú","kết cục","Danh từ"],
 ["结晶","jiéjīng","kết tinh","Danh từ"],
 ["结算","jiésuàn","quyết toán","Động từ"],
 ["杰出","jiéchū","kiệt xuất","Tính từ"],
 ["解除","jiěchú","giải trừ","Động từ"],
 ["解雇","jiěgù","sa thải","Động từ"],
 ["解剖","jiěpōu","giải phẫu","Động từ"],
 ["解散","jiěsàn","giải tán","Động từ"],
 ["解体","jiětǐ","tan rã","Danh từ"],
 ["戒备","jièbèi","cảnh giác","Danh từ"],
 ["介入","jièrù","can thiệp","Động từ"],
 ["界限","jièxiàn","ranh giới","Danh từ"],
 ["金融","jīnróng","tài chính","Danh từ"],
 ["津津有味","jīnjīnyǒuwèi","ngon lành","Thành ngữ"],
 ["紧迫","jǐnpò","cấp bách","Phó từ"],
 ["锦上添花","jǐnshàngtiānhuā","gấm thêm hoa","Thành ngữ"],
 ["尽快","jǐnkuài","càng sớm càng tốt","Phó từ"],
 ["尽量","jǐnliàng","cố sức","Phó từ"],
 ["进而","jìn'ér","từ đó mà","Liên từ"],
 ["进攻","jìngōng","tấn công","Động từ"],
 ["进化","jìnhuà","tiến hóa","Động từ"],
 ["精打细算","jīngdǎxìsuàn","tính toán kỹ","Thành ngữ"],
 ["精华","jīnghuá","tinh hoa","Danh từ (Khác)"],
 ["精简","jīngjiǎn","tinh giản","Danh từ"],
 ["精密","jīngmì","tinh mật","Tính từ"],
 ["精确","jīngquè","chính xác","Tính từ"],
 ["精通","jīngtōng","tinh thông","Tính từ"],
 ["精心","jīngxīn","tinh ý","Danh từ"],
 ["精益求精","jīngyìqiújīng","ngày càng hoàn thiện","Danh từ"],
 ["精致","jīngzhì","tinh xảo","Tính từ"],
 ["经费","jīngfèi","kinh phí","Động từ / Danh từ"],
 ["经商","jīng shāng","kinh doanh","Danh từ"],
 ["经纬","jīngwěi","kinh vĩ","Danh từ"],
 ["颈","jǐng","cổ","Danh từ"],
 ["井","jǐng","giếng",""],
 ["景气","jǐngqì","cảnh khí","Danh từ"],
 ["警告","jǐnggào","cảnh cáo","Danh từ"],
 ["警惕","jǐngtì","cảnh giác","Động từ"],
 ["竞赛","jìngsài","thi đấu","Động từ / Danh từ"],
 ["竞选","jìngxuǎn","tranh cử","Động từ / Danh từ"],
 ["敬爱","jìng'ài","kính yêu","Danh từ riêng"],
 ["敬礼","jìnglǐ","chào","Danh từ riêng"],
 ["敬业","jìngyè","tận tâm","Danh từ"],
 ["境界","jìngjiè","cảnh giới","Danh từ"],
 ["镜头","jìngtóu","ống kính","Danh từ"],
 ["纠纷","jiūfēn","tranh chấp","Danh từ"],
 ["纠正","jiūzhèng","sửa chữa","Động từ"],
 ["酒精","jiǔjīng","cồn","Danh từ"],
 ["就近","jiùjìn","gần đây","Phó từ"],
 ["就业","jiùyè","tìm việc","Động từ"],
 ["就职","jiùzhí","nhậm chức","Động từ"],
 ["救济","jiùjì","cứu tế","Danh từ"],
 ["居民","jūmín","cư dân","Danh từ"],
 ["居住","jūzhù","cư trú","Động từ"],
 ["局部","júbù","cục bộ","Danh từ"],
 ["局面","júmiàn","cục diện","Danh từ"],
 ["局势","júshì","cục thế","Danh từ"],
 ["局限","júxiàn","hạn chế","Danh từ"],
 ["举动","jǔdòng","hành vi","Động từ"],
 ["举世闻名","jǔshìwénmíng","nổi tiếng thế giới","Thành ngữ"],
 ["举世瞩目","jǔshìzhǔmù","cả thế giới chú ý","Thành ngữ"],
 ["举足轻重","jǔzúqīngzhòng","quan trọng","Thành ngữ"],
 ["聚精会神","jùjīnghuìshén","tập trung chú ý","Danh từ"],
 ["捐","juān","quyên góp","Động từ"],
 ["卷","juǎn","cuộn","Số từ"],
 ["抉择","juézé","lựa chọn","Động từ"],
 ["觉悟","juéwù","giác ngộ","Động từ"],
 ["觉醒","juéxǐng","thức tỉnh","Động từ"],
 ["绝望","juéwàng","tuyệt vọng","Động từ"],
 ["崛起","juéqǐ","trỗi dậy","Động từ"],
 ["军队","jūnduì","quân đội","Danh từ"],
 ["军阀","jūnfá","quân phiệt","Danh từ"],
 ["开采","kāicǎi","khai thác","Động từ"],
 ["开辟","kāipì","khai phá","Động từ"],
 ["开拓","kāituò","mở rộng","Động từ"],
 ["开销","kāixiāo","chi tiêu","Động từ"],
 ["开展","kāizhǎn","triển khai","Động từ"],
 ["刊登","kāndēng","đăng báo","Động từ"],
 ["刊物","kānwù","ấn phẩm","Danh từ"],
 ["勘探","kāntàn","thăm dò","Động từ / Danh từ"],
 ["看待","kàndài","nhìn nhận","Động từ"],
 ["看望","kànwàng","thăm","Động từ"],
 ["慷慨","kāngkǎi","hào phóng","Tính từ"],
 ["抗议","kàngyì","phản đối","Danh từ (Khác)"],
 ["考古","kǎogǔ","khảo cổ","Động từ / Danh từ"],
 ["考核","kǎohé","kiểm tra, đánh giá","Động từ / Danh từ"],
 ["考验","kǎoyàn","thử thách","Động từ / Danh từ"],
 ["磕","kē","gõ, va","Động từ"],
 ["科目","kēmù","môn học","Danh từ"],
 ["可观","kěguān","đáng kể","Tính từ"],
 ["可口","kěkǒu","ngon miệng","Động từ"],
 ["刻不容缓","kèbùrónghuǎn","không thể chần chừ","Thành ngữ"],
 ["客户","kèhù","khách hàng","Danh từ"],
 ["课题","kètí","đề tài","Danh từ"],
 ["恳切","kěnqiè","tha thiết","Tính từ"],
 ["坑","kēng","hố","Danh từ"],
 ["空洞","kōngdòng","rỗng tuếch","Danh từ"],
 ["空前绝后","kōngqiánjuéhòu","vô tiền khoáng hậu","Từ láy / Quán dụng ngữ"],
 ["空想","kōngxiǎng","viễn vông","Danh từ"],
 ["恐吓","kǒnghè","đe dọa","Động từ"],
 ["恐惧","kǒngjù","sợ hãi","Tính từ / Danh từ"],
 ["孔","kǒng","lỗ","Danh từ riêng"],
 ["空隙","kòngxì","khe hở","Danh từ"],
 ["口气","kǒuqì","giọng, hơi thở","Danh từ"],
 ["口腔","kǒuqiāng","miệng (y tế)","Danh từ"],
 ["口头","kǒutóu","bằng miệng","Danh từ"],
 ["枯燥","kūzào","khô khan","Tính từ"],
 ["苦尽甘来","kǔjìngānlái","khổ tận cam lai","Thành ngữ"],
 ["苦难","kǔnàn","khổ nạn","Tính từ"],
 ["夸大","kuādà","phóng đại","Động từ"],
 ["夸奖","kuājiǎng","khen ngợi","Động từ"],
 ["跨","kuà","bước qua","Động từ"],
 ["快活","kuàihuo","vui vẻ","Phó từ"],
 ["宽敞","kuānchang","rộng rãi","Tính từ"],
 ["宽容","kuānróng","khoan dung","Tính từ"],
 ["宽慰","kuānwèi","an ủi","Tính từ"],
 ["款待","kuǎndài","khoản đãi","Động từ"],
 ["款式","kuǎnshì","kiểu dáng","Danh từ"],
 ["狂风暴雨","kuángfēngbàoyǔ","bão tố","Thành ngữ"],
 ["矿产","kuàngchǎn","khoáng sản","Danh từ"],
 ["旷课","kuàng kè","trốn học","Danh từ"],
 ["亏待","kuīdài","đối xử bạc","Động từ"],
 ["亏损","kuīsǔn","thua lỗ","Động từ / Danh từ"],
 ["昆虫","kūnchóng","côn trùng","Danh từ"],
 ["捆","kǔn","bó, gói","Động từ"],
 ["括号","kuòhào","ngoặc","Danh từ"],
 ["扩充","kuòchōng","mở rộng","Động từ"],
 ["扩张","kuòzhāng","bành trướng","Động từ"],
 ["辣","là","cay","Danh từ"],
 ["来历","láilì","lai lịch","Động từ"],
 ["来源","láiyuán","nguồn gốc","Danh từ"],
 ["栏目","lánmù","chuyên mục","Danh từ"],
 ["谅解","liàngjiě","thông cảm","Động từ"],
 ["晾","liàng","phơi",""],
 ["辽阔","liáokuò","rộng lớn","Tính từ"],
 ["猎","liè","săn","Động từ"],
 ["列举","lièjǔ","liệt kê","Động từ"],
 ["临床","línchuáng","lâm sàng","Động từ / Danh từ"],
 ["临时","línshí","tạm thời","Tính từ"],
 ["灵感","línggǎn","cảm hứng","Tính từ"],
 ["灵魂","línghún","linh hồn","Danh từ"],
 ["灵敏","língmǐn","nhạy bén","Danh từ riêng"],
 ["凌晨","língchén","rạng sáng","Danh từ chỉ thời gian"],
 ["领袖","lǐngxiù","lãnh tụ","Danh từ"],
 ["领导","lǐngdǎo","lãnh đạo","Danh từ"],
 ["流传","liúchuán","lưu truyền","Động từ / Danh từ"],
 ["流浪","liúlàng","lang thang","Danh từ"],
 ["流露","liúlù","lộ ra","Động từ"],
 ["流氓","liúmáng","lưu manh","Danh từ"],
 ["流通","liútōng","lưu thông","Động từ / Danh từ"],
 ["留恋","liúliàn","lưu luyến","Động từ"],
 ["留念","liúniàn","lưu niệm","Động từ"],
 ["留神","liú shén","chú ý","Động từ"],
 ["垄断","lǒngduàn","lũng đoạn","Động từ"],
 ["笼罩","lǒngzhào","bao phủ","Động từ"],
 ["隆重","lóngzhòng","long trọng","Tính từ"],
 ["搂","lǒu","ôm","Động từ"],
 ["露","lù","sương, lộ ra","Động từ"],
 ["屡次","lǚcì","nhiều lần","Phó từ"],
 ["履行","lǚxíng","thực hiện","Động từ"],
 ["掠夺","lüèduó","cướp đoạt","Động từ"],
 ["略微","lüèwēi","hơi","Phó từ"],
 ["轮廓","lúnkuò","đường nét","Danh từ"],
 ["轮胎","lúntāi","lốp xe","Danh từ"],
 ["论坛","lùntán","diễn đàn","Danh từ"],
 ["论证","lùnzhèng","luận chứng","Danh từ"],
 ["啰嗦","luōsuo","dài dòng","Hình dung từ"],
 ["落成","luòchéng","hoàn thành","Động từ"],
 ["落实","luòshí","thực hiện","Tính từ"],
 ["络绎不绝","luòyìbùjué","nối nhau không dứt","Thành ngữ"]
];
