// HSK 4 - 600 từ trung cấp
const HSK4 = [
 ["按时","ànshí","đúng giờ","Phó từ"],
 ["按照","ànzhào","theo, chiểu theo","Giới từ"],
 ["安排","ānpái","sắp xếp","Động từ"],
 ["安全","ānquán","an toàn","Tính từ / Danh từ"],
 ["暗","àn","tối","Phó từ"],
 ["百分之","bǎifēnzhī","phần trăm","Thành ngữ"],
 ["棒","bàng","giỏi, tuyệt",""],
 ["包括","bāokuò","bao gồm","Động từ"],
 ["保护","bǎohù","bảo vệ","Động từ"],
 ["保证","bǎozhèng","đảm bảo","Động từ"],
 ["抱","bào","ôm","Động từ"],
 ["抱歉","bàoqiàn","xin lỗi","Động từ"],
 ["报名","bào míng","đăng ký","Động từ"],
 ["倍","bèi","lần (gấp)","Số từ"],
 ["本来","běnlái","vốn dĩ","Danh từ chỉ thời gian"],
 ["笨","bèn","ngu, đần",""],
 ["比如","bǐrú","ví dụ","Động từ"],
 ["毕业","bì yè","tốt nghiệp","Danh từ"],
 ["遍","biàn","lượt, lần","Động từ"],
 ["标准","biāozhǔn","tiêu chuẩn","Danh từ"],
 ["表格","biǎogé","biểu mẫu","Danh từ"],
 ["表扬","biǎoyáng","khen ngợi","Động từ"],
 ["饼干","bǐnggān","bánh quy","Danh từ"],
 ["并且","bìngqiě","hơn nữa","Liên từ"],
 ["博士","bóshì","tiến sĩ","Danh từ"],
 ["不得不","bùdébù","buộc phải","Phó từ"],
 ["不管","bùguǎn","bất kể","Liên từ"],
 ["不过","búguò","nhưng mà","Liên từ"],
 ["不仅","bùjǐn","không chỉ","Liên từ"],
 ["部分","bùfen","bộ phận, phần","Danh từ"],
 ["擦","cā","lau, chùi","Động từ"],
 ["猜","cāi","đoán","Động từ"],
 ["材料","cáiliào","vật liệu, tài liệu","Danh từ"],
 ["参观","cānguān","tham quan","Danh từ"],
 ["餐厅","cāntīng","nhà ăn","Danh từ"],
 ["厕所","cèsuǒ","nhà vệ sinh","Danh từ"],
 ["差不多","chàbuduō","gần như","Từ láy / Quán dụng ngữ"],
 ["长城","Chángchéng","Vạn Lý Trường Thành","Danh từ (Địa danh)"],
 ["长江","Chángjiāng","sông Trường Giang","Danh từ (Địa danh)"],
 ["尝","cháng","nếm","Động từ"],
 ["场","chǎng","sân, (lượng từ) trận","Lượng từ"],
 ["超过","chāoguò","vượt qua","Động từ"],
 ["吵","chǎo","ồn, cãi","Động từ"],
 ["成功","chénggōng","thành công","Tính từ"],
 ["成为","chéngwéi","trở thành","Động từ"],
 ["诚实","chéngshí","thành thật","Tính từ"],
 ["乘坐","chéngzuò","đi (phương tiện)","Động từ"],
 ["吃惊","chī jīng","kinh ngạc","Tính từ"],
 ["重新","chóngxīn","lại, từ đầu","Tính từ"],
 ["抽烟","chōu yān","hút thuốc","Động từ"],
 ["出差","chū chāi","đi công tác","Động từ"],
 ["出发","chūfā","xuất phát","Động từ"],
 ["出生","chūshēng","sinh ra","Động từ"],
 ["厨师","chúshī","đầu bếp","Danh từ"],
 ["传真","chuánzhēn","fax","Động từ"],
 ["窗户","chuānghu","cửa sổ","Danh từ"],
 ["词语","cíyǔ","từ ngữ","Danh từ"],
 ["从来","cónglái","từ trước đến nay","Phó từ"],
 ["粗心","cūxīn","bất cẩn","Tính từ"],
 ["存","cún","cất, gửi","Động từ"],
 ["错误","cuòwù","sai lầm","Danh từ"],
 ["答案","dá'àn","đáp án","Danh từ"],
 ["打扮","dǎban","trang điểm","Động từ"],
 ["打工","dǎ gōng","làm thêm","Động từ"],
 ["打印","dǎyìn","in","Động từ"],
 ["打折","dǎ zhé","giảm giá","Động từ"],
 ["打针","dǎ zhēn","tiêm","Động từ"],
 ["大概","dàgài","đại khái","Phó từ"],
 ["大使馆","dàshǐguǎn","đại sứ quán","Danh từ"],
 ["大约","dàyuē","khoảng","Phó từ"],
 ["代表","dàibiǎo","đại biểu","Danh từ"],
 ["代替","dàitì","thay thế","Động từ"],
 ["大夫","dàifu","bác sĩ","Danh từ"],
 ["当","dāng","khi, làm","Danh từ chỉ thời gian"],
 ["当时","dāngshí","lúc đó","Danh từ chỉ thời gian"],
 ["刀","dāo","dao","Danh từ"],
 ["导游","dǎoyóu","hướng dẫn viên","Danh từ"],
 ["到处","dàochù","khắp nơi","Phó từ"],
 ["到底","dàodǐ","rốt cuộc","Phó từ"],
 ["道歉","dào qiàn","xin lỗi","Động từ"],
 ["得意","déyì","đắc ý, hãnh diện","Động từ"],
 ["登记","dēngjì","đăng ký","Động từ"],
 ["等","děng","(trợ từ) vân vân","Trợ từ"],
 ["低","dī","thấp","Tính từ"],
 ["底","dǐ","đáy","Danh từ phương hướng"],
 ["地址","dìzhǐ","địa chỉ","Danh từ"],
 ["地球","dìqiú","trái đất","Danh từ"],
 ["掉","diào","rơi, mất",""],
 ["调查","diàochá","điều tra","Động từ / Danh từ"],
 ["丢","diū","mất, đánh mất",""],
 ["动作","dòngzuò","động tác","Danh từ"],
 ["堵车","dǔ chē","kẹt xe","Động từ"],
 ["肚子","dùzi","bụng","Danh từ"],
 ["短信","duǎnxìn","tin nhắn","Danh từ"],
 ["对话","duìhuà","hội thoại","Danh từ"],
 ["对面","duìmiàn","đối diện","Danh từ"],
 ["对于","duìyú","đối với","Giới từ"],
 ["吨","dūn","tấn","Số từ"],
 ["顿","dùn","(lượng từ) bữa","Lượng từ"],
 ["多余","duōyú","thừa, dư","Số từ"],
 ["而","ér","mà, và","Liên từ"],
 ["儿童","értóng","trẻ em","Danh từ"],
 ["发生","fāshēng","xảy ra","Động từ"],
 ["发展","fāzhǎn","phát triển","Động từ / Danh từ"],
 ["法律","fǎlǜ","pháp luật","Danh từ"],
 ["翻译","fānyì","dịch, phiên dịch","Động từ"],
 ["反对","fǎnduì","phản đối","Phó từ"],
 ["反映","fǎnyìng","phản ánh","Động từ"],
 ["方法","fāngfǎ","phương pháp","Danh từ"],
 ["方面","fāngmiàn","phương diện","Danh từ"],
 ["方向","fāngxiàng","hướng","Danh từ"],
 ["房东","fángdōng","chủ nhà","Danh từ"],
 ["放弃","fàngqì","từ bỏ","Động từ"],
 ["放暑假","fàng shǔjià","nghỉ hè","Từ láy / Quán dụng ngữ"],
 ["份","fèn","(lượng từ) phần","Lượng từ"],
 ["丰富","fēngfù","phong phú","Tính từ"],
 ["否则","fǒuzé","nếu không","Liên từ"],
 ["符合","fúhé","phù hợp","Động từ"],
 ["付款","fù kuǎn","thanh toán","Động từ"],
 ["复印","fùyìn","photocopy","Động từ"],
 ["复杂","fùzá","phức tạp","Tính từ"],
 ["负责","fùzé","chịu trách nhiệm","Động từ"],
 ["富","fù","giàu","Danh từ riêng"],
 ["父亲","fùqīn","cha","Danh từ"],
 ["改变","gǎibiàn","thay đổi","Động từ"],
 ["干","gàn","làm","Động từ"],
 ["干杯","gān bēi","nâng cốc","Danh từ"],
 ["赶","gǎn","đuổi kịp, vội","Động từ"],
 ["感动","gǎndòng","cảm động","Động từ"],
 ["感觉","gǎnjué","cảm giác","Danh từ"],
 ["感情","gǎnqíng","tình cảm","Danh từ"],
 ["感谢","gǎnxiè","cảm ơn","Động từ"],
 ["钢琴","gāngqín","đàn piano","Danh từ"],
 ["高速公路","gāosù gōnglù","cao tốc","Danh từ"],
 ["胳膊","gēbo","cánh tay","Danh từ"],
 ["各","gè","các, mỗi","Đại từ"],
 ["工程师","gōngchéngshī","kỹ sư","Danh từ"],
 ["工具","gōngjù","dụng cụ","Danh từ"],
 ["工资","gōngzī","lương","Động từ / Danh từ"],
 ["功夫","gōngfu","công phu, kung fu","Danh từ"],
 ["共同","gòngtóng","cùng nhau","Phó từ"],
 ["购物","gòu wù","mua sắm","Danh từ"],
 ["够","gòu","đủ",""],
 ["估计","gūjì","ước tính","Động từ"],
 ["鼓励","gǔlì","khuyến khích","Động từ"],
 ["故意","gùyì","cố ý","Phó từ"],
 ["顾客","gùkè","khách hàng","Danh từ riêng"],
 ["挂","guà","treo","Động từ"],
 ["管理","guǎnlǐ","quản lý","Động từ / Danh từ"],
 ["光","guāng","ánh sáng","Danh từ"],
 ["广播","guǎngbō","phát thanh","Động từ / Danh từ"],
 ["广告","guǎnggào","quảng cáo","Danh từ"],
 ["逛","guàng","dạo","Động từ"],
 ["规定","guīdìng","quy định","Danh từ"],
 ["国际","guójì","quốc tế","Danh từ"],
 ["国籍","guójí","quốc tịch","Danh từ"],
 ["果然","guǒrán","quả nhiên","Phó từ"],
 ["过程","guòchéng","quá trình","Danh từ"],
 ["海洋","hǎiyáng","đại dương","Danh từ (Địa danh)"],
 ["害羞","hàixiū","xấu hổ","Tính từ"],
 ["寒冷","hánlěng","lạnh giá","Tính từ"],
 ["汗","hàn","mồ hôi",""],
 ["航班","hángbān","chuyến bay","Danh từ"],
 ["好处","hǎochu","lợi ích","Phó từ"],
 ["好像","hǎoxiàng","hình như","Động từ"],
 ["号码","hàomǎ","số (điện thoại)","Danh từ"],
 ["合格","hégé","đạt yêu cầu","Danh từ"],
 ["合适","héshì","phù hợp","Tính từ"],
 ["盒子","hézi","hộp","Danh từ"],
 ["后悔","hòuhuǐ","hối hận","Động từ"],
 ["厚","hòu","dày","Tính từ"],
 ["互相","hùxiāng","lẫn nhau","Phó từ"],
 ["怀疑","huáiyí","nghi ngờ","Động từ"],
 ["回忆","huíyì","hồi tưởng","Động từ"],
 ["活动","huódòng","hoạt động","Động từ / Danh từ"],
 ["活泼","huópo","hoạt bát","Tính từ"],
 ["火","huǒ","lửa","Danh từ"],
 ["获得","huòdé","đạt được","Động từ"],
 ["积极","jījí","tích cực","Tính từ / Phó từ"],
 ["积累","jīlěi","tích lũy","Động từ"],
 ["基础","jīchǔ","cơ sở","Danh từ"],
 ["激动","jīdòng","xúc động","Tính từ"],
 ["及时","jíshí","kịp thời","Liên từ"],
 ["即使","jíshǐ","cho dù","Liên từ"],
 ["计划","jìhuà","kế hoạch","Danh từ"],
 ["记者","jìzhě","nhà báo","Danh từ"],
 ["技术","jìshù","kỹ thuật","Danh từ"],
 ["既然","jìrán","đã, vì đã","Liên từ"],
 ["继续","jìxù","tiếp tục","Động từ"],
 ["加班","jiā bān","làm thêm giờ","Động từ"],
 ["加油站","jiāyóuzhàn","cây xăng","Danh từ (Tổ chức)"],
 ["家具","jiājù","nội thất","Danh từ"],
 ["假","jiǎ","giả","Danh từ"],
 ["价格","jiàgé","giá cả","Danh từ"],
 ["坚持","jiānchí","kiên trì","Động từ"],
 ["减肥","jiǎn féi","giảm cân","Động từ"],
 ["减少","jiǎnshǎo","giảm bớt","Động từ"],
 ["建议","jiànyì","kiến nghị, đề xuất","Danh từ"],
 ["将来","jiānglái","tương lai","Danh từ chỉ thời gian"],
 ["奖金","jiǎngjīn","tiền thưởng","Danh từ"],
 ["降低","jiàngdī","hạ thấp","Động từ"],
 ["交","jiāo","giao, nộp","Động từ"],
 ["交流","jiāolíu","giao lưu","Danh từ"],
 ["交通","jiāotōng","giao thông","Danh từ"],
 ["骄傲","jiāo'ào","kiêu ngạo, tự hào","Tính từ"],
 ["教育","jiàoyù","giáo dục","Động từ / Danh từ"],
 ["接受","jiēshòu","tiếp nhận","Động từ"],
 ["结果","jiéguǒ","kết quả","Danh từ"],
 ["解释","jiěshì","giải thích","Động từ"],
 ["尽管","jǐnguǎn","mặc dù","Liên từ"],
 ["紧张","jǐnzhāng","căng thẳng","Tính từ"],
 ["进行","jìnxíng","tiến hành","Động từ"],
 ["禁止","jìnzhǐ","cấm","Động từ"],
 ["精彩","jīngcǎi","tinh tế, hấp dẫn","Danh từ"],
 ["精神","jīngshén","tinh thần","Danh từ"],
 ["经济","jīngjì","kinh tế","Danh từ"],
 ["经历","jīnglì","kinh nghiệm, trải nghiệm","Danh từ"],
 ["经验","jīngyàn","kinh nghiệm","Danh từ"],
 ["景色","jǐngsè","cảnh sắc","Danh từ"],
 ["警察","jǐngchá","cảnh sát","Động từ"],
 ["竞争","jìngzhēng","cạnh tranh","Động từ / Danh từ"],
 ["竟然","jìngrán","bất ngờ","Phó từ"],
 ["镜子","jìngzi","gương","Danh từ"],
 ["究竟","jiūjìng","rốt cuộc","Phó từ"],
 ["举","jǔ","giơ, nâng","Động từ"],
 ["拒绝","jùjué","từ chối","Động từ"],
 ["距离","jùlí","khoảng cách","Danh từ"],
 ["聚会","jùhuì","họp mặt","Danh từ"],
 ["开玩笑","kāi wánxiào","đùa","Động từ"],
 ["看法","kànfǎ","quan điểm","Động từ"],
 ["考虑","kǎolǜ","cân nhắc","Động từ"],
 ["科学","kēxué","khoa học","Danh từ"],
 ["咳嗽","késou","ho","Động từ"],
 ["可怜","kělián","đáng thương","Động từ"],
 ["可是","kěshì","nhưng","Liên từ"],
 ["客厅","kètīng","phòng khách","Danh từ"],
 ["肯定","kěndìng","chắc chắn","Động từ"],
 ["空","kōng","trống","Danh từ"],
 ["恐怕","kǒngpà","e rằng","Phó từ"],
 ["苦","kǔ","đắng, khổ","Tính từ"],
 ["矿泉水","kuàngquánshuǐ","nước khoáng","Danh từ"],
 ["困","kùn","buồn ngủ","Động từ"],
 ["困难","kùnnan","khó khăn","Tính từ / Danh từ"],
 ["拉","lā","kéo","Động từ"],
 ["垃圾桶","lājītǒng","thùng rác","Danh từ"],
 ["来不及","láibují","không kịp","Động từ"],
 ["来得及","láidejí","kịp","Động từ"],
 ["老虎","lǎohǔ","con hổ","Danh từ riêng"],
 ["浪费","làngfèi","lãng phí","Danh từ"],
 ["浪漫","làngmàn","lãng mạn","Tính từ"],
 ["朗读","lǎngdú","đọc to","Động từ"],
 ["劳驾","láojià","xin phiền","Danh từ riêng"],
 ["冷静","lěngjìng","bình tĩnh","Tính từ"],
 ["理发","lǐ fà","cắt tóc","Động từ"],
 ["理解","lǐjiě","lý giải, hiểu","Động từ"],
 ["理想","lǐxiǎng","lý tưởng","Danh từ"],
 ["力气","lìqi","sức lực","Danh từ"],
 ["厉害","lìhai","ghê gớm, giỏi","Tính từ"],
 ["例如","lìrú","ví dụ như","Động từ"],
 ["联系","liánxì","liên hệ","Danh từ"],
 ["凉快","liángkuai","mát mẻ","Tính từ"],
 ["零钱","língqián","tiền lẻ","Danh từ"],
 ["另外","lìngwài","ngoài ra","Liên từ"],
 ["流利","liúlì","lưu loát","Danh từ"],
 ["流行","liúxíng","thịnh hành","Động từ"],
 ["律师","lǜshī","luật sư","Danh từ"],
 ["乱","luàn","lộn xộn","Phó từ"],
 ["落后","luòhòu","lạc hậu","Tính từ"],
 ["麻烦","máfan","phiền phức","Tính từ / Danh từ"],
 ["马虎","mǎhu","cẩu thả","Danh từ riêng"],
 ["满","mǎn","đầy","Tính từ"],
 ["毛","máo","lông, hào (tiền)","Danh từ riêng"],
 ["毛巾","máojīn","khăn mặt","Danh từ riêng"],
 ["美丽","měilì","xinh đẹp","Danh từ (Địa danh)"],
 ["梦","mèng","giấc mơ","Danh từ"],
 ["迷路","mí lù","lạc đường","Danh từ"],
 ["密码","mìmǎ","mật khẩu","Danh từ"],
 ["免费","miǎnfèi","miễn phí","Động từ / Danh từ"],
 ["秒","miǎo","giây","Số từ"],
 ["民族","mínzú","dân tộc","Danh từ"],
 ["母亲","mǔqīn","mẹ","Danh từ"],
 ["目的","mùdì","mục đích","Danh từ"],
 ["目前","mùqián","hiện tại","Danh từ chỉ thời gian"],
 ["内","nèi","trong, nội","Danh từ"],
 ["内容","nèiróng","nội dung","Danh từ"],
 ["耐心","nàixīn","kiên nhẫn","Tính từ"],
 ["难道","nándào","chẳng lẽ","Phó từ"],
 ["难受","nánshòu","khó chịu","Động từ"],
 ["能力","nénglì","năng lực","Danh từ"],
 ["年龄","niánlíng","tuổi","Danh từ"],
 ["弄","nòng","làm","Động từ"],
 ["暖和","nuǎnhuo","ấm áp","Tính từ"],
 ["偶尔","ǒu'ěr","thỉnh thoảng","Phó từ"],
 ["排队","pái duì","xếp hàng","Danh từ"],
 ["排列","páiliè","sắp xếp","Động từ"],
 ["判断","pànduàn","phán đoán","Động từ"],
 ["陪","péi","đi cùng","Động từ"],
 ["批评","pīpíng","phê bình","Động từ"],
 ["皮肤","pífū","da","Danh từ"],
 ["脾气","píqi","tính khí","Danh từ"],
 ["篇","piān","(lượng từ) bài","Lượng từ"],
 ["骗","piàn","lừa","Động từ"],
 ["乒乓球","pīngpāngqiú","bóng bàn","Danh từ"],
 ["平时","píngshí","ngày thường","Danh từ chỉ thời gian"],
 ["破","pò","rách, vỡ","Động từ"],
 ["葡萄","pútao","nho","Danh từ"],
 ["普遍","pǔbiàn","phổ biến","Tính từ / Phó từ"],
 ["其次","qící","thứ hai","Đại từ"],
 ["其中","qízhōng","trong đó","Đại từ"],
 ["气候","qìhòu","khí hậu","Danh từ"],
 ["千万","qiānwàn","nhất định (phải/đừng)","Số từ"],
 ["签证","qiānzhèng","visa","Động từ"],
 ["墙","qiáng","tường","Danh từ"],
 ["桥","qiáo","cầu","Danh từ"],
 ["巧克力","qiǎokèlì","sô cô la","Danh từ riêng"],
 ["亲戚","qīnqi","họ hàng","Danh từ"],
 ["轻","qīng","nhẹ","Tính từ"],
 ["轻松","qīngsōng","nhẹ nhàng","Tính từ"],
 ["情况","qíngkuàng","tình hình","Danh từ"],
 ["穷","qióng","nghèo","Tính từ"],
 ["区别","qūbié","sự khác nhau","Danh từ"],
 ["取","qǔ","lấy","Động từ"],
 ["全部","quánbù","toàn bộ","Danh từ"],
 ["缺点","quēdiǎn","khuyết điểm","Danh từ"],
 ["缺少","quēshǎo","thiếu","Động từ"],
 ["确实","quèshí","thực sự","Tính từ / Phó từ"],
 ["然而","rán'ér","tuy nhiên","Liên từ"],
 ["热闹","rènao","náo nhiệt","Tính từ"],
 ["任何","rènhé","bất kỳ","Đại từ"],
 ["任务","rènwu","nhiệm vụ","Danh từ"],
 ["仍然","réngrán","vẫn","Phó từ"],
 ["日记","rìjì","nhật ký","Danh từ"],
 ["入口","rùkǒu","lối vào","Danh từ (Địa danh)"],
 ["散步","sàn bù","đi dạo","Danh từ"],
 ["森林","sēnlín","rừng","Danh từ"],
 ["沙发","shāfā","sofa","Danh từ (Khác)"],
 ["商量","shāngliang","bàn bạc","Danh từ"],
 ["伤心","shāng xīn","đau lòng","Danh từ"],
 ["稍微","shāowēi","hơi, một chút","Phó từ"],
 ["社会","shèhuì","xã hội","Danh từ"],
 ["申请","shēnqǐng","xin, đăng ký","Động từ"],
 ["深","shēn","sâu","Tính từ"],
 ["甚至","shènzhì","thậm chí","Phó từ"],
 ["生活","shēnghuó","cuộc sống","Động từ / Danh từ"],
 ["生命","shēngmìng","sinh mệnh","Động từ / Danh từ"],
 ["生意","shēngyi","kinh doanh","Động từ"],
 ["省","shěng","tỉnh, tiết kiệm","Danh từ"],
 ["剩","shèng","còn thừa","Động từ"],
 ["失败","shībài","thất bại","Động từ"],
 ["失望","shīwàng","thất vọng","Động từ"],
 ["师傅","shīfu","sư phụ, thợ","Danh từ riêng"],
 ["十分","shífēn","rất, vô cùng","Số từ"],
 ["实际","shíjì","thực tế","Danh từ"],
 ["实在","shízài","thực sự","Động từ"],
 ["食品","shípǐn","thực phẩm","Danh từ"],
 ["使","shǐ","sử, khiến","Động từ"],
 ["使用","shǐyòng","sử dụng","Động từ"],
 ["适合","shìhé","thích hợp","Động từ"],
 ["适应","shìyìng","thích ứng","Động từ"],
 ["收","shōu","thu, nhận","Động từ"],
 ["收入","shōurù","thu nhập","Động từ"],
 ["收拾","shōushi","thu dọn","Động từ"],
 ["首都","shǒudū","thủ đô","Phó từ"],
 ["首先","shǒuxiān","trước hết","Phó từ"],
 ["受到","shòudào","nhận được","Động từ"],
 ["受不了","shòubuliǎo","chịu không nổi","Từ láy / Quán dụng ngữ"],
 ["输","shū","thua","Động từ"],
 ["熟悉","shúxī","quen thuộc","Động từ"],
 ["数量","shùliàng","số lượng","Danh từ"],
 ["数字","shùzì","số, chữ số","Danh từ"],
 ["帅","shuài","đẹp trai","Danh từ riêng"],
 ["顺便","shùnbiàn","tiện thể","Tính từ / Phó từ"],
 ["顺利","shùnlì","thuận lợi","Tính từ / Phó từ"],
 ["顺序","shùnxù","thứ tự","Danh từ"],
 ["说明","shuōmíng","thuyết minh","Động từ"],
 ["硕士","shuòshì","thạc sĩ","Danh từ"],
 ["死","sǐ","chết","Động từ"],
 ["速度","sùdù","tốc độ","Danh từ"],
 ["塑料袋","sùliàodài","túi nilon","Danh từ"],
 ["酸","suān","chua","Danh từ"],
 ["随便","suíbiàn","tùy ý","Phó từ"],
 ["随着","suízhe","theo, cùng với","Giới từ"],
 ["孙子","sūnzi","cháu trai (nội)","Danh từ riêng"],
 ["所有","suǒyǒu","tất cả","Tính từ"],
 ["台","tái","(lượng từ) chiếc (máy)","Lượng từ"],
 ["态度","tàidu","thái độ","Danh từ"],
 ["谈","tán","nói chuyện","Động từ"],
 ["弹钢琴","tán gāngqín","chơi đàn piano","Danh từ"],
 ["汤","tāng","canh, súp","Danh từ"],
 ["糖","táng","đường, kẹo",""],
 ["躺","tǎng","nằm","Động từ"],
 ["趟","tàng","(lượng từ) chuyến",""],
 ["讨论","tǎolùn","thảo luận","Động từ"],
 ["讨厌","tǎoyàn","ghét","Động từ"],
 ["特点","tèdiǎn","đặc điểm","Danh từ"],
 ["提","tí","nâng, đề cập","Động từ"],
 ["提供","tígōng","cung cấp","Động từ"],
 ["提前","tíqián","trước hạn","Động từ"],
 ["提醒","tíxǐng","nhắc nhở","Động từ"],
 ["填空","tián kòng","điền vào chỗ trống","Động từ"],
 ["条件","tiáojiàn","điều kiện","Danh từ"],
 ["停","tíng","dừng","Động từ"],
 ["挺","tǐng","khá, rất","Phó từ"],
 ["通过","tōngguò","thông qua","Giới từ"],
 ["通知","tōngzhī","thông báo","Động từ"],
 ["同情","tóngqíng","đồng tình","Danh từ"],
 ["同时","tóngshí","đồng thời","Liên từ"],
 ["推","tuī","đẩy","Động từ"],
 ["推迟","tuīchí","hoãn lại","Động từ"],
 ["脱","tuō","cởi","Động từ"],
 ["袜子","wàzi","tất, vớ","Danh từ"],
 ["完全","wánquán","hoàn toàn","Tính từ / Phó từ"],
 ["网球","wǎngqiú","quần vợt","Danh từ"],
 ["网站","wǎngzhàn","trang web","Danh từ"],
 ["往","wǎng","về phía",""],
 ["往往","wǎngwǎng","thường thường","Danh từ chỉ thời gian"],
 ["危险","wēixiǎn","nguy hiểm","Tính từ / Danh từ"],
 ["卫生间","wèishēngjiān","nhà vệ sinh","Danh từ"],
 ["温度","wēndù","nhiệt độ","Danh từ"],
 ["文章","wénzhāng","bài viết","Danh từ"],
 ["污染","wūrǎn","ô nhiễm","Động từ / Danh từ"],
 ["无","wú","không","Động từ"],
 ["无聊","wúliáo","chán, buồn","Tính từ"],
 ["无论","wúlùn","bất luận","Liên từ"],
 ["误会","wùhuì","hiểu lầm","Danh từ"],
 ["西红柿","xīhóngshì","cà chua","Danh từ riêng"],
 ["吸引","xīyǐn","thu hút","Động từ"],
 ["咸","xián","mặn","Danh từ (Địa danh)"],
 ["现代","xiàndài","hiện đại","Danh từ chỉ thời gian"],
 ["现象","xiànxiàng","hiện tượng","Danh từ"],
 ["限制","xiànzhì","hạn chế","Động từ"],
 ["相反","xiāngfǎn","ngược lại","Động từ"],
 ["相同","xiāngtóng","giống nhau","Phó từ"],
 ["详细","xiángxì","chi tiết","Tính từ / Phó từ"],
 ["响","xiǎng","vang, kêu",""],
 ["橡皮","xiàngpí","cục tẩy","Danh từ"],
 ["消息","xiāoxi","tin tức","Danh từ"],
 ["小吃","xiǎochī","đồ ăn vặt","Danh từ"],
 ["小伙子","xiǎohuǒzi","chàng trai","Danh từ"],
 ["小说","xiǎoshuō","tiểu thuyết","Danh từ"],
 ["效果","xiàoguǒ","hiệu quả","Danh từ"],
 ["笑话","xiàohua","truyện cười","Danh từ"],
 ["心情","xīnqíng","tâm trạng","Danh từ"],
 ["辛苦","xīnkǔ","vất vả","Tính từ"],
 ["信封","xìnfēng","phong bì","Động từ"],
 ["信息","xìnxī","thông tin","Danh từ"],
 ["信心","xìnxīn","lòng tin","Danh từ"],
 ["兴奋","xīngfèn","phấn khích","Động từ"],
 ["行","xíng","được",""],
 ["幸福","xìngfú","hạnh phúc","Tính từ"],
 ["性别","xìngbié","giới tính","Danh từ"],
 ["性格","xìnggé","tính cách","Danh từ"],
 ["修理","xiūlǐ","sửa chữa","Động từ"],
 ["许多","xǔduō","nhiều","Số từ"],
 ["学期","xuéqī","học kỳ","Danh từ"],
 ["压力","yālì","áp lực","Danh từ"],
 ["牙膏","yágāo","kem đánh răng","Danh từ"],
 ["亚洲","Yàzhōu","châu Á","Danh từ (Địa danh)"],
 ["严格","yángé","nghiêm ngặt","Tính từ / Phó từ"],
 ["严重","yánzhòng","nghiêm trọng","Tính từ"],
 ["研究","yánjiū","nghiên cứu","Động từ / Danh từ"],
 ["演出","yǎnchū","biểu diễn","Động từ"],
 ["演员","yǎnyuán","diễn viên","Danh từ"],
 ["阳光","yángguāng","ánh nắng","Danh từ riêng"],
 ["养成","yǎngchéng","hình thành (thói quen)","Động từ"],
 ["样子","yàngzi","kiểu dáng","Danh từ"],
 ["邀请","yāoqǐng","mời","Động từ"],
 ["钥匙","yàoshi","chìa khóa","Danh từ"],
 ["也许","yěxǔ","có lẽ","Phó từ"],
 ["叶子","yèzi","lá cây","Danh từ riêng"],
 ["一辈子","yí bèizi","cả đời","Số từ"],
 ["意见","yìjiàn","ý kiến","Danh từ"],
 ["意思","yìsi","ý nghĩa","Danh từ"],
 ["因此","yīncǐ","vì vậy","Liên từ"],
 ["印象","yìnxiàng","ấn tượng","Danh từ"],
 ["赢","yíng","thắng","Động từ"],
 ["应聘","yìngpìn","ứng tuyển","Động từ"],
 ["勇敢","yǒnggǎn","dũng cảm","Tính từ"],
 ["永远","yǒngyuǎn","mãi mãi","Phó từ"],
 ["优点","yōudiǎn","ưu điểm","Danh từ"],
 ["优秀","yōuxiù","xuất sắc","Tính từ"],
 ["尤其","yóuqí","nhất là","Phó từ"],
 ["由","yóu","do, bởi","Giới từ"],
 ["由于","yóuyú","do, bởi vì","Liên từ"],
 ["有趣","yǒuqù","thú vị","Tính từ"],
 ["友好","yǒuhǎo","hữu hảo","Tính từ"],
 ["友谊","yǒuyì","tình bạn","Danh từ riêng"],
 ["于是","yúshì","vì thế","Liên từ"],
 ["与","yǔ","và, với","Giới từ"],
 ["语法","yǔfǎ","ngữ pháp","Danh từ"],
 ["语言","yǔyán","ngôn ngữ","Danh từ"],
 ["预习","yùxí","chuẩn bị bài","Động từ"],
 ["原来","yuánlái","hóa ra","Phó từ"],
 ["原谅","yuánliàng","tha thứ","Danh từ riêng"],
 ["原因","yuányīn","nguyên nhân","Danh từ"],
 ["约会","yuēhuì","hẹn hò","Danh từ"],
 ["阅读","yuèdú","đọc","Động từ"],
 ["云","yún","mây","Danh từ (Địa danh)"],
 ["允许","yǔnxǔ","cho phép","Động từ"],
 ["杂志","zázhì","tạp chí","Danh từ"],
 ["咱们","zánmen","chúng mình","Đại từ"],
 ["暂时","zànshí","tạm thời","Phó từ"],
 ["脏","zāng","bẩn","Tính từ"],
 ["责任","zérèn","trách nhiệm","Danh từ"],
 ["增加","zēngjiā","tăng thêm","Động từ"],
 ["占","zhàn","chiếm","Động từ"],
 ["招聘","zhāopìn","tuyển dụng","Động từ"],
 ["真正","zhēnzhèng","thực sự","Phó từ"],
 ["整理","zhěnglǐ","chỉnh lý","Danh từ"],
 ["正常","zhèngcháng","bình thường","Phó từ"],
 ["正好","zhènghǎo","vừa hay","Tính từ"],
 ["正确","zhèngquè","chính xác","Tính từ / Phó từ"],
 ["正式","zhèngshì","chính thức","Tính từ / Phó từ"],
 ["证明","zhèngmíng","chứng minh","Danh từ"],
 ["之","zhī","của (văn viết)","Trợ từ"],
 ["支持","zhīchí","ủng hộ","Động từ"],
 ["知识","zhīshi","kiến thức","Động từ"],
 ["值得","zhíde","đáng giá","Động từ"],
 ["直接","zhíjiē","trực tiếp","Tính từ / Phó từ"],
 ["植物","zhíwù","thực vật","Danh từ"],
 ["职业","zhíyè","nghề nghiệp","Danh từ"],
 ["只好","zhǐhǎo","đành phải","Phó từ"],
 ["只要","zhǐyào","chỉ cần","Liên từ"],
 ["指","zhǐ","chỉ","Danh từ"],
 ["质量","zhìliàng","chất lượng","Danh từ"],
 ["至少","zhìshǎo","ít nhất","Phó từ"],
 ["制度","zhìdù","chế độ","Danh từ"],
 ["中文","Zhōngwén","tiếng Trung","Danh từ (Khác)"],
 ["重","zhòng","nặng","Tính từ"],
 ["重点","zhòngdiǎn","trọng điểm","Danh từ"],
 ["重视","zhòngshì","coi trọng","Động từ"],
 ["周围","zhōuwéi","xung quanh","Danh từ phương hướng"],
 ["猪","zhū","con lợn","Danh từ"],
 ["逐渐","zhújiàn","dần dần","Phó từ"],
 ["祝","zhù","chúc","Động từ"],
 ["祝贺","zhùhè","chúc mừng","Danh từ riêng"],
 ["著名","zhùmíng","nổi tiếng","Tính từ"],
 ["专门","zhuānmén","chuyên","Danh từ"],
 ["专业","zhuānyè","chuyên ngành","Danh từ"],
 ["转","zhuǎn","quay, rẽ","Động từ"],
 ["赚","zhuàn","kiếm (tiền)","Động từ"],
 ["准确","zhǔnquè","chính xác","Tính từ"],
 ["仔细","zǐxì","cẩn thận","Tính từ / Phó từ"],
 ["自然","zìrán","tự nhiên","Phó từ"],
 ["总结","zǒngjié","tổng kết","Danh từ"],
 ["租","zū","thuê","Động từ"],
 ["最好","zuìhǎo","tốt nhất","Tính từ"],
 ["尊重","zūnzhòng","tôn trọng","Tính từ"],
 ["座","zuò","(lượng từ) tòa","Lượng từ"],
 ["座位","zuòwèi","chỗ ngồi","Danh từ"],
 ["做生意","zuò shēngyi","làm kinh doanh","Động từ"]
];
