// ============================================================
// QUYỂN 1 - Giáo trình Hán ngữ Tập 1 - Quyển 1 (HSK 1)
// Format: [Hán tự, Pinyin, Nghĩa, Từ loại, Số bài, Tên bài]
// ============================================================

const HSK1_LESSONS = {
  1:  "你好 (Xin chào)",
  2:  "汉语不太难 (Tiếng Hán không khó lắm)",
  3:  "明天见 (Ngày mai gặp)",
  4:  "你去哪儿 (Bạn đi đâu đấy)",
  5:  "这是王老师 (Đây là thầy giáo Vương)",
  6:  "我学习汉语 (Tôi học tiếng Hán)",
  7:  "你吃什么 (Bạn ăn cái gì)",
  8:  "苹果一斤多少钱 (Một cân táo bao nhiêu tiền)",
  9:  "我换人民币 (Tôi đổi nhân dân tệ)",
  10: "他住哪儿 (Ông ấy ở đâu)",
  11: "我们都是留学生 (Chúng tôi đều là lưu học sinh)",
  12: "你在哪儿学习 (Bạn học ở đâu)",
  13: "这不是中药 (Cái này không phải thuốc đông y)",
  14: "你的车是新的还是旧的 (Xe của bạn mới hay cũ)",
  15: "你公司有多少职员 (Công ty của bạn có bao nhiêu nhân viên)"
};

const HSK1 = [
  // ──────── Bài 1: 你好 (Xin chào) ────────
  ["你","nǐ","anh, chị, bạn... (đại từ chỉ người ngôi thứ hai số ít)","Đại từ",1,"你好 (Xin chào)"],
  ["好","hǎo","tốt, dùng để chào","Tính từ",1,"你好 (Xin chào)"],
  ["一","yī","một","Số từ",1,"你好 (Xin chào)"],
  ["五","wǔ","năm","Số từ",1,"你好 (Xin chào)"],
  ["八","bā","tám","Số từ",1,"你好 (Xin chào)"],
  ["大","dà","lớn","Tính từ",1,"你好 (Xin chào)"],
  ["不","bù","không","Phó từ",1,"你好 (Xin chào)"],
  ["口","kǒu","(cái) miệng","Danh từ",1,"你好 (Xin chào)"],
  ["白","bái","trắng","Tính từ",1,"你好 (Xin chào)"],
  ["女","nǚ","nữ","Danh từ",1,"你好 (Xin chào)"],
  ["马","mǎ","(con) ngựa","Danh từ",1,"你好 (Xin chào)"],

  // ──────── Bài 2: 汉语不太难 (Tiếng Hán không khó lắm) ────────
  ["忙","máng","bận","Tính từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["吗","ma","(trợ từ nghi vấn)","Trợ từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["很","hěn","rất","Phó từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["汉语","Hànyǔ","tiếng Hán, tiếng Hoa","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["难","nán","khó","Tính từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["太","tài","quá, lắm","Phó từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["爸爸","bàba","ba, bố","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["妈妈","māma","mẹ, má","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["他","tā","anh ấy, ông ấy, nó...","Đại từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["她","tā","chị ấy, cô ấy, bà ấy...","Đại từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["男","nán","nam, con trai","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["哥哥","gēge","anh","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["弟弟","dìdi","em trai","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],
  ["妹妹","mèimei","em gái","Danh từ",2,"汉语不太难 (Tiếng Hán không khó lắm)"],

  // ──────── Bài 3: 明天见 (Ngày mai gặp) ────────
  ["学","xué","học","Động từ",3,"明天见 (Ngày mai gặp)"],
  ["英语","Yīngyǔ","tiếng Anh","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["阿拉伯语","Ālābóyǔ","tiếng Ả Rập","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["德语","Déyǔ","tiếng Đức","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["俄语","Éyǔ","tiếng Nga","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["法语","Fǎyǔ","tiếng Pháp","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["韩国语","Hánguóyǔ","tiếng Hàn","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["日语","Rìyǔ","tiếng Nhật","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["西班牙语","Xībānyáyǔ","tiếng Tây Ban Nha","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["对","duì","đúng, phải","Tính từ",3,"明天见 (Ngày mai gặp)"],
  ["明天","míngtiān","ngày mai","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["见","jiàn","gặp","Động từ",3,"明天见 (Ngày mai gặp)"],
  ["去","qù","đi","Động từ",3,"明天见 (Ngày mai gặp)"],
  ["邮局","yóujú","bưu điện","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["寄","jì","gửi","Động từ",3,"明天见 (Ngày mai gặp)"],
  ["信","xìn","thư","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["银行","yínháng","ngân hàng","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["取","qǔ","nhận, lấy, rút","Động từ",3,"明天见 (Ngày mai gặp)"],
  ["钱","qián","tiền","Danh từ",3,"明天见 (Ngày mai gặp)"],
  ["六","liù","sáu","Số từ",3,"明天见 (Ngày mai gặp)"],
  ["七","qī","bảy","Số từ",3,"明天见 (Ngày mai gặp)"],
  ["九","jiǔ","chín","Số từ",3,"明天见 (Ngày mai gặp)"],
  ["北京","Běijīng","Bắc Kinh, thủ đô của Trung Quốc","Danh từ riêng",3,"明天见 (Ngày mai gặp)"],

  // ──────── Bài 4: 你去哪儿 (Bạn đi đâu đấy) ────────
  ["今天","jīntiān","hôm nay","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["天","tiān","ngày","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["昨天","zuótiān","hôm qua","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期","xīngqī","tuần, thứ","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期一","xīngqīyī","thứ hai","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期二","xīngqī'èr","thứ ba","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期三","xīngqīsān","thứ tư","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期四","xīngqīsì","thứ năm","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期五","xīngqīwǔ","thứ sáu","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期六","xīngqīliù","thứ bảy","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["星期天","xīngqītiān","chủ nhật","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["几","jǐ","mấy, vài","Đại từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["二","èr","hai","Số từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["三","sān","ba","Số từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["四","sì","bốn","Số từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["哪儿","nǎr","ở đâu","Đại từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["那儿","nàr","ở đấy, ở kia","Đại từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["我","wǒ","tôi, ta... (đại từ chỉ người ngôi thứ nhất số ít)","Đại từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["回","huí","về, trở về","Động từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["学校","xuéxiào","trường, trường học","Danh từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["再见","zàijiàn","tạm biệt","Động từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["对不起","duì bu qǐ","xin lỗi","Cụm từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["没关系","méi guānxi","không hề chi, không sao","Cụm từ",4,"你去哪儿 (Bạn đi đâu đấy)"],
  ["天安门","Tiān'ānmén","Thiên An Môn","Danh từ riêng",4,"你去哪儿 (Bạn đi đâu đấy)"],

  // ──────── Bài 5: 这是王老师 (Đây là thầy giáo Vương) ────────
  ["这","zhè","này, đây","Đại từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["是","shì","là, phải, vâng","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["老师","lǎoshī","thầy, cô giáo","Danh từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["您","nín","ngài, ông, bà","Đại từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["请","qǐng","mời","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["进","jìn","vào","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["坐","zuò","ngồi","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["喝","hē","uống","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["茶","chá","trà","Danh từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["谢谢","xièxie","cảm ơn","Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["不客气","bú kèqi","đừng khách sáo","Cụm từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["客气","kèqi","khách sáo","Tính từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["工作","gōngzuò","công việc, công tác","Danh từ/Động từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["身体","shēntǐ","thân thể","Danh từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["十","shí","mười","Số từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["日","rì","ngày","Danh từ",5,"这是王老师 (Đây là thầy giáo Vương)"],
  ["王","Wáng","họ Vương","Danh từ riêng",5,"这是王老师 (Đây là thầy giáo Vương)"],

  // ──────── Bài 6: 我学习汉语 (Tôi học tiếng Hán) ────────
  ["请问","qǐngwèn","xin hỏi","Động từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["问","wèn","hỏi","Động từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["贵姓","guìxìng","quí tính (họ của ngài)","Cụm từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["姓","xìng","họ","Động từ/Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["叫","jiào","gọi, tên là","Động từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["名字","míngzi","tên","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["哪","nǎ","nào","Đại từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["国","guó","nước, quốc gia","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["中国","Zhōngguó","Trung Quốc","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["德国","Déguó","nước Đức","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["俄国","Éguó","nước Nga","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["法国","Fǎguó","nước Pháp","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["韩国","Hánguó","Hàn Quốc","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["美国","Měiguó","nước Mỹ","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["日本","Rìběn","Nhật Bản","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["英国","Yīngguó","nước Anh","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["人","rén","người","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["学习","xuéxí","học tập","Động từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["汉字","Hànzì","chữ Hán","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["发音","fāyīn","phát âm","Danh từ/Động từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["什么","shénme","gì, cái gì","Đại từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["书","shū","sách","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["谁","shéi","ai","Đại từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["的","de","(trợ từ cấu trúc)","Trợ từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["那","nà","kia, ấy","Đại từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["杂志","zázhì","tạp chí","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["中文","Zhōngwén","Trung văn, tiếng Trung","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["阿拉伯文","Ālābówén","tiếng Ả Rập","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["德文","Déwén","tiếng Đức","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["俄文","Éwén","Nga văn, tiếng Nga","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["法文","Fǎwén","Pháp văn, tiếng Pháp","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["韩文","Hánwén","tiếng Hàn","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["日文","Rìwén","tiếng Nhật","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["西班牙文","Xībānyáwén","tiếng Tây Ban Nha","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["英文","Yīngwén","Anh văn, tiếng Anh","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["朋友","péngyou","bạn","Danh từ",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["麦克","Màikè","Mike","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],
  ["张东","Zhāng Dōng","Trương Đông","Danh từ riêng",6,"我学习汉语 (Tôi học tiếng Hán)"],

  // ──────── Bài 7: 你吃什么 (Bạn ăn cái gì) ────────
  ["中午","zhōngwǔ","buổi trưa","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["吃","chī","ăn","Động từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["饭","fàn","cơm","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["食堂","shítáng","nhà ăn","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["馒头","mántou","bánh màn thầu","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["米饭","mǐfàn","cơm","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["米","mǐ","gạo","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["要","yào","muốn, cần, phải","Động từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["个","gè","cái (lượng từ)","Lượng từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["碗","wǎn","chén, bát","Lượng từ/Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["鸡蛋","jīdàn","trứng gà","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["鸡","jī","gà","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["蛋","dàn","trứng","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["汤","tāng","canh, xúp","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["啤酒","píjiǔ","bia","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["酒","jiǔ","rượu","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["这些","zhèxiē","những... này","Đại từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["些","xiē","một vài","Lượng từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["一些","yì xiē","vài, những","Lượng từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["那些","nàxiē","những... kia","Đại từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["饺子","jiǎozi","há cảo, bánh chẻo, sủi cảo","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["包子","bāozi","bánh bao","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["面条","miàntiáo","mì sợi","Danh từ",7,"你吃什么 (Bạn ăn cái gì)"],
  ["玛丽","Mǎlì","Mary","Danh từ riêng",7,"你吃什么 (Bạn ăn cái gì)"],

  // ──────── Bài 8: 苹果一斤多少钱 (Một cân táo bao nhiêu tiền) ────────
  ["买","mǎi","mua","Động từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["水果","shuǐguǒ","trái cây","Danh từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["苹果","píngguǒ","táo","Danh từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["斤","jīn","cân (nửa kilôgram)","Lượng từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["公斤","gōngjīn","kilogram","Lượng từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["贵","guì","mắc, đắt","Tính từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["了","le","(trợ từ)","Trợ từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["吧","ba","(trợ từ) dùng ở cuối câu tỏ ý thương lượng, đề nghị","Trợ từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["多少","duōshao","bao nhiêu","Đại từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["多","duō","nhiều","Tính từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["少","shǎo","ít","Tính từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["块","kuài","đồng (đơn vị tiền tệ)","Lượng từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["角","jiǎo","hào (đơn vị tiền tệ)","Lượng từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["分","fēn","xu (đơn vị tiền tệ)","Lượng từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["还","hái","còn","Phó từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["别的","biéde","cái khác, thứ khác","Đại từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["橘子","júzi","quýt","Danh từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["怎么","zěnme","thế nào","Đại từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["卖","mài","bán","Động từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["两","liǎng","hai","Số từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["一共","yígòng","tổng cộng, tất cả","Phó từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["给","gěi","trao, đưa, cho","Động từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],
  ["找","zhǎo","thối (tiền), tìm","Động từ",8,"苹果一斤多少钱 (Một cân táo bao nhiêu tiền)"],

  // ──────── Bài 9: 我换人民币 (Tôi đổi nhân dân tệ) ────────
  ["下午","xiàwǔ","buổi chiều","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["上午","shàngwǔ","buổi sáng","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["图书馆","túshūguǎn","thư viện","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["换","huàn","đổi, thay","Động từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["小姐","xiǎojie","cô","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["营业员","yíngyèyuán","nhân viên bán hàng","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["人民币","rénmínbì","Nhân dân tệ","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["人民","rénmín","nhân dân","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["百","bǎi","trăm","Số từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["千","qiān","ngàn","Số từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["万","wàn","vạn","Số từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["美元","měiyuán","đôla Mỹ","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["港币","gǎngbì","đôla Hồng Kông","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["日元","rìyuán","đồng Yên (Nhật)","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["欧元","ōuyuán","đồng Euro","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["等","děng","đợi","Động từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["一会儿","yíhuìr","một lúc, một lát","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["先生","xiānsheng","ông, ngài","Danh từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],
  ["数","shǔ","đếm","Động từ",9,"我换人民币 (Tôi đổi nhân dân tệ)"],

  // ──────── Bài 10: 他住哪儿 (Ông ấy ở đâu) ────────
  ["办公室","bàngōngshì","văn phòng","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["办公","bàngōng","làm việc","Động từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["职员","zhíyuán","nhân viên, viên chức","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["在","zài","ở, tại","Giới từ/Động từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["家","jiā","nhà","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["呢","ne","(trợ từ) dùng ở cuối câu biểu thị ngữ khí khẳng định","Trợ từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["住","zhù","ở, ngụ","Động từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["楼","lóu","lầu, toà nhà lầu","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["门","mén","cửa","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["房间","fángjiān","phòng","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["号","hào","số","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["知道","zhīdào","biết","Động từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["电话","diànhuà","điện thoại","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["电","diàn","điện","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["话","huà","lời nói","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["号码","hàomǎ","số, mã số","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["零","líng","lẻ, số 0","Số từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["手机","shǒujī","điện thoại di động","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["手","shǒu","tay","Danh từ",10,"他住哪儿 (Ông ấy ở đâu)"],
  ["李昌浩","Lǐ Chānghào","Lee Changho (tên người Hàn Quốc)","Danh từ riêng",10,"他住哪儿 (Ông ấy ở đâu)"],

  // ──────── Bài 11: 我们都是留学生 (Chúng tôi đều là lưu học sinh) ────────
  ["秘书","mìshū","thư ký","Danh từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["先","xiān","trước, trước tiên","Phó từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["介绍","jièshào","giới thiệu","Động từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["一下儿","yíxiàr","một tí, một chút","Phó từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["位","wèi","vị","Lượng từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["教授","jiàoshòu","giáo sư","Danh từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["校长","xiàozhǎng","hiệu trưởng","Danh từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["欢迎","huānyíng","hoan nghênh","Động từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["留学生","liúxuéshēng","lưu học sinh, học sinh người nước ngoài","Danh từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["留学","liúxué","du học","Động từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["也","yě","cũng","Phó từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["我们","wǒmen","chúng tôi, chúng ta","Đại từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["你们","nǐmen","các bạn, các anh, các chị","Đại từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["他们","tāmen","họ, bọn họ","Đại từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["都","dōu","đều","Phó từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["和","hé","và, với, cùng","Liên từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["俩","liǎ","hai người","Số từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["学生","xuésheng","học sinh","Danh từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["没什么","méi shénme","không có chi, không sao","Cụm từ",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["马","Mǎ","họ Mã","Danh từ riêng",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["田芳","Tián Fāng","Điền Phương","Danh từ riêng",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["罗兰","Luólán","Rô-lăng (Roland)","Danh từ riêng",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],
  ["爱德华","Àidéhuá","Et-uốt (Edward)","Danh từ riêng",11,"我们都是留学生 (Chúng tôi đều là lưu học sinh)"],

  // ──────── Bài 12: 你在哪儿学习 (Bạn học ở đâu) ────────
  ["语言","yǔyán","ngôn ngữ","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["大学","dàxué","đại học","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["怎么样","zěnmeyàng","như thế nào","Đại từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["觉得","juéde","cảm thấy","Động từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["语法","yǔfǎ","ngữ pháp","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["听","tīng","nghe","Động từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["比较","bǐjiào","khá, tương đối, so sánh","Phó từ/Động từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["容易","róngyì","dễ, dễ dàng","Tính từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["读","dú","đọc","Động từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["写","xiě","viết","Động từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["但是","dànshì","nhưng","Liên từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["新","xīn","mới","Tính từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["同学","tóngxué","bạn học","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["同屋","tóngwū","bạn cùng phòng","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["班","bān","lớp","Danh từ",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["北京语言大学","Běijīng Yǔyán Dàxué","Đại học Ngôn ngữ Bắc Kinh","Danh từ riêng",12,"你在哪儿学习 (Bạn học ở đâu)"],
  ["林","Lín","họ Lâm","Danh từ riêng",12,"你在哪儿学习 (Bạn học ở đâu)"],

  // ──────── Bài 13: 这不是中药 (Cái này không phải thuốc đông y) ────────
  ["没有","méi yǒu","không có, không, chưa","Phó từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["箱子","xiāngzi","vali, hòm, rương","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["有","yǒu","có","Động từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["这儿","zhèr","ở đây","Đại từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["重","zhòng","nặng","Tính từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["黑","hēi","đen","Tính từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["红","hóng","đỏ","Tính từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["轻","qīng","nhẹ","Tính từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["旧","jiù","cũ","Tính từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["药","yào","thuốc","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["中药","zhōngyào","thuốc đông y, thuốc bắc","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["西药","xīyào","thuốc tây","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["茶叶","cháyè","trà","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["里","lǐ","trong, bên trong","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["日用品","rìyòngpǐn","đồ dùng hàng ngày","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["件","jiàn","cái (áo...)","Lượng từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["衣服","yīfu","áo, quần áo, y phục","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["把","bǎ","cái (lượng từ dùng cho vật có tay cầm)","Lượng từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["雨伞","yǔsǎn","cái dù, ô","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["雨","yǔ","mưa","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["瓶","píng","bình, chai","Lượng từ/Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["香水","xiāngshuǐ","nước hoa","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["水","shuǐ","nước","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["本","běn","cuốn, quyển (lượng từ dùng cho sách vở)","Lượng từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["词典","cídiǎn","từ điển","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["张","zhāng","tờ, tấm (giấy, tranh...)","Lượng từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["光盘","guāngpán","CD; VCD; DVD","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["支","zhī","cây (bút, viết)","Lượng từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],
  ["笔","bǐ","bút, viết","Danh từ",13,"这不是中药 (Cái này không phải thuốc đông y)"],

  // ──────── Bài 14: 你的车是新的还是旧的 (Xe của bạn mới hay cũ) ────────
  ["经理","jīnglǐ","giám đốc","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["好久","hǎojiǔ","thời gian dài, rất lâu","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["啊","à","A (thán từ)","Thán từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["马马虎虎","mǎmahūhū","tàm tạm","Tính từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["最近","zuìjìn","gần đây","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["刚","gāng","vừa","Phó từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["开学","kāi xué","khai trường, khai giảng","Động từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["开","kāi","mở","Động từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["有点儿","yǒu diǎnr","có một chút, hơi","Phó từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["点儿","diǎnr","chút, chút ít","Lượng từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["还是","háishi","hay, hay là","Liên từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["咖啡","kāfēi","cà phê","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["杯","bēi","ly","Lượng từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["车","chē","xe","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["自行车","zìxíngchē","xe đạp","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["汽车","qìchē","ô tô","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["摩托车","mótuōchē","xe máy","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["出租车","chūzūchē","taxi","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["颜色","yánsè","màu, màu sắc","Danh từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["蓝","lán","xanh da trời","Tính từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["辆","liàng","chiếc, cái (lượng từ của xe)","Lượng từ",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],
  ["关","Guān","Quan (họ)","Danh từ riêng",14,"你的车是新的还是旧的 (Xe của bạn mới hay cũ)"],

  // ──────── Bài 15: 你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên) ────────
  ["全","quán","toàn, tất cả, cả","Tính từ/Phó từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["照片","zhàopiàn","hình, ảnh chụp","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["看","kàn","xem, nhìn, trông, đọc","Động từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["姐姐","jiějie","chị gái","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["只","zhǐ","chỉ","Phó từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["做","zuò","làm","Động từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["大夫","dàifu","bác sĩ","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["医院","yīyuàn","bệnh viện","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["公司","gōngsī","công ty","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["商店","shāngdiàn","cửa hàng","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["律师","lǜshī","luật sư","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["外贸","wàimào","ngoại thương","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["小","xiǎo","nhỏ","Tính từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["大概","dàgài","khoảng, đại khái","Phó từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"],
  ["外国","wàiguó","nước ngoài","Danh từ",15,"你公司有多少职员 (Công ty bạn có bao nhiêu nhân viên)"]
];
