// ============================================================
// QUYỂN 2 - Giáo trình Hán ngữ Tập 1 - Quyển 2 (HSK 2)
// Format: [Hán tự, Pinyin, Nghĩa, Từ loại, Số bài, Tên bài]
// ============================================================

const HSK2_LESSONS = {
  1: "Từ mới trang 17",
  2: "Từ mới trang 71",
  3: "Từ bổ sung trang 89",
  4: "Từ bổ sung trang 112",
  5: "Từ mới trang 117",
  6: "Từ bổ sung trang 123",
  7: "Từ bổ sung trang 127",
  8: "Từ mới trang 132",
  9: "Từ mới trang 148",
  10: "Từ bổ sung trang 175"
};

const HSK2 = [
  // ──────── Từ mới trang 17 ────────
  ["出来","chūlai","đi ra (to move from inside to outside)","Động từ",1,"Từ mới trang 17"],
  ["来","lái","đến (to come)","Động từ",1,"Từ mới trang 17"],
  ["正在","zhèngzài","đang (in the process of)","Phó từ",1,"Từ mới trang 17"],
  ["音乐","yīnyuè","âm nhạc (music)","Danh từ",1,"Từ mới trang 17"],
  ["没有","méiyǒu","không có, chưa (have not)","Phó từ",1,"Từ mới trang 17"],
  ["正","zhèng","đang (be doing)","Phó từ",1,"Từ mới trang 17"],
  ["录音","lùyīn","ghi âm (recording)","Động từ/Danh từ",1,"Từ mới trang 17"],
  ["事","shì","sự việc, chuyện (matter)","Danh từ",1,"Từ mới trang 17"],
  ["书店","shūdiàn","hiệu sách (bookstore)","Danh từ",1,"Từ mới trang 17"],
  ["想","xiǎng","muốn, nghĩ (to want to)","Động từ",1,"Từ mới trang 17"],
  ["汉英","Hàn-Yīng","Hán-Anh","Tính từ",1,"Từ mới trang 17"],
  ["坐","zuò","ngồi, đi (xe) (to travel by)","Động từ",1,"Từ mới trang 17"],
  ["挤","jǐ","đông đúc, chen chúc (crowded)","Tính từ/Động từ",1,"Từ mới trang 17"],
  ["骑","qí","cưỡi, đi (xe đạp, ngựa) (to ride)","Động từ",1,"Từ mới trang 17"],
  ["行","xíng","được, OK (all right)","Động từ/Tính từ",1,"Từ mới trang 17"],
  ["门","mén","môn (lượng từ môn học)","Lượng từ",1,"Từ mới trang 17"],
  ["课","kè","bài học, tiết học (lesson)","Danh từ",1,"Từ mới trang 17"],
  ["综合","zōnghé","tổng hợp (comprehensive)","Tính từ",1,"Từ mới trang 17"],
  ["口语","kǒuyǔ","khẩu ngữ (spoken language)","Danh từ",1,"Từ mới trang 17"],
  ["听力","tīnglì","thính lực, nghe (listening)","Danh từ",1,"Từ mới trang 17"],
  ["阅读","yuèdú","đọc hiểu (reading)","Động từ/Danh từ",1,"Từ mới trang 17"],
  ["文化","wénhuà","văn hóa (culture)","Danh từ",1,"Từ mới trang 17"],
  ["体育","tǐyù","thể dục (physical training)","Danh từ",1,"Từ mới trang 17"],
  ["教","jiāo","dạy (to teach)","Động từ",1,"Từ mới trang 17"],

  // ──────── Từ mới trang 71 ────────
  ["洗澡","xǐ zǎo","tắm (to take a shower)","Động từ",2,"Từ mới trang 71"],
  ["洗","xǐ","rửa, giặt (to wash)","Động từ",2,"Từ mới trang 71"],
  ["然后","ránhòu","sau đó (then)","Liên từ/Phó từ",2,"Từ mới trang 71"],
  ["睡觉","shuì jiào","ngủ (to sleep)","Động từ",2,"Từ mới trang 71"],
  ["爬","pá","leo, trèo (to climb)","Động từ",2,"Từ mới trang 71"],
  ["们","men","các, những (hậu tố thêm vào chữ đại từ/danh từ)","Trợ từ",2,"Từ mới trang 71"],
  ["山","shān","núi (mountain)","Danh từ",2,"Từ mới trang 71"],
  ["年级","niánjí","lớp, năm học (grade)","Danh từ",2,"Từ mới trang 71"],
  ["出发","chūfā","xuất phát (to start out)","Động từ",2,"Từ mới trang 71"],
  ["前","qián","trước (front)","Danh từ",2,"Từ mới trang 71"],
  ["集合","jíhé","tập trung, tập hợp (to assemble)","Động từ",2,"Từ mới trang 71"],
  ["刻","kè","khắc, 15 phút (quarter)","Danh từ",2,"Từ mới trang 71"],
  ["上车","shàng chē","lên xe (to get on a bus)","Động từ",2,"Từ mới trang 71"],
  ["下车","xià chē","xuống xe (to get off a bus)","Động từ",2,"Từ mới trang 71"],
  ["准时","zhǔnshí","đúng giờ (punctual)","Tính từ",2,"Từ mới trang 71"],
  ["带","dài","mang theo, đem (to take)","Động từ",2,"Từ mới trang 71"],
  ["山本","Shānběn","Sơn Bản (Yamahon)","Danh từ riêng",2,"Từ mới trang 71"],

  // ──────── Từ bổ sung xuất hiện ở trang 89 ────────
  ["歌","gē","bài hát (song)","Danh từ",3,"Từ bổ sung xuất hiện ở trang 89"],
  ["太极拳","tàijíquán","Thái cực quyền","Danh từ",3,"Từ bổ sung xuất hiện ở trang 89"],
  ["足球","zúqiú","bóng đá","Danh từ",3,"Từ bổ sung xuất hiện ở trang 89"],
  ["比赛","bǐsài","trận đấu, thi đấu","Danh từ/Động từ",3,"Từ bổ sung xuất hiện ở trang 89"],
  ["网球","wǎngqiú","quần vợt (tennis)","Danh từ",3,"Từ bổ sung xuất hiện ở trang 89"],
  ["武术","wǔshù","võ thuật","Danh từ",3,"Từ bổ sung xuất hiện ở trang 89"],

  // ──────── Từ bổ sung xuất hiện ở trang 112 ────────
  ["迷路","mí lù","lạc đường","Động từ",4,"Từ bổ sung xuất hiện ở trang 112"],
  ["公共汽车","gōnggòng qìchē","xe buýt","Danh từ",4,"Từ bổ sung xuất hiện ở trang 112"],
  ["出租车","chūzūchē","taxi","Danh từ",4,"Từ bổ sung xuất hiện ở trang 112"],
  ["司机","sījī","tài xế","Danh từ",4,"Từ bổ sung xuất hiện ở trang 112"],
  ["算了","suàn le ba","thôi đi, bỏ đi","Cụm từ",4,"Từ bổ sung xuất hiện ở trang 112"],

  // ──────── Từ mới xuất hiện ở trang 117 ────────
  ["能","néng","có thể (can, be able to)","Động từ năng nguyện",5,"Từ mới xuất hiện ở trang 117"],
  ["再","zài","lại (again)","Phó từ",5,"Từ mới xuất hiện ở trang 117"],
  ["遍","biàn","lần (lượt)","Lượng từ",5,"Từ mới xuất hiện ở trang 117"],
  ["懂","dǒng","hiểu (to understand)","Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["舒服","shūfu","thoải mái, dễ chịu","Tính từ",5,"Từ mới xuất hiện ở trang 117"],
  ["意思","yìsi","ý nghĩa (meaning)","Danh từ",5,"Từ mới xuất hiện ở trang 117"],
  ["次","cì","lần (times)","Lượng từ",5,"Từ mới xuất hiện ở trang 117"],
  ["小时","xiǎoshí","giờ (đồng hồ)","Danh từ",5,"Từ mới xuất hiện ở trang 117"],
  ["请假","qǐng jià","xin nghỉ phép","Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["头疼","tóu téng","đau đầu","Tính từ/Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["头","tóu","đầu","Danh từ",5,"Từ mới xuất hiện ở trang 117"],
  ["疼","téng","đau","Tính từ/Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["发烧","fā shāo","phát sốt","Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["可能","kěnéng","có thể, có lẽ","Phó từ/Năng nguyện",5,"Từ mới xuất hiện ở trang 117"],
  ["咳嗽","késou","ho","Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["感冒","gǎnmào","cảm cúm","Động từ/Danh từ",5,"Từ mới xuất hiện ở trang 117"],
  ["了","le","rồi (trợ từ)","Trợ từ",5,"Từ mới xuất hiện ở trang 117"],
  ["看病","kàn bìng","khám bệnh","Động từ",5,"Từ mới xuất hiện ở trang 117"],
  ["病","bìng","bệnh","Danh từ/Động từ",5,"Từ mới xuất hiện ở trang 117"],

  // ──────── Từ bổ sung xuất hiện ở trang 123 ────────
  ["开车","kāi chē","lái xe","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["游泳","yóu yǒng","bơi","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["钓鱼","diào yú","câu cá","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["停车","tíng chē","đỗ xe","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["滑冰","huá bīng","trượt băng","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["拍照","pāi zhào","chụp ảnh","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["抽烟/吸烟","chōu/xī yān","hút thuốc","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["唱歌","chàng gē","hát","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["跳舞","tiào wǔ","khiêu vũ","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],
  ["打篮球","dǎ lánqiú","chơi bóng rổ","Động từ",6,"Từ bổ sung xuất hiện ở trang 123"],

  // ──────── Từ bổ sung xuất hiện ở trang 127 ────────
  ["护照","hùzhào","hộ chiếu","Danh từ",7,"Từ bổ sung xuất hiện ở trang 127"],
  ["驾照","jiàzhào","bằng lái xe","Danh từ",7,"Từ bổ sung xuất hiện ở trang 127"],

  // ──────── Từ mới xuất hiện ở trang 132 ────────
  ["不错","búcuò","không tồi, khá tốt","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["错","cuò","sai","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["进步","jìnbù","tiến bộ","Động từ/Danh từ",8,"Từ mới xuất hiện ở trang 132"],
  ["水平","shuǐpíng","trình độ","Danh từ",8,"Từ mới xuất hiện ở trang 132"],
  ["提高","tígāo","nâng cao","Động từ",8,"Từ mới xuất hiện ở trang 132"],
  ["快","kuài","nhanh","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["哪里","nǎli","đâu có (trả lời khiêm tốn)","Đại từ",8,"Từ mới xuất hiện ở trang 132"],
  ["准","zhǔn","chuẩn xác","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["流利","liúlì","lưu loát","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["努力","nǔlì","nỗ lực, chăm chỉ","Tính từ/Động từ",8,"Từ mới xuất hiện ở trang 132"],
  ["认真","rènzhēn","nghiêm túc, chăm chỉ","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["看","kàn","nhìn, xem, đánh giá","Động từ",8,"Từ mới xuất hiện ở trang 132"],
  ["为","wèi","vì, cho","Giới từ",8,"Từ mới xuất hiện ở trang 132"],
  ["这么","zhème","thế này, như thế này","Đại từ",8,"Từ mới xuất hiện ở trang 132"],
  ["那么","nàme","thế kia, như thế kia","Đại từ",8,"Từ mới xuất hiện ở trang 132"],
  ["早","zǎo","sớm","Tính từ",8,"Từ mới xuất hiện ở trang 132"],
  ["运动","yùndòng","vận động, thể thao","Động từ/Danh từ",8,"Từ mới xuất hiện ở trang 132"],
  ["跑步","pǎo bù","chạy bộ","Động từ",8,"Từ mới xuất hiện ở trang 132"],
  ["跑","pǎo","chạy","Động từ",8,"Từ mới xuất hiện ở trang 132"],
  ["篮球","lánqiú","bóng rổ","Danh từ",8,"Từ mới xuất hiện ở trang 132"],
  ["球","qiú","quả bóng","Danh từ",8,"Từ mới xuất hiện ở trang 132"],
  ["刚才","gāngcái","vừa nãy","Danh từ chỉ thời gian",8,"Từ mới xuất hiện ở trang 132"],
  ["可以","kěyǐ","có thể, được","Năng nguyện/Tính từ",8,"Từ mới xuất hiện ở trang 132"],

  // ──────── Từ mới xuất hiện ở trang 148 ────────
  ["忘","wàng","quên","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["开机","kāi jī","mở máy (điện thoại)","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["开","kāi","mở","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["又","yòu","lại (xảy ra trong quá khứ)","Phó từ",9,"Từ mới xuất hiện ở trang 148"],
  ["响","xiǎng","reo, vang lên","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["接","jiē","nhận (cuộc gọi), đón","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["踢","tī","đá","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["比赛","bǐsài","trận đấu, thi đấu","Danh từ/Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["队","duì","đội","Danh từ",9,"Từ mới xuất hiện ở trang 148"],
  ["输","shū","thua","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["赢","yíng","thắng","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["比","bǐ","tỉ số (của trận đấu), so với","Giới từ/Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["祝贺","zhùhè","chúc mừng","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["哎","āi","ôi, a (thán từ)","Thán từ",9,"Từ mới xuất hiện ở trang 148"],
  ["上","shàng","lên (học, lớp)","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["托福","Tuōfú","TOEFL","Danh từ riêng",9,"Từ mới xuất hiện ở trang 148"],
  ["已经","yǐjīng","đã...","Phó từ",9,"Từ mới xuất hiện ở trang 148"],
  ["考","kǎo","thi","Động từ",9,"Từ mới xuất hiện ở trang 148"],
  ["陪","péi","đi cùng, tháp tùng","Động từ",9,"Từ mới xuất hiện ở trang 148"],

  // ──────── Từ bổ sung xuất hiện ở trang 175 ────────
  ["嗓子","sǎngzi","cổ họng, giọng","Danh từ",10,"Từ bổ sung xuất hiện ở trang 175"],
  ["出汗","chū hàn","đổ mồ hôi","Động từ",10,"Từ bổ sung xuất hiện ở trang 175"]
];
